(function(g){var window=this;'use strict';var Fz=function(J){J.publish("cardstatechange",J.DQ()&&J.y3()?1:0)},e4=function(J,m){var S=g.W8(m),Y=S?m:arguments;
for(S=S?0:1;S<Y.length;S++){if(J==null)return;J=J[Y[S]]}return J},LWR=function(J){var m=g.UE(J);
J=g.Xo(J);return new g.OE(m.x,m.y,J.width,J.height)},qT1=function(J,m,S){var Y;
return Y=g.Wt(J,m,function(){g.Fb(Y);S.apply(J,arguments)},{})},xD=function(J){J=g.nD(J);
delete nz[J];g.de(nz)&&sg&&sg.stop()},dQb=function(){sg||(sg=new g.P$(function(){zNu()},20));
var J=sg;J.isActive()||J.start()},zNu=function(){var J=g.OX();
g.xR(nz,function(m){wDv(m,J)});
g.de(nz)||dQb()},ce=function(J,m,S,Y){g.I8.call(this);
if(!Array.isArray(J)||!Array.isArray(m))throw Error("Start and end parameters must be arrays");if(J.length!=m.length)throw Error("Start and end points must be the same length");this.G=J;this.C=m;this.duration=S;this.A=Y;this.coords=[];this.progress=this.L=0;this.D=null},wDv=function(J,m){m<J.startTime&&(J.endTime=m+J.endTime-J.startTime,J.startTime=m);
J.progress=(m-J.startTime)/(J.endTime-J.startTime);J.progress>1&&(J.progress=1);J.L=1E3/(m-J.D);J.D=m;UQv(J,J.progress);J.progress==1?(J.J=0,xD(J),J.onFinish(),J.XL()):J.isPlaying()&&J.ga()},UQv=function(J,m){typeof J.A==="function"&&(m=J.A(m));
J.coords=Array(J.G.length);for(let S=0;S<J.G.length;S++)J.coords[S]=(J.C[S]-J.G[S])*m+J.G[S]},iB1=function(J,m){g.Om.call(this,J);
this.coords=m.coords;this.x=m.coords[0];this.y=m.coords[1];this.z=m.coords[2];this.duration=m.duration;this.progress=m.progress;this.fps=m.L;this.state=m.J},b9=function(J,m,S,Y,h){ce.call(this,m,S,Y,h);
this.element=J},Og=function(J,m,S,Y,h){if(m.length!=2||S.length!=2)throw Error("Start and end points must be 2D");
b9.call(this,J,m,S,Y,h)},lWt=function(J){return Math.pow(J,3)},fWs=function(J){return 3*J*J-2*J*J*J},ZT=function(J){return J.baseUrl||null},Ik=function(J,m){return g.wF(g.lV(J,m),S=>!!S)},ti1=function(J,m,S){function Y(An){var iV=An.hovercardButton;
if(!iV)return null;iV=iV.subscribeButtonRenderer;if(!iV)return null;var CD=V(iV.unsubscribedButtonText),Zz=V(iV.subscribedButtonText);if(iV.subscribed){var bV=V(iV.subscriberCountWithUnsubscribeText);var ph=V(iV.subscriberCountText)}else bV=V(iV.subscriberCountText),ph=V(iV.subscriberCountWithSubscribeText);var i6=null;return An.signinEndpoint&&((i6=e4(An,"signinEndpoint","webNavigationEndpointData","url"))||(i6=g.U(iV.signInEndpoint?.commandMetadata,g.oQ)?.url),!i6)?null:CD&&(Zz||i6)?{subscribed:iV.subscribed,
subscribeText:CD,subscribeCount:bV,unsubscribeText:Zz,unsubscribeCount:ph,enabled:iV.enabled,signinUrl:i6,classic:An.useClassicSubscribeButton}:null}
function h(An){if(An){var iV=[],CD=An.videoId;CD&&iV.push("v="+CD);(CD=An.playlistId)&&iV.push("list="+CD);(An=An.startTimeSeconds)&&iV.push("t="+An);return"/watch?"+iV.join("&")}}
function V(An){if(!An)return null;var iV=An.simpleText;return iV?iV:An.runs?g.lV(An.runs,CD=>CD.text).join(""):null}
m=m.endscreenElementRenderer;if(!m)return null;var K=m.style,E=m.endpoint||{},T=null,k=null,y=!1,D=null,R=null,r=null,W=null,b=!1,v=null,q=null,d=null,w=null,f=null,mt=null;if(K==="VIDEO")g.U(E,g.JI)?T=g.U(E,g.JI).url:(mt=g.U(E,g.cR),T=h(mt)),k=!1,D=J,m.thumbnailOverlays?(y=m.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,R=V(y.text),y=y.style==="LIVE"):R=V(m.videoDuration);else if(K==="PLAYLIST")g.U(E,g.JI)?T=g.U(E,g.JI).url:(mt=g.U(E,g.cR),T=h(mt)),k=!1,D=J,r=V(m.playlistLength);else if(K===
"CHANNEL"){if(b=e4(E,"browseEndpoint","browseId"))W=b,T=`/channel/${W}`;k=!1;D="new";(b=!!m.isSubscribe)?v=Y(m):q=V(m.subscribersText)}else K==="WEBSITE"?((d=e4(E,"urlEndpoint","url"))&&(T=d),k=!0,D="new",d=m.icon.thumbnails[0].url):K==="CREATOR_MERCHANDISE"&&(m.productPrice&&(w=V(m.productPrice)),m.additionalFeesText&&(f=V(m.additionalFeesText)),(k=e4(E,"urlEndpoint","url"))&&(T=k),k=!0,D="new");J=e4(m,"title","accessibility","accessibilityData","label");var rF=m.endpoint?m.endpoint.clickTrackingParams:
null,xf="";if(m.metadata){let An=V(m.metadata);An&&(xf=An)}return{id:`element-${S}`,type:K,title:V(m.title),metadata:xf,callToAction:V(m.callToAction),oX:m.image,iconUrl:d,left:Number(m.left),width:Number(m.width),top:Number(m.top),aspectRatio:Number(m.aspectRatio),startMs:Math.floor(Number(m.startMs)),endMs:Math.floor(Number(m.endMs)),videoDuration:R,Pb:y,playlistLength:r,channelId:W,subscribeButton:v,subscribersText:q,isSubscribe:b,targetUrl:T||null,Yw:k,sessionData:rF?{itct:rF}:null,jc:D,K0:J?
J:null,isPlaceholder:m.isPlaceholder,impressionUrls:Ik(m.impressionUrls||[],ZT),dT:Ik(m.hovercardShowUrls||[],ZT),clickUrls:Ik(E.loggingUrls||[],ZT),visualElement:g.uk(m.trackingParams),productPrice:w,additionalFeesText:f,watchEndpoint:mt||null}},Gd=function(J,m){var S={startMs:Math.floor(Number(J.startMs)),
impressionUrls:Ik(J.impressionUrls||[],ZT),elements:Ik(J.elements||[],(Y,h)=>ti1(m,Y,h))};
J.trackingParams&&(S.visualElement=g.uk(J.trackingParams));return S},A_=function(J){return J.player.U().playerStyle==="creator-endscreen-editor"},HBR=function(J){return J.player.getVideoData().y8?"current":J.W?"new":"current"},ve=function(J,m,S=!0){J.player.h8("creatorendscreen");
J.K&&(J.K.dispose(),J.K=null,J.A.dispose(),J.A=null);for(var Y of Object.values(J.G))Y.dispose();J.G={};J.L={};J.B.length>0&&(J.B.forEach(h=>{h.dispose()}),J.B.length=0);
J.J&&(g.bw(J.J,"ytp-ce-element-show"),J.J.setAttribute("aria-hidden","true"));J.C=0;if((J.endscreen=m)&&m.elements){S&&aWe(J);S=[];Y=new g.hq(m.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});S.push(Y);J.player.U().K||(J.K=new g.C({S:"div",Z:"ytp-ce-shadow"}),g.H9(J.player,J.K.element,4),J.A=new g.w3(J.K,200));for(Y=0;Y<m.elements.length;++Y){let h=m.elements[Y],V=XDv(J,h);if(!V){g.CR(new g.pe("buildEndscreenElement null",h));continue}J.G[h.id]=V;J.L[h.id]=h;g.H9(J.player,
V.element,4);let K=new g.hq(h.startMs,h.endMs,{id:"ytp-ce-element-"+h.id,namespace:"creatorendscreen"});S.push(K);CXk(J,V,h)}J.player.zc(S);J.O9()}},Miv=function(J){var m=J.player.getVideoData(),S=m.videoId;
J.D&&J.D.abort();S={method:"POST",onFinish:h=>{var V=J.D=null;h.status===200&&(h=h.responseText,h.substring(0,3)===")]}"&&(h=h.substring(3),V=JSON.parse(h),V=Gd(V,HBR(J))));ve(J,V)},
urlParams:{v:S},withCredentials:!0};J.W&&(S.urlParams.ptype="embedded");var Y=m.nN;Y&&(S.postParams={ad_tracking:Y});if(m=g.Dti(m))if(m=g.Lh(m),m=g.G6(m))J.D=g.Wo(m,S)},aWe=function(J){var m=g.zY(),S=g.dL();
S&&m&&J.endscreen.visualElement&&g.CK(g.kS)(void 0,S,m,J.endscreen.visualElement)},XDv=function(J,m){var S=null;
switch(m.type){case "VIDEO":J={S:"div",w2:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":m.K0||"","aria-hidden":"true"},Y:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-covering-image",O:u9(m)},{S:"div",Z:"ytp-ce-covering-shadow-top"},{S:"a",Z:"ytp-ce-covering-overlay",O:{href:Lz(J,m.targetUrl),tabindex:"-1"},Y:[{S:"div",w2:["ytp-ce-video-title","ytp-webkit-ellipsis"],O:{dir:g.uw(m.title||"")},g2:m.title},{S:"div",Z:m.Pb?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
g2:m.videoDuration||void 0}]}]};S=new g.C(J);break;case "PLAYLIST":J={S:"div",w2:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":m.K0||"","aria-hidden":"true"},Y:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-covering-image",O:u9(m)},{S:"div",Z:"ytp-ce-covering-shadow-top"},{S:"a",Z:"ytp-ce-covering-overlay",O:{href:Lz(J,m.targetUrl),tabindex:"-1"},Y:[{S:"div",w2:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],O:{dir:g.uw(m.title||"")},g2:m.title},{S:"div",Z:"ytp-ce-playlist-count",
Y:[{S:"div",Z:"ytp-ce-playlist-icon"},{S:"div",Z:"ytp-ce-playlist-count-text",g2:m.playlistLength||void 0}]}]}]};S=new g.C(J);break;case "CHANNEL":S={S:"div",w2:["ytp-ce-element","ytp-ce-channel",m.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":m.K0||"","aria-hidden":"true"},Y:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",
Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body-padding",Y:[{S:"a",w2:["ytp-ce-channel-title","ytp-ce-link"],O:{href:Lz(J,m.targetUrl),target:"_blank",tabindex:"-1",dir:g.uw(m.title||"")},g2:m.title},m.subscribeButton?{S:"div",Z:"ytp-ce-subscribe-container",Y:[{S:"div",Z:"ytp-ce-channel-subscribe"}]}:"",m.subscribersText?{S:"div",Z:"ytp-ce-channel-subscribers-text",O:m.K0?{"aria-hidden":"true"}:{},g2:m.subscribersText}:"",m.metadata?{S:"div",w2:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],g2:m.metadata}:""]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",O:u9(m)}]};S=new g.C(S);let h=g.lj(document,"div","ytp-ce-channel-subscribe",S.element)[0];if(m.subscribeButton&&m.channelId){g.xd(h,"ytp-ce-subscribe-button");let V;if(J.player.U().K){var Y=null;V=m.sessionData.itct}else Y="endscreen",V=null;Y=new g.iG(m.subscribeButton.subscribeText,m.subscribeButton.subscribeCount,m.subscribeButton.unsubscribeText,m.subscribeButton.unsubscribeCount,!!m.subscribeButton.enabled,
!!m.subscribeButton.classic,m.channelId,!!m.subscribeButton.subscribed,Y,V,J.player,!1);h.appendChild(Y.element);J.B.push(Y)}break;case "WEBSITE":J={S:"div",w2:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":m.K0||"","aria-hidden":"true"},Y:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body",
Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body-padding",Y:[{S:"div",Z:"ytp-ce-website-title",O:{dir:g.uw(m.title||"")},g2:m.title},{S:"div",Z:"ytp-ce-website-metadata",g2:m.metadata},{S:"a",w2:["ytp-ce-website-goto","ytp-ce-link"],O:{href:Lz(J,m.targetUrl),target:"_blank",tabindex:"-1"},g2:m.callToAction}]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",O:u9(m)},{S:"div",Z:"ytp-ce-expanding-icon",O:Jmu(m.iconUrl)}]};S=new g.C(J);break;case "CREATOR_MERCHANDISE":S="",m.productPrice&&(S={S:"div",Z:"ytp-ce-merchandise-price-container",
Y:[{S:"div",Z:"ytp-ce-merchandise-price",g2:m.productPrice}]},m.additionalFeesText&&S.Y.push({S:"div",Z:"ytp-ce-merchandise-additional-fees",g2:m.additionalFeesText})),J={S:"div",w2:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":m.K0||"","aria-hidden":"true"},Y:[{S:"div",Z:"ytp-ce-element-shadow"},{S:"div",Z:"ytp-ce-expanding-overlay",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-hider"},{S:"div",Z:"ytp-ce-expanding-overlay-background"},{S:"div",Z:"ytp-ce-expanding-overlay-content",
Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body",Y:[{S:"div",Z:"ytp-ce-expanding-overlay-body-padding",Y:[{S:"div",Z:"ytp-ce-merchandise-title",O:{dir:g.uw(m.title||"")},g2:m.title},S,{S:"div",Z:"ytp-ce-merchandise-metadata",g2:m.metadata},{S:"a",w2:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:Lz(J,m.targetUrl),target:"_blank",tabindex:"-1"},g2:m.callToAction}]}]}]}]},{S:"div",Z:"ytp-ce-expanding-image",O:u9(m)},{S:"div",Z:"ytp-ce-merchandise-invideo-cta-container",Y:[{S:"div",Z:"ytp-ce-merchandise-invideo-cta",
g2:m.callToAction||void 0}]}]},S=new g.C(J)}m.isPlaceholder&&g.xd(S.element,"ytp-ce-placeholder");return S},CXk=function(J,m,S){function Y(){K(1)}
function h(){K(-1)}
m.listen("mouseenter",()=>{ql(J,m,S)});
m.listen("mouseleave",()=>{zd(J,m,S)});
J.player.U().K||m.listen("click",()=>{g.xd(m.element,"ytp-ce-element-hover")});
m.listen("click",E=>{mCv(J,S,E)});
m.listen("keypress",E=>{mCv(J,S,E)});
m.listen("focus",()=>{ql(J,m,S)});
m.listen("blur",()=>{zd(J,m,S)});
m.listen("touchstart",()=>{ql(J,m,S)});
var V=g.fV("ytp-ce-expanding-overlay-hider",m.element);V&&m.j(V,"touchstart",E=>{E.stopPropagation();g.bw(m.element,"ytp-ce-element-hover");g.bw(m.element,"ytp-ce-force-expand")});
m.listen("keydown",E=>{J.eN=E.keyCode===9&&!E.shiftKey});
var K=E=>{J.C+=E;J.C>0?(g.xd(m.element,"ytp-ce-force-expand"),d0(J,S.id,!0)):(g.bw(m.element,"ytp-ce-force-expand"),g.bw(m.element,"ytp-ce-element-hover"),d0(J,S.id,!1))};
V=E=>{E&&(m.listen("blur",()=>{E.style.display!="none"&&J.eN&&E.focus()}),m.j(E,"focus",Y),m.j(E,"blur",h))};
V(g.fV("ytp-sb-subscribe",m.element));V(g.fV("ytp-sb-unsubscribe",m.element));m.listen("focus",Y);m.listen("blur",h)},w0=function(J,m,S){function Y(){V||(h++,h===m.length&&(K.stop(),S&&S()))}
if(!m||m.length===0||A_(J))S&&S();else{m=SQs(J,m);var h=0,V=!1,K=new g.P$(()=>{V=!0;S&&S()},1E3,J);
K.start();for(J=0;J<m.length;J++)g.KP(m[J],Y)}},u9=function(J){if(J.oX)var m=J.oX.thumbnails;
return Jmu(m?m[m.length-1].url:null)},Lz=function(J,m){J=J.player.U();
if(m){if(m.startsWith("//"))return J.protocol+":"+m;if(m.startsWith("/"))return g.bh(J)+m}else return"";return m},Jmu=function(J){return J?{style:"background-image: url("+J+")"}:{}},ql=function(J,m,S){g.sH(m.element,"ytp-ce-element-hover")||(S.type==="VIDEO"||S.type==="PLAYLIST"?g.xd(m.element,"ytp-ce-element-hover"):J.player.U().K?(new g.P$(()=>{g.xd(m.element,"ytp-ce-element-hover")},200)).start():g.xd(m.element,"ytp-ce-element-hover"),w0(J,S.dT),d0(J,S.id,!0))},zd=function(J,m,S){g.bw(m.element,
"ytp-ce-element-hover");
g.bw(m.element,"ytp-ce-force-expand");d0(J,S.id,!1)},mCv=function(J,m,S){if(m.targetUrl&&(!S||S.type!=="keypress"||S.keyCode===13)){for(var Y=S.target;Y&&!g.sH(Y,"ytp-ce-element");){g.sH(Y,"subscribe-label")&&Ug(J,m);
if(g.sH(Y,"ytp-ce-channel-subscribe"))return;Y=Y.parentElement||null}if(!Y||g.sH(Y,"ytp-ce-element-hover")){S.preventDefault();S.stopPropagation();if(Y=J.G[m.id])zd(J,Y,m),Y.element.blur();if(S.ctrlKey||S.metaKey||m.jc==="new")Ug(J,m),J.player.sendVideoStatsEngageEvent(17,void 0),J.player.pauseVideo(),S=g.Lh(Lz(J,m.targetUrl)),S=g.G6(S),g.FI(S,void 0,m.sessionData);else{let h=g.PH(J.player.U())||J.player.getVideoData().y8,V=()=>{var K=Lz(J,m.targetUrl),E=m.sessionData,T=m.watchEndpoint,k=g.YI(K);
h&&k&&(k.v||k.list)?J.player.YA(k.v,E,k.list,!1,void 0,T||void 0):g.Wx(K,E)};
Ug(J,m,()=>{J.player.sendVideoStatsEngageEvent(17,V)})}}}},d0=function(J,m,S){J.K&&(S?J.A.show():J.A.hide());
for(let Y of Object.keys(J.G))Y!==m&&g.Zh(J.G[Y].element,"ytp-ce-element-shadow-show",S)},Ug=function(J,m,S){w0(J,m.clickUrls,S);
(J=g.dL())&&m.Yw&&g.F_(J,m.visualElement)},SQs=function(J,m){var S=J.player.getVideoData().clientPlaybackNonce;
J=J.player.getCurrentTime().toFixed(2);S={CPN:S,AD_CPN:S,MT:J};J=[];for(let Y=0;Y<m.length;Y++)J.push(jdu(m[Y],S));return J},jdu=function(J,m){return J.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,S=>{var Y=unescape(S);
Y=Y.substring(1,Y.length-1);return m[Y]?escape(m[Y]):S})},YQg=function(J){return typeof J==="string"?J:""},i9=function(J,m,S){for(let Y in m)if(m[Y]===J)return J;
return S},l9=function(J){if(!J)return null;
var m=g.Lh(YQg(J.value));m=g.G6(m);if(!m)return null;var S=i9(J.target,hm1,"current");if(S==null)J=null;else{var Y=J.show_link_icon;J=new Vgv(m,S,Y==="true"||Y==="false"?Y==="true":!0,J.pause_on_navigation!=null?J.pause_on_navigation:!0)}return J},Twv=function(J){if(!J)return null;
var m=i9(J.type,$CZ),S=i9(J.trigger,Kye);J=J.url;J=Array.isArray(J)&&J.length?J[0]:J;J=l9(J?J:null);return m?new EnR(m,S,J):null},gnb=function(J,m){return g.XQ(J.action,m)},fz=function(J,m){J="background-image: url("+J+");";
var S=[];m&&S.push(m);return{S:"div",Z:"iv-card-image",O:{style:J},Y:S}},He=function(J){return J.customMessage?t_("div","iv-card-message",J.customMessage):""},ak=function(J){if(!J.metaInfo||J.metaInfo.length===0)return"";
var m=[];for(let S of J.metaInfo)m.push(t_("li","",S));return{S:"ul",Z:"iv-card-meta-info",Y:m}},Xz=function(J,m,S,Y){if(Y)for(let h of m)J.J(h,Y,S.id,S.sessionData,S.r_.click,5)},t_=function(J,m,S){m?typeof m==="string"?m={"class":m}:Array.isArray(m)&&(m={"class":m.join(" ")}):m={};
m.dir=g.uw(S);return{S:J,O:m,g2:S}},kgu=function(J){if(!J.customMessage)return"";
var m=["iv-card-action","iv-card-primary-link"],S={};J.Ml&&(m.push("iv-card-action-icon"),S.style="background-image: url("+J.Ml+");");S.dir=g.uw(J.customMessage);var Y=[{S:"span",g2:J.customMessage}];J.showLinkIcon&&(Y.push("\u00a0"),Y.push({S:"span",Z:"iv-card-link-icon"}));return{S:"div",w2:m,O:S,Y}},ymv=function(J){var m;
(m=J)&&!(m=J.length>1?J.charAt(0)==="/"&&J.charAt(1)!=="/":J==="/")&&(m=J.replace(/^(https?:)?\/\//,"").split("/",1),m=!m||m.length<1||!m[0]?[]:m[0].toLowerCase().split(".").reverse(),m=m[0]==="com"&&m[1]==="youtube"||m[0]==="be"&&m[1]==="youtu");return m?J.indexOf("/redirect?")===-1:!1},DCk=function(J,m){return m?m:ymv(J)?"current":"new"},Cz=function(J,m,S,Y,h,V,K){J.context.J.listen(m,"click",E=>{J.d2(S,Y,h,V||[],K||0,E)});
J.context.J.listen(m,"touchstart",()=>{J.kk=!1});
J.context.J.listen(m,"touchmove",()=>{J.kk=!0})},Rmg=function(J){if(g.U(J,g.JI)?.url)return g.U(J,g.JI).url;
if((J=g.U(J,g.cR))&&J.videoId){let m="/watch?v="+J.videoId;J.playlistId&&(m+="&list="+J.playlistId);J.index&&(m+="&index="+J.index);J.startTimeSeconds&&(m+="&t="+J.startTimeSeconds);return m}return null},Ml=function(J,m,S){return{R$:(J.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
click:(S.loggingUrls||[]).map(Y=>Y.baseUrl||""),
close:(m.dismissLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
Pn:(m.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
CT:(m.clickLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||"")}},jD=function(J,m){if(m.onClickCommand&&g.U(m.onClickCommand,g.dD2)?.targetId==="engagement-panel-error-corrections"){J.N=m;
var S=!0}else S=!1;if(!S||rms(J,m))if(S=Nwg(J,m)){var Y={la:m,vZ:S.element,qJ:!1};if(m.onClickCommand)J.V.X("web_infocards_teaser_show_logging_fix")&&(J.yI||Qd1(J),J7(J,m.id),S=J.findLastIndex(Y),g.RI(J.cards,S,0,Y));else{J.isInitialized||BwI(J);J7(J,m.id);let h=J.findLastIndex(Y);g.RI(J.cards,h,0,Y);S.VE(J.G,h);J.u5()}m.autoOpen?J.addCueRange(m.startMs,0x8000000000000,m.id,()=>{J.K||(J.J=Y,mj(J),P2t(J,Y),SD(J,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(S=J.context.V.getCurrentTime()*1E3,S<5E3&&S>m.startMs&&
one(J,Y),J.addCueRange(m.startMs,m.startMs+1,m.id,()=>{one(J,Y)}),mj(J))}},Ys=function(J){J.K&&(J.FG.hide(),J.h0.G(),g.bw(J.context.V.getRootNode(),g.NE.IV_DRAWER_OPEN),J.K=!1,Fz(J.V),J.A&&J.A.stop(),J.A=new g.P$(()=>{J.aM&&(J.aM.focus(),J.aM=null)},330),J.A.start())},Wyg=function(J,m){m=m.data;
m.autoOpenMs&&J.addCueRange(m.autoOpenMs,0x8000000000000,"",()=>{SD(J,"YOUTUBE_DRAWER_AUTO_OPEN")});
m.autoCloseMs&&J.addCueRange(m.autoCloseMs,0x8000000000000,"",()=>{Ys(J)});
var S=m.headerText;g.gd(J.eX,S);J.B&&J.B.setAttribute("data-tooltip-title",S);m.eventId&&(J.eventId=m.eventId);J.A0=g.uk(m.trackingParams);J.C=g.uk(m.closeTrackingParams);J.xi=g.uk(m.iconTrackingParams)},h7=function(J,m,S){var Y=-1,h=-1;
for(let V=0;V<J.length;V++){if(J[V].height===m||J[V].width===S)return J[V];((J[V].height||0)<m||(J[V].width||0)<S)&&(Y<0||(J[Y].height||0)<(J[V].height||0)||(J[Y].width||0)<(J[V].width||0))?Y=V:((J[V].height||0)>=m||(J[V].width||0)>=S)&&(h<0||(J[h].height||0)>(J[V].height||0)||(J[h].width||0)>(J[V].width||0))&&(h=V)}return J[h>=0?h:Y]},VW=function(J,m,S,Y){return{feature:S.feature?S.feature:"cards",
src_vid:J.context.videoData.videoId,annotation_id:m,ei:J.context.videoData.eventId||"",itct:Y.trackingParams||""}},Fyk=function(J,m){var S=m.cardId?m.cardId:`cr:${J.L}`,Y=J.V.U().experiments.RM("enable_error_corrections_infocard_web_client");
if(!m.content&&m.teaser.simpleCardTeaserRenderer&&Y){Y=m.teaser.simpleCardTeaserRenderer;var h=m.icon?m.icon.infoCardIconRenderer:null;if(Y.channelAvatar&&Y.channelAvatar.thumbnails&&Y.channelAvatar.thumbnails.length>0)var V=h7(Y.channelAvatar.thumbnails,22,22).url;m={id:S,timestamp:J.L,type:"simple",teaserText:g.IE(Y.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:{},sponsored:!1,r_:{},Ta:null,mk:Y.trackingParams?
g.uk(Y.trackingParams):null,xi:h&&h.trackingParams?g.uk(h.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Ml:null,title:"",customMessage:"",url:null,onClickCommand:Y.onTapCommand||null,FS:V};jD(J,m)}else if(m.content?.simpleCardContentRenderer){if(!m.cueRanges.length)return;V=m.content?.simpleCardContentRenderer;Y=m.teaser.simpleCardTeaserRenderer;h=m.icon?m.icon.infoCardIconRenderer:null;m={id:S,timestamp:J.L,type:"simple",teaserText:g.IE(Y.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),
startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:VW(J,S,m,V),sponsored:!1,r_:Ml(V,Y,V.command),Ta:V.trackingParams?g.uk(V.trackingParams):null,mk:Y.trackingParams?g.uk(Y.trackingParams):null,xi:h&&h.trackingParams?g.uk(h.trackingParams):null,imageUrl:h7(V.image.thumbnails,290,290).url,displayDomain:V.displayDomain?g.IE(V.displayDomain):null,showLinkIcon:!!V.showLinkIcon,Ml:null,title:V.title?g.IE(V.title):"",customMessage:V.callToAction?g.IE(V.callToAction):"",url:g.U(V.command,
g.JI).url?l9({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:g.U(V.command,g.JI).url}):null,onClickCommand:null};jD(J,m)}else if(m.content?.collaboratorInfoCardContentRenderer){if(!m.cueRanges.length)return;V=m.content?.collaboratorInfoCardContentRenderer;Y=m.teaser.simpleCardTeaserRenderer;h=m.icon?m.icon.infoCardIconRenderer:null;m={id:S,timestamp:J.L,type:"collaborator",teaserText:g.IE(Y.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),
autoOpen:!!m.autoOpen,sessionData:VW(J,S,m,V),sponsored:!1,r_:Ml(V,Y,V.endpoint),Ta:V.trackingParams?g.uk(V.trackingParams):null,mk:Y.trackingParams?g.uk(Y.trackingParams):null,xi:h&&h.trackingParams?g.uk(h.trackingParams):null,channelId:g.U(V.endpoint,g.BN).browseId,customMessage:V.customText?g.IE(V.customText):null,profileImageUrl:h7(V.channelAvatar.thumbnails,290,290).url,title:V.channelName?g.IE(V.channelName):"",metaInfo:[V.subscriberCountText?g.IE(V.subscriberCountText):""],url:l9({pause_on_navigation:!J.context.videoData.isLivePlayback,
target:"new",value:g.U(V.endpoint,g.BN).canonicalBaseUrl?g.U(V.endpoint,g.BN).canonicalBaseUrl:`/channel/${g.U(V.endpoint,g.BN).browseId}`}),onClickCommand:null};jD(J,m)}else if(m.content?.playlistInfoCardContentRenderer){if(!m.cueRanges.length)return;V=m.content?.playlistInfoCardContentRenderer;Y=m.teaser.simpleCardTeaserRenderer;h=m.icon?m.icon.infoCardIconRenderer:null;m={id:S,timestamp:J.L,type:"playlist",teaserText:g.IE(Y.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),
autoOpen:!!m.autoOpen,sessionData:VW(J,S,m,V),sponsored:!1,r_:Ml(V,Y,V.action),Ta:V.trackingParams?g.uk(V.trackingParams):null,mk:Y.trackingParams?g.uk(Y.trackingParams):null,xi:h&&h.trackingParams?g.uk(h.trackingParams):null,ik:h7(V.playlistThumbnail.thumbnails,258,290).url,customMessage:V.customMessage?g.IE(V.customMessage):null,playlistVideoCount:g.IE(V.playlistVideoCount),title:V.playlistTitle?g.IE(V.playlistTitle):"",metaInfo:[V.channelName?g.IE(V.channelName):"",V.videoCountText?g.IE(V.videoCountText):
""],url:l9({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:Rmg(V.action)}),onClickCommand:null};jD(J,m)}else if(m.content?.videoInfoCardContentRenderer){if(!m.cueRanges.length)return;V=m.content?.videoInfoCardContentRenderer;Y=m.teaser.simpleCardTeaserRenderer;h=m.icon?m.icon.infoCardIconRenderer:null;m={id:S,timestamp:J.L,type:"video",teaserText:g.IE(Y.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,
sessionData:VW(J,S,m,V),sponsored:!1,r_:Ml(V,Y,V.action),Ta:V.trackingParams?g.uk(V.trackingParams):null,mk:Y.trackingParams?g.uk(Y.trackingParams):null,xi:h&&h.trackingParams?g.uk(h.trackingParams):null,ik:h7(V.videoThumbnail.thumbnails,258,290).url,videoDuration:V.lengthString?g.IE(V.lengthString):null,customMessage:V.customMessage?g.IE(V.customMessage):null,title:V.videoTitle?g.IE(V.videoTitle):"",metaInfo:[V.channelName?g.IE(V.channelName):"",V.viewCountText?g.IE(V.viewCountText):""],isLiveNow:!!V.badge,
url:l9({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:Rmg(V.action)}),onClickCommand:null};jD(J,m)}J.L++},em1=function(J,m){return g.XQ(J.cards,S=>S.la.id===m)},mj=function(J){g.Zh(J.V.getRootNode(),"ytp-cards-shopping-active",nnZ(J))},J7=function(J,m){if(m=em1(J,m))m===J.J&&(J.J=null),J.V.removeCueRange(m.la.id),g.EE(m.vZ),g.jX(J.cards,m),J.u5(),mj(J)},SD=function(J,m,S){if(!J.K){J.FG.show();
J.qB=new g.P$(()=>{g.xd(J.context.V.getRootNode(),g.NE.IV_DRAWER_OPEN)},0);
J.qB.start();J.h0.j(J.G,"mousewheel",h=>{J.GT.start();h.preventDefault();h=h||window.event;var V=0;h.type=="MozMousePixelScroll"?V=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?V=h.detail:V=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=V)J.G.scrollTop+=h});
J.K=!0;var Y=g.dL();Y&&J.A0&&J.C&&g.oE(Y,[J.A0,J.C]);m={TRIGGER_TYPE:m};for(let h of J.cards)h.qJ||(h.qJ=!0,sdZ(J.context.logger,h.la.r_.R$,m)),Y&&g.oE(Y,[h.la.Ta]);Fz(J.V);S&&(J.A=new g.P$(()=>{J.aM=J.B;J.Yk.focus()},330),J.A.start())}},BwI=function(J){g.c$(J.cS(),[g.NE.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.H9(J.V,J.D,5);J.FU();J.B=g.fV("ytp-cards-button",J.V.getRootNode());J.Yk=g.fV("iv-drawer-close-button",J.D);J.isInitialized=!0},Qd1=function(J){J.eN.push(g.Fj("iv-teaser-shown",J.jX,J));
J.eN.push(g.Fj("iv-teaser-hidden",J.YI,J));J.eN.push(g.Fj("iv-teaser-clicked",J.vS,J));J.yI=!0},rms=function(J,m){J.N=m;
var S=J.V.getVideoData();if(!S)return!1;S=g.kE(S.getWatchNextResponse());if(S?.markersMap)for(let h=0;S?.markersMap.length>h;h++){var Y=S?.markersMap[h];if(Y.key==="ERROR_CORRECTION_MARKERS"&&(Y=Y.value?.markers)&&Y.length>0)return m.startMs=g.U(Y[0],g.$Yu)?.timeRangeStartMillis||0,J.N=null,!0}return!1},Nwg=function(J,m){switch(m.type){case "simple":J=J.TT;
var S=m.displayDomain?{S:"div",Z:"iv-card-image-text",g2:m.displayDomain}:void 0;var Y=kgu(m);S={S:"div",w2:["iv-card"],Y:[{S:"a",Z:"iv-click-target",O:{href:m.url?m.url.J()||"":""},Y:[fz(m.imageUrl,S),{S:"div",Z:"iv-card-content",Y:[t_("h2",void 0,m.title),Y]}]}]};S=new g.C(S);Xz(J,g.ij("iv-click-target",S.element),m,m.url);m=S;break;case "collaborator":J=J.TT;S={S:"div",w2:["iv-card","iv-card-channel"],Y:[{S:"a",w2:["iv-click-target"],O:{href:m.url.J()||"","data-ytid":m.channelId},Y:[fz(m.profileImageUrl),
{S:"div",Z:"iv-card-content",Y:[He(m),{S:"h2",Z:"iv-card-primary-link",g2:m.title},ak(m)]}]}]};S=new g.C(S);Xz(J,g.ij("iv-click-target",S.element),m,m.url);m=S;break;case "playlist":J=J.TT;S={S:"div",w2:["iv-card","iv-card-playlist"],Y:[{S:"a",Z:"iv-click-target",O:{href:m.url.J()||""},Y:[fz(m.ik,{S:"div",Z:"iv-card-image-overlay",Y:[{S:"span",Z:"iv-card-playlist-video-count",g2:m.playlistVideoCount}]}),{S:"div",Z:"iv-card-content",Y:[He(m),t_("h2","iv-card-primary-link",m.title),ak(m)]}]}]};S=new g.C(S);
Xz(J,g.ij("iv-click-target",S.element),m,m.url);m=S;break;case "productListing":J=J.TT;var h=m.offers.length!=0;S=["iv-card"];Y="";var V=kgu(m);h&&(S.push("iv-card-product-listing"),Y="iv-card-primary-link",V=m.offers[0],h=[],V.price&&h.push({S:"div",Z:"iv-card-offer-price",g2:V.price}),V.merchant&&h.push({S:"div",Z:"iv-card-offer-merchant",g2:V.merchant}),V={S:"div",Y:h});h=m.url?m.url.J()||"":"";S={S:"div",w2:S,O:{tabindex:"0"},Y:[{S:"a",w2:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+
m.imageUrl+");",href:h,"aria-hidden":"true",tabindex:"-1"}},{S:"div",Z:"iv-card-content",Y:[m.sponsored?{S:"div",Z:"iv-card-sponsored",Y:["Sponsored",{S:"div",Z:"iv-ad-info-container",Y:[{S:"div",Z:"iv-ad-info",g2:"{{adInfo}}"},{S:"div",Z:"iv-ad-info-icon-container",Y:[{S:"div",Z:"iv-ad-info-icon"},{S:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{S:"a",Z:"iv-click-target",O:{href:h},Y:[t_("h2",Y,m.title),V]}]}]};S=new g.C(S);Y=g.Yc("span");g.gd(Y,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
S.setContent(Y,"adInfo");Xz(J,g.ij("iv-click-target",S.element),m,m.url);m=S;break;case "video":J=J.TT;S=m.isLiveNow?{S:"span",w2:["yt-badge","yt-badge-live"],g2:"LIVE NOW"}:null;S={S:"div",w2:["iv-card","iv-card-video"],Y:[{S:"a",Z:"iv-click-target",O:{href:m.url?.J()||""},Y:[fz(m.ik,m.videoDuration?{S:"span",Z:"iv-card-video-duration",g2:m.videoDuration}:void 0),{S:"div",Z:"iv-card-content",Y:[He(m),t_("h2","iv-card-primary-link",m.title),ak(m),S]}]}]};S=new g.C(S);Xz(J,g.ij("iv-click-target",S.element),
m,m.url);m=S;break;default:return null}return m},one=function(J,m){if(!g.sH(J.V.getRootNode(),"ytp-cards-teaser-shown")){if(J.J!==m){var S=g.dL(),Y=J.J?J.J.la.xi:J.xi;
S&&Y&&g.Wy(S,[Y]);J.J=m;mj(J)}(S=J.isInitialized&&J.cS().style.display=="none")||(S=J.context.V.getPlayerState(),Y=S===0&&J.context.V.getCurrentTime()===0,S=!(S===1||S===3||Y));S||m.la.teaserDurationMs&&J.V.Rd(!0,{teaserText:m.la.teaserText,durationMs:m.la.teaserDurationMs,onClickCommand:m.la.onClickCommand,FS:m.la.FS??null});J.QE.isActive()||((!J.K||!J.GT.isActive()&&J.MB)&&P2t(J,m),J.QE.start(910+m.la.teaserDurationMs))}},nnZ=function(J){return J.J?J.J.la.type==="productListing":J.V.X("enable_wn_infocards")?
!!J.cards?.length&&g.H8(J.cards,m=>m.la.type==="productListing"):g.H8(J.cards,m=>m.la.type==="productListing")},P2t=function(J,m){J.W.gX?(m=new ce([0,
J.G.scrollTop],[0,m.vZ.offsetTop],600,fWs),J.context.K.listen(m,"animate",S=>{J.G.scrollTop=S.y}),J.context.K.listen(m,"finish",S=>{J.G.scrollTop=S.y}),m.play()):(J.W.Rq(!0),J.G.scrollTop=m.vZ.offsetTop,J.W.Rq(!1))},$s=function(J){return J.J&&J.J.la?J.J.la:J.cards[0]&&J.cards[0].la?J.cards[0].la:null},xCu=function(J){var m=J.annotation.data;
"start_ms"in m&&"end_ms"in m&&J.addCueRange(Number(m.start_ms),Number(m.end_ms),J.annotation.id,()=>{J.show()},()=>{J.hide()})},cmu=function(J,m){var S=LWR(m).width;
g.dd(m,S);S=new Og(m,[S,m.offsetTop],[S-S,m.offsetTop],200,lWt);g.O(J,S);J.context.K.listen(S,"begin",()=>{g.CZ(m,!0)});
S.play()},K9=function(J,m,S){S.stopPropagation();
bHZ(J);OHR(J,m);J.J.focus()},ZHu=function(J){var m=J.annotation.data;
if(J.annotation.style==="cta")var S=6;else if(J.annotation.style==="video"||J.annotation.style==="playlist")S=7;J.L=m.collapsedelay_ms||J.L;var Y=["iv-promo","iv-promo-inactive"];J.cS().setAttribute("aria-hidden","true");J.cS().setAttribute("aria-label","Promotion");J.cS().tabIndex=0;var h=J.annotation.H3(),V=m.image_url;if(V){var K=J.createElement({S:"div",w2:["iv-promo-img","iv-click-target"]});V=J.createElement({S:"img",O:{src:V,"aria-hidden":"true"}});K.appendChild(V);m.video_duration&&!m.is_live?
(V=J.createElement({S:"span",Z:"iv-promo-video-duration",g2:m.video_duration}),K.appendChild(V)):m.playlist_length&&(V=J.createElement({S:"span",Z:"iv-promo-playlist-length",g2:m.playlist_length.toString()}),K.appendChild(V));h&&Cz(J,K,h,J.annotation.id,m.session_data,void 0,S)}h?(V=J.createElement({S:"a",Z:"iv-promo-txt"}),g.dc(V,h.J()),J.J=V):J.J=J.createElement({S:"div",Z:"iv-promo-txt"});switch(J.annotation.style){case "cta":case "website":var E=J.createElement({S:"p",Y:[{S:"strong",g2:m.text_line_1}]});
var T=J.createElement({S:"p",Y:[{S:"span",Z:"iv-promo-link",g2:m.text_line_2}]});if(V=m.text_line_3){Y.push("iv-promo-website-card-cta-redesign");var k=J.createElement({S:"button",w2:["iv-promo-round-expand-icon","ytp-button"]});V=J.createElement({S:"button",w2:["iv-button","iv-promo-button"],Y:[{S:"span",Z:"iv-button-content",g2:V}]});var y=J.createElement({S:"div",Z:"iv-promo-button-container"});y.appendChild(V);h&&Cz(J,J.cS(),h,J.annotation.id,m.session_data,void 0,S)}g.xd(J.J,"iv-click-target");
h&&Cz(J,J.J,h,J.annotation.id,m.session_data,void 0,S);break;case "playlist":case "video":E=J.createElement({S:"p",Y:[{S:"span",g2:m.text_line_1}]}),T=J.createElement({S:"p",Y:[{S:"strong",g2:m.text_line_2}]}),m.is_live&&(E=T,T=J.createElement({S:"span",w2:["yt-badge","iv-promo-badge-live"],g2:"LIVE NOW"})),g.xd(J.J,"iv-click-target"),h&&Cz(J,J.J,h,J.annotation.id,m.session_data,void 0,S),Y.push("iv-promo-video")}E&&J.J.appendChild(E);T&&J.J.appendChild(T);J.C.appendChild(J.J);y&&J.C.appendChild(y);
S=J.createElement({S:"div",Z:"iv-promo-actions"});J.G=J.createElement({S:"button",w2:["iv-promo-expand","ytp-button"]});J.G.title="Expand";J.context.J.listen(J.G,"click",D=>{K9(J,5E3,D)});
S.appendChild(J.G);g.CZ(J.G,!1);J.context.J.listen(J.cS(),"mouseover",J.GT,J);J.context.J.listen(J.cS(),"mouseout",J.TT,J);J.context.J.listen(J.cS(),"touchend",D=>{K9(J,5E3,D)});
J.K=J.createElement({S:"button",w2:["iv-promo-close","ytp-button"]});J.K.title="Close";J.context.J.listen(J.K,"click",J.annotation.style==="cta"&&m.text_line_3?J.N:J.eN,J);S.appendChild(J.K);g.c$(J.cS(),Y);K&&(g.VX(J.cS(),K),k&&K.appendChild(k));g.VX(J.cS(),J.C);g.VX(J.cS(),S)},E$=function(J){J.D&&(g.NS.clearTimeout(J.D),J.D=null)},bHZ=function(J){J.A.stop();
J.isCollapsed&&(g.OH(J.cS(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),J.isCollapsed=!1,J.J&&J.J.removeAttribute("aria-hidden"),g.CZ(J.G,!1),g.CZ(J.K,!0))},OHR=function(J,m){J.D||(J.D=g.cg(function(){E$(this);
IBv(this)},m,J))},IBv=function(J){J.isCollapsed||J.B||J.D||(g.xd(J.cS(),"iv-promo-collapsed"),J.isCollapsed=!0,J.A.start())},sdZ=function(J,m,S){m&&(S?Tl(J,m.map(Y=>g.Tx(Y,S))):Tl(J,m))},Tl=function(J,m,S,Y){var h=1,V=void 0,K=-1;
if(S){let E=!1;V=()=>{h--;h||E||(clearTimeout(K),E=!0,S())};
K=setTimeout(()=>{E=!0;S()},1E3)}for(let E of m||[])h++,g.KP(E,V);
Y&&(h++,Y!==0&&J.V.sendVideoStatsEngageEvent(Y,V))},pMu=function(J){return J==="annotation-editor"||J==="live-dashboard"},Ggs=function(J){J.D&&(J.player.removeEventListener("videodatachange",J.D),J.D=null)},Amt=function(J){J=J.createElement({S:"div",
w2:["annotation","annotation-type-custom"]});g.CZ(J,!1);return J},ks=function(J,m){var S=!1,Y=m.getElementsByTagName("annotations");
if(Y&&!(Y.length<1)&&(Y=Y[0].getAttribute("itct"))){var h=g.dL();if(h){var V=g.zY();V&&g.CK(g.gC)(void 0,h,V,[g.uk(Y)])}}m=m.getElementsByTagName("annotation");for(Y=0;Y<m.length;Y++){var K=vns(J,m[Y]);h=null;try{a:{if(!K){h=null;break a}var E=K.id;V=/.+/;let r=typeof E==="string"&&V!=null&&E!=null&&E.match(V)?E:"",W=i9(K.type,uBZ),b=i9(K.style,LyZ),v=YQg(K.data),q=v.length!==0?JSON.parse(v):{};b:{var T=K.action;V=Twv;if(T==null){var k=null;break b}if(g.W8(T)){K=[];for(let w of T){let f=V(w);f&&K.push(f)}k=
K;break b}let d=V(T);k=d?[d]:[]}V=k;h=r&&W?new qQg(r,W,b,V,q):null}}catch(r){}if(h)if(h.type==="branding"||h.type==="promotion"){V=J;K=h;var y=Amt(V),D=null;switch(K.type){case "branding":if(V.player.U().S7)break;V.player.X("web_player_overlay_positioned_layout")?(y.setAttribute("data-overlay-order","11"),V.player.Zz(y,4,!0)):V.G.element.appendChild(y);D=new zme(y,gJ(V),K);break;case "promotion":g.H9(V.player,y,4),D=new dCI(y,gJ(V),K)}D&&D.mQ();D&&(g.O(J,D),J.L[h.id]=D)}else if(h.type==="card"||h.type===
"drawer"){J.J||(J.J=wM1(J),g.O(J,J.J));if(h.type==="card"){y=J.J;var R=(S=h)&&S.data&&S.data.card_type;h=S.data;if(R)switch(V=h.tracking||{},V={R$:V.impression,click:V.click,close:V.close,Pn:V.teaser_impression,CT:V.teaser_click},K=h.tracking_params||{},D=null,R){case "collaborator":S={id:S.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,
r_:V,Ta:K.card?g.uk(K.card):null,mk:K.teaser?g.uk(K.teaser):null,xi:K.icon?g.uk(K.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,profileImageUrl:h.image_url,title:h.title,metaInfo:h.meta_info,url:l9({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};jD(y,S);break;case "playlist":S={id:S.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,
autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,r_:V,Ta:K.card?g.uk(K.card):null,mk:K.teaser?g.uk(K.teaser):null,xi:K.icon?g.uk(K.icon):null,ik:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:l9({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};jD(y,S);break;case "productListing":h.signin_url&&(D=l9({target:"current",
value:h.signin_url}));R=[];let r=h.offers||[];for(let W=0;W<r.length;W++)R.push(new UCt(g.gZ(r[W].merchant),g.gZ(r[W].price)));S={id:S.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,r_:V,Ta:K.card?g.uk(K.card):null,mk:K.teaser?g.uk(K.teaser):null,xi:K.icon?g.uk(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:
null,showLinkIcon:!!h.show_link_icon,Ml:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:l9({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),VH5:D,SRz:h.signin_title?h.signin_title:void 0,MHB:h.signin_message?h.signin_message:void 0,offers:R,onClickCommand:null};jD(y,S);break;case "simple":S={id:S.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,
startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,r_:V,Ta:K.card?g.uk(K.card):null,mk:K.teaser?g.uk(K.teaser):null,xi:K.icon?g.uk(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Ml:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:l9({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};
jD(y,S);break;case "video":S={id:S.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,r_:V,Ta:K.card?g.uk(K.card):null,mk:K.teaser?g.uk(K.teaser):null,xi:K.icon?g.uk(K.icon):null,ik:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,
url:l9({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null},jD(y,S)}}else Wyg(J.J,h);S=!0}}S&&(Fz(J.player),J.W())},iHZ=function(J){var m=J.player.U();
J=J.player.getVideoData();return(m.annotationsLoadPolicy||J.annotationsLoadPolicy)===1&&!J.Ug||m.MB.get(J.videoId)||J.rw()||g.yG(J)?!0:!1},lBe=function(J,m){m=!m.isCued()&&!m.J(1024);
J.G.Rq(m);J.K.Rq(m)},aB1=function(J,m){var S=m.videoId,Y=V=>{var K=J.loadNumber;
J.C=null;J.loaded&&J.loadNumber===K&&J.player.getVideoData().videoId===S&&(V=g.kI(V)&&V.responseXML?V.responseXML:null)&&(ks(J,V),g.xd(J.player.getRootNode(),"iv-module-loaded"))};
g.tu()&&(Y=fBX(J,Y));var h={format:"XML",onFinish:Y,onError:()=>{J.C=null},
urlParams:{}};m.isPharma&&(h.urlParams.pharma="1");h.method="POST";h.withCredentials=!0;(Y=J.player.U().MB.get(S))&&tgk(h,Y);Y=Y&&Y.AJ;if(!m.N6||Y)J.D=()=>{if(!J.N)J.onVideoDataChange(h);var V=J.player.getVideoData();V?.Ed()&&!J.eN&&HHu(J,V)},J.player.addEventListener("videodatachange",J.D)},yW=function(J,m){var S=!1;
J.J||(J.J=wM1(J),g.O(J,J.J));for(var Y of m.cards||[])Y.cardRenderer&&(Fyk(J.J,Y.cardRenderer),S=!0);S&&(J.player.getVideoData()?.Ed()||(S=J.J,Y=m.headerText?g.IE(m.headerText):"",g.gd(S.eX,Y),S.B&&S.B.setAttribute("data-tooltip-title",Y),S.context.videoData.eventId&&(S.eventId=S.context.videoData.eventId),S.A0=m.trackingParams?g.uk(m.trackingParams):null,S.C=m.closeButton.infoCardIconRenderer.trackingParams?g.uk(m.closeButton.infoCardIconRenderer.trackingParams):null,S.xi=m.icon.infoCardIconRenderer.trackingParams?
g.uk(m.icon.infoCardIconRenderer.trackingParams):null,J.W()),Fz(J.player))},HHu=function(J,m){if(m=m.getWatchNextResponse()?.cards?.cardCollectionRenderer)J.eN=!0,yW(J,m),m.headerText&&J.T8&&(m=g.IE(m.headerText),J.T8.setAttribute("data-tooltip-title",m))},fBX=function(J,m){return(...S)=>{J.EE()||J.mQ.push(g.kd.bV(()=>{m(...S)}))}},tgk=function(J,m){J.method="POST";
J.postParams=J.postParams||{};m.AJ&&(J.postParams.ic_coll=m.AJ);m.m3&&(J.postParams.ic_track=m.m3)},vns=function(J,m){var S={};
for(var Y of m.attributes)S[Y.name]=Y.nodeValue;for(Y=0;Y<m.childNodes.length;Y++){let V=m.childNodes[Y];if(!g.FQ(V)||V.nodeType!=1)continue;var h=void 0;if(S[V.tagName])h=S[V.tagName];else if(V.tagName==="data"){V.childNodes.length>0&&(h=V.childNodes[0].nodeValue,S[V.tagName]=typeof h==="string"?h.trim():h);continue}else h=[],S[V.tagName]=h;V&&V.tagName==="TEXT"?V.childNodes.length===1&&V.childNodes[0].nodeType===3?h.push(V.childNodes[0].nodeValue):h.push(""):V&&h.push(vns(J,V))}return S},gJ=function(J){if(!J.B){let m=
new XMZ(J);
g.O(J,m);let S=new g.CF(J);g.O(J,S);J.B=new C2Z(m,S,J.player.U(),J.player.getVideoData(),J.logger,J.player,J.ur)}return J.B},Mgs=function(J){var m=J.player.getVideoData();
if(m.wO){var S=J.player.U().MB.get(m.videoId);if(S){var Y={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(h,V,K)=>{h=J.loadNumber;V=m.videoId;J.loaded&&J.loadNumber===h&&J.player.getVideoData().videoId===V&&(K=g.kI(K)&&K.responseXML?K.responseXML:null)&&ks(J,K)}};
g.tu()&&(Y.onFinish=fBX(J,Y.onFinish));Y.postParams={ic_only:"1"};tgk(Y,S);J.N=!0;g.Wo(m.wO,Y)}}},wM1=function(J){var m=new g.C({S:"div"});
g.CZ(m.element,!1);var S=new JNu(J.player,m.element,gJ(J));g.O(S,m);m.VE(J.G.element);S.mQ();return S},m6R=function(J,m,S,Y,h){if(!J.player.U().S7){var V=[];
m.navigationEndpoint&&g.U(m.navigationEndpoint,g.BN)&&g.U(m.navigationEndpoint,g.BN).browseId&&V.push(new EnR("openUrl","click",new Vgv(`/channel/${g.U(m.navigationEndpoint,g.BN).browseId}`,"new",!0,!0)));var K=m.watermark.thumbnails[0];Y={channel_name:m.channelName,end_ms:m.endTimeMs,image_height:K.height,image_type:1,image_url:K.url,image_width:K.width,is_mobile:!1,session_data:{annotation_id:S,ei:h,feature:"iv",itct:m.trackingParams,src_vid:Y},start_ms:m.startTimeMs};if(m.subscribeButton&&g.U(m.subscribeButton,
g.i4)){Y.channel_id=g.U(m.subscribeButton,g.i4).channelId;m=g.U(m.subscribeButton,g.i4);K=h=null;m.subscribed?(m.subscriberCountWithUnsubscribeText&&(h=g.IE(m.subscriberCountWithUnsubscribeText)),m.subscriberCountText&&(K=g.IE(m.subscriberCountText))):(m.subscriberCountText&&(h=g.IE(m.subscriberCountText)),m.subscriberCountWithSubscribeText&&(K=g.IE(m.subscriberCountWithSubscribeText)));let E=g.U(m.signInEndpoint?.commandMetadata,g.oQ)?.url||"";m={subscribeText:g.IE(m.unsubscribedButtonText),subscribeCount:h||
"",unsubscribeText:g.IE(m.subscribedButtonText),unsubscribeCount:K||"",enabled:m.enabled||!1,classic:!1,subscribed:m.subscribed||!1,feature:"iv",signInUrl:E};Y.standalone_subscribe_button_data=m}V=new qQg(S,"branding","branding",V,Y);Y=Amt(J);J.player.X("web_player_overlay_positioned_layout")?(Y.setAttribute("data-overlay-order","11"),J.player.Zz(Y,4,!0)):J.G.element.appendChild(Y);V=new zme(Y,gJ(J),V);V.mQ();g.O(V,V);J.L[S]=V}};
g.rV.prototype.Rd=g.hn(43,function(J,m){var S=g.NA(this.aq());S&&S.Rd(J,m)});
var nz={},sg=null;g.G2(ce,g.I8);g.c=ce.prototype;g.c.getDuration=function(){return this.duration};
g.c.play=function(J){if(J||this.J==0)this.progress=0,this.coords=this.G;else if(this.isPlaying())return!1;xD(this);this.startTime=J=g.OX();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.p$();this.NU("play");this.isPaused()&&this.NU("resume");this.J=1;var m=g.nD(this);m in nz||(nz[m]=this);dQb();wDv(this,J);return!0};
g.c.stop=function(J){xD(this);this.J=0;J&&(this.progress=1);UQv(this,this.progress);this.onStop();this.XL()};
g.c.pause=function(){this.isPlaying()&&(xD(this),this.J=-1,this.NU("pause"))};
g.c.fz=function(){this.J==0||this.stop(!1);this.NU("destroy");ce.ki.fz.call(this)};
g.c.destroy=function(){this.dispose()};
g.c.ga=function(){this.NU("animate")};
g.c.NU=function(J){this.dispatchEvent(new iB1(J,this))};
g.G2(iB1,g.Om);g.G2(b9,ce);b9.prototype.K=function(){};
b9.prototype.ga=function(){this.K();b9.ki.ga.call(this)};
b9.prototype.XL=function(){this.K();b9.ki.XL.call(this)};
b9.prototype.p$=function(){this.K();b9.ki.p$.call(this)};
g.G2(Og,b9);Og.prototype.K=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var XMZ=class extends g.rX{constructor(J){super();this.G=J||window;this.J=[]}listen(J,m,S,Y){S=(0,g.sX)(S,Y||this.G);J=g.Wt(J,m,S);this.J.push(J);return J}Jm(J,m,S,Y){S=(0,g.sX)(S,Y||this.G);J=qT1(J,m,S);this.J.push(J);return J}rg(J){g.Fb(J);g.jX(this.J,J)}removeAll(){g.Fb(this.J);this.J.length=0}fz(){this.removeAll();super.fz()}};var V5k=class extends g.qa{constructor(J){super(J);this.D=this.endscreen=null;this.G={};this.L={};this.A=this.K=null;this.B=[];this.J=null;this.eN=!0;this.C=0;J=J.U();this.W=g.$P(J)||J.GT==="profilepage";this.events=new g.PW(this);g.O(this,this.events);this.events.j(this.player,g.zz("creatorendscreen"),this.onCueRangeEnter);this.events.j(this.player,g.da("creatorendscreen"),this.onCueRangeExit);this.events.j(this.player,"resize",this.O9);this.events.j(window,"focus",this.N);this.load();var m=g.Yc("STYLE");
(g.Uh("HEAD")[0]||document.body).appendChild(m);this.addOnDisposeCallback(()=>{g.EE(m)});
m.sheet&&(m.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),m.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!A_(this)){var J=g.R6V(this.player.getVideoData());J?(J=Gd(J,HBR(this)),ve(this,J,!1)):Miv(this)}}unload(){ve(this,null);this.D&&(this.D.abort(),this.D=null);super.unload()}f4(J,m){return A_(this)?J==="loadCustomEndscreenRenderer"?(J=Gd(m,"new"),ve(this,J),!0):null:null}getOptions(){return A_(this)?["loadCustomEndscreenRenderer"]:[]}O9(){if(this.endscreen&&this.endscreen.elements){var J=this.player.getVideoContentRect();if(J&&J.width!==0&&J.height!==0){var m=this.player.getPlayerSize();
if(m&&m.width!==0&&m.height!==0){var S=J.width/J.height;var Y=0;var h=-1;for(var V=0;V<Spg.length;V++){var K=Math.abs(m.width-Spg[V]);if(h===-1||Y>=K)h=V,Y=K}Y=jaZ[h];this.K&&g.pZ(this.K.element,"outline-width",Math.max(m.width,m.height)+"px");for(m=0;m<this.endscreen.elements.length;++m){V=this.endscreen.elements[m].id;h=this.G[V];K=this.L[V];if(!h||!K)continue;let T=K.width*S/K.aspectRatio;var E=Math.round(K.width*J.width);V=Math.round(T*J.height);let k=J.left+Math.round(K.left*J.width),y=J.top+
Math.round(K.top*J.height);g.HB(h.element,E,V);g.dd(h.element,k,y);g.OH(h.element,YpR);E>256||V>256?g.xd(h.element,"ytp-ce-large-round"):E>96||V>96?g.xd(h.element,"ytp-ce-medium-round"):g.xd(h.element,"ytp-ce-small-round");g.OH(h.element,hhu);E=K.left+K.width/2;K=K.top+T/2;g.xd(h.element,E<=.5&&K<=.5?"ytp-ce-top-left-quad":E>.5&&K<=.5?"ytp-ce-top-right-quad":E<=.5&&K>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.OH(h.element,jaZ);g.xd(h.element,Y);(h=g.lj(document,"div","ytp-ce-expanding-overlay-body",
h.element)[0])&&g.pZ(h,"height",`${V}px`)}}}}}onCueRangeEnter(J){if(this.endscreen)if(J.getId()==="ytp-ce-in-endscreen")w0(this,this.endscreen.impressionUrls),(J=g.dL())&&this.endscreen.visualElement&&g.Py(J,this.endscreen.visualElement),this.J&&(g.xd(this.J,"ytp-ce-element-show"),this.J.removeAttribute("aria-hidden"),this.player.DQ()?g.xd(this.J,"ytp-ce-hide-button-lower"):g.bw(this.J,"ytp-ce-hide-button-lower"));else{J=J.getId().substring(15);var m=this.G[J],S=this.L[J];g.xd(m.element,"ytp-ce-element-show");
m.element.removeAttribute("aria-hidden");m=this.player.getRootNode();g.xd(m,"ytp-ce-shown");w0(this,S.impressionUrls);(m=g.dL())&&g.Py(m,S.visualElement);this.player.U().eN&&g.c9(this.player,"endscreenelementshown",J)}}onCueRangeExit(J){if(J.getId()==="ytp-ce-in-endscreen")this.J&&(g.bw(this.J,"ytp-ce-element-show"),this.J.setAttribute("aria-hidden","true"));else{J=J.getId().substring(15);var m=this.G[J];g.bw(m.element,"ytp-ce-element-show");m.element.setAttribute("aria-hidden","true");m=this.player.getRootNode();
g.bw(m,"ytp-ce-shown");this.player.U().eN&&g.c9(this.player,"endscreenelementhidden",J)}}N(J){J.target===window&&(new g.P$(()=>{for(let m of Object.values(this.G))g.OH(m.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Rq(J){for(let m of Object.values(this.G))J?m.element.setAttribute("hidden",""):m.element.removeAttribute("hidden")}uj(J){this.J&&this.player.getRootNode().removeChild(this.J);
J&&(g.xd(J,"ytp-ce-hide-button-container"),this.J=J,g.H9(this.player,this.J,4))}},Spg=[346,426,470,506,570,640,853,1280,1920],jaZ="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hhu=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],YpR=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Vgv=class{constructor(J,m,S,Y){this.value=J;this.target=m;this.showLinkIcon=S;this.G=Y}J(){return this.value?this.value:null}},hm1={IA:"current",j3:"new"};var EnR=class{constructor(J,m,S){this.type=J;this.trigger=m;this.url=S}},$CZ={CLOSE:"close",nU:"openUrl",SUBSCRIBE:"subscribe"},Kye={Ag:"click",CLOSE:"close",OT:"hidden",y0G:"rollOut",T22:"rollOver",SEE:"shown"};var qQg=class{constructor(J,m,S,Y,h){this.id=J;this.type=m;this.style=S;this.data=h;this.action=Y||[]}H3(){var J=gnb(this,m=>m.type==="openUrl"&&m.url!=null);
return J?J.url:null}},LyZ={u7:"anchored",Wv:"branding",CHANNEL:"channel",BG:"cta",Wf:"highlightText",Qq:"label",PLAYLIST:"playlist",POPUP:"popup",qE5:"speech",SUBSCRIBE:"subscribe",Rn0:"title",VIDEO:"video",hxE:"website"},uBZ={Wv:"branding",Jg:"card",O5:"drawer",nf:"highlight",aV:"marker",Vd:"promotion",TEXT:"text",zxQ:"widget"};var $6k=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
K8R=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var E5X=class{constructor(J,m){this.context=J;this.J=m}};var UCt=class{constructor(J,m){this.merchant=J;this.price=m}};var TXs=class extends g.rX{constructor(J,m){super();this.element=J;this.context=m;this.kk=!1;this.oM=new Map;this.t0=new Map;this.context.V.addEventListener(g.zz("annotations_module"),S=>{(S=this.oM.get(S))&&S.apply(this)});
this.context.V.addEventListener(g.da("annotations_module"),S=>{(S=this.t0.get(S))&&S.apply(this)})}addCueRange(J,m,S,Y,h){J=new g.hq(J,m,{id:S,
namespace:"annotations_module"});Y&&this.oM.set(J,Y);h&&this.t0.set(J,h);this.context.V.zc([J],1)}mQ(){this.context.G.subscribe("resize",this.u5,this)}cS(){return this.element}d2(J,m,S,Y,h,V){if(this.kk)return!1;V&&(V.stopPropagation(),V.preventDefault());this.navigate(J,S,Y,h);return!1}show(){}hide(){}destroy(){g.EE(this.cS())}u5(){}navigate(J,m,S,Y){var h=J.J();if(h){var V=DCk(h,J.target),K=()=>{J.G&&this.context.V.pauseVideo();var E=this.context.videoData.y8||!1,T=g.YI(h||"");E&&T&&(T.v||T.list)?
this.context.V.YA(T.v,m,T.list,!1):g.FI(h||"",V==="current"?"_top":void 0,m)};
V==="new"&&(K(),K=null);Tl(this.context.logger,S,K,Y);ymv(h)||(S=g.dL(),Y=m.itct,S&&Y&&g.F_(S,g.uk(Y)))}}fz(){this.oM.clear();this.t0.clear();super.fz()}createElement(J){J=new g.C(J);g.O(this,J);return J.element}};var JNu=class extends TXs{constructor(J,m,S){super(m,S);this.V=J;this.eventId=null;this.yI=this.MB=this.Cg=this.K=this.isInitialized=!1;this.cards=[];this.Yk=this.B=this.aM=this.A=this.qB=this.J=null;this.eN=[];this.N=this.C=this.xi=this.A0=null;this.L=0;this.GT=new g.P$(()=>{},S.b5.Ha?4E3:3E3);
g.O(this,this.GT);this.QE=new g.P$(()=>{});
g.O(this,this.QE);this.TT=new E5X(S,(Y,h,V,K,E,T)=>{Cz(this,Y,h,V,K,E,T)});
this.W=new g.C({S:"div",Z:"iv-drawer",O:{id:"iv-drawer"},Y:[{S:"div",Z:"iv-drawer-header",O:{"aria-role":"heading"},Y:[{S:"span",Z:"iv-drawer-header-text"},{S:"button",w2:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{S:"div",Z:"iv-drawer-content"}]});g.O(this,this.W);this.D=this.W.element;this.FG=new g.w3(this.W,330);g.O(this,this.FG);this.eX=g.fV("iv-drawer-header-text",this.D);this.G=g.fV("iv-drawer-content",this.D);this.addCueRange(0,S.videoData.lengthSeconds*
1E3,"",()=>{this.Cg&&SD(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.Cg=this.K)&&Ys(this)});
this.h0=new g.PW(this);g.O(this,this.h0);this.V.addEventListener("videodatachange",this.uW.bind(this))}uW(){this.N&&jD(this,this.N)}isAvailable(){var J;if(J=!!this.cards.length)(J=this.V.getRootNode())?(J=g.Xo(J),J=173<J.width&&173<J.height):J=!1;return J}u5(){var J=this.isAvailable();g.CZ(this.cS(),J);g.Zh(this.context.V.getRootNode(),g.NE.IV_DRAWER_ENABLED,J);Fz(this.V)}destroy(){this.V.Rd(!1);try{this.V.getRootNode().removeChild(this.D)}catch(J){}g.ex(this.eN);this.h0.G();this.qB&&this.qB.dispose();
this.A&&this.A.dispose();super.destroy()}FU(){this.context.J.listen(g.fV("iv-drawer-close-button",this.D),"click",this.wX,this);this.context.J.listen(this.G,"touchend",()=>{this.GT.start()});
this.context.J.listen(this.G,"scroll",this.s9,this);this.context.G.subscribe("onHideControls",()=>{this.MB=!0});
this.context.G.subscribe("onShowControls",()=>{this.MB=!1});
this.context.G.subscribe("onVideoAreaChange",()=>{this.MB=g.sH(this.V.getRootNode(),"ytp-autohide")});
this.eN.push(g.Fj("iv-button-shown",this.HS,this));this.eN.push(g.Fj("iv-button-hidden",this.lS,this));Qd1(this)}findLastIndex(J){if(this.cards.length===0)return 0;var m=g.MS(this.cards,S=>J.la.startMs>S.la.startMs||J.la.startMs===S.la.startMs&&J.la.timestamp>=S.la.timestamp?!0:!1);
return m===-1?0:m+1}wX(){if(this.K){Tl(this.context.logger,$s(this).r_.close);var J=g.dL();J&&this.C&&g.F_(J,this.C);Ys(this)}}s9(){g.Zh(this.D,"iv-drawer-scrolled",this.G.scrollTop>0)}HS(){var J=g.dL(),m=$s(this);m=m?m.xi:this.xi;J&&m&&g.oE(J,[m])}lS(){var J=g.dL(),m=$s(this);m=m?m.xi:this.xi;J&&m&&g.Wy(J,[m])}jX(){var J=$s(this);Tl(this.context.logger,J.r_.Pn);var m=g.dL();if(m&&J)if(this.V.X("web_infocards_teaser_show_logging_fix")){let S=[];J.mk&&S.push(J.mk);J.xi&&S.push(J.xi);S.length>0&&g.oE(m,
S)}else g.oE(m,[J.mk,J.xi])}YI(){var J=g.dL(),m=$s(this);J&&m&&g.Wy(J,[m.mk])}vS(J){var m=$s(this),S=g.dL();this.J?J?(J=this.context.logger,Tl(J,m.r_.CT),J.V.sendVideoStatsEngageEvent(4,void 0),S&&m.mk&&g.F_(S,m.mk)):(J=this.context.logger,Tl(J,m.r_.CT),J.V.sendVideoStatsEngageEvent(4,void 0),S&&m.xi&&g.F_(S,m.xi)):(J=this.context.logger,Tl(J,m.r_.CT),J.V.sendVideoStatsEngageEvent(4,void 0),S&&this.xi&&g.F_(S,this.xi))}};var g5k=class extends TXs{constructor(J,m,S){super(J,m);this.annotation=S;this.isActive=!1}mQ(){super.mQ();xCu(this)}show(){super.show();var J=g.dL(),m=this.annotation.data;J&&m&&(m=m.session_data)&&g.oE(J,[g.uk(m.itct)])}hide(){super.hide();var J=g.dL(),m=this.annotation.data;J&&m&&(m=m.session_data)&&g.Wy(J,[g.uk(m.itct)])}};var zme=class extends g5k{constructor(J,m,S){super(J,m,S);this.J=null;this.G=!1}show(){if(!this.isActive){super.show();if(!this.G){g.xd(this.cS(),"iv-branding");let J=this.annotation.data;this.J=this.createElement({S:"img",w2:["branding-img","iv-click-target"],O:{"aria-label":"Channel watermark",src:J.image_url,width:J.image_width,height:J.image_height}});g.CZ(this.J,!1);let m=this.createElement({S:"button",w2:["branding-img-container","ytp-button"]});m.appendChild(this.J);this.cS().appendChild(m);
let S=this.annotation.H3();S&&Cz(this,m,S,this.annotation.id,J.session_data);this.G=!0}g.CZ(this.cS(),!0);this.isActive=!0;if(this.J){try{cmu(this,this.J)}catch{}g.xd(this.context.V.getRootNode(),"ytp-branding-shown");this.context.V.getRootNode().style.setProperty("--branding-image-width",`${this.J.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.CZ(this.cS(),!1),this.isActive=!1,g.bw(this.context.V.getRootNode(),"ytp-branding-shown"))}destroy(){g.bw(this.context.V.getRootNode(),
"ytp-branding-shown");super.destroy()}};var C2Z=class{constructor(J,m,S,Y,h,V,K){this.J=J;this.K=m;this.b5=S;this.videoData=Y;this.logger=h;this.V=V;this.G=K}};var dCI=class extends g5k{constructor(J,m,S){super(J,m,S);this.B=this.isCollapsed=this.W=!1;this.L=5E3;this.G=this.K=this.J=this.D=null;this.C=this.createElement({S:"div",w2:["iv-promo-contents"]});this.A=new g.P$(()=>{this.J.setAttribute("aria-hidden","true");g.CZ(this.K,!1);g.CZ(this.G,!0)},700,this);
g.O(this,this.A)}show(){this.isActive||(super.show(),this.W||(ZHu(this),this.W=!0),g.CZ(this.cS(),!0),g.cg(function(){g.bw(this.cS(),"iv-promo-inactive")},100,this),this.cS().removeAttribute("aria-hidden"),this.isActive=!0,E$(this),bHZ(this),OHR(this,this.L))}hide(){this.isActive&&(g.xd(this.cS(),"iv-promo-inactive"),this.isActive=!1,this.cS().setAttribute("aria-hidden","true"))}d2(J,m,S,Y,h,V){return this.isCollapsed?!1:super.d2(J,m,S,Y,h,V)}GT(J){this.B=!0;
K9(this,500,J)}TT(){this.B=!1;IBv(this)}eN(J){J.stopPropagation();this.hide()}N(J){J.stopPropagation();E$(this);this.isCollapsed=!0;g.xd(this.cS(),"iv-promo-collapsed-no-delay");this.A.start()}destroy(){this.A.dispose();super.destroy()}};var kBk=class{constructor(J){this.V=J}};g.gs("annotations_module",class extends g.qa{constructor(J){super(J);this.eN=this.N=!1;this.loadNumber=0;this.L={};this.logger=new kBk(this.player);this.A=new g.PW(this);this.C=this.D=null;this.events=new g.PW(this);this.T8=this.B=this.J=null;this.mQ=[];g.O(this,this.A);this.A.j(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.A.j(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.A.j(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.A.j(this.player,"resize",S=>{this.publish("resize",S)});
this.A.j(this.player,"presentingplayerstatechange",S=>{this.publish("presentingplayerstatechange",S)});
this.subscribe("presentingplayerstatechange",this.GT,this);this.subscribe("resize",this.W,this);this.player.U().MB.subscribe("vast_info_card_add",this.TT,this);g.O(this,this.events);this.u5=this.createElement({S:"div",Z:"video-custom-annotations"});this.G=new g.C({S:"div",w2:["ytp-player-content","ytp-iv-player-content"]});g.O(this,this.G);g.H9(this.player,this.G.element,4);this.G.hide();this.K=new g.C({S:"div",w2:["ytp-iv-video-content"]});g.O(this,this.K);J=this.createElement({S:"div",Z:"video-annotations"});
J.appendChild(this.u5);this.K.element.appendChild(J);this.Bm()?this.load():this.player.X("web_fix_annotations")&&(this.D=()=>{this.loaded||this.EE()||!this.Bm()||(Ggs(this),this.load())},this.player.addEventListener("videodatachange",this.D));
var m=this.createElement({S:"style"});(g.Uh("HEAD")[0]||document.body).appendChild(m);this.addOnDisposeCallback(()=>{g.EE(m)});
if(J=m.sheet){for(let S of $6k)J.insertRule(S,0);for(let S of K8R)J.insertRule(S,0)}}f4(J,m){if(!pMu(this.player.U().playerStyle))return null;switch(J){case "loadCustomAnnotationsXml":return(J=g.XN(m))&&ks(this,J),!0;case "removeCustomAnnotationById":return m&&this.J&&(J7(this.J,m),Fz(this.player)),!0}return null}getOptions(){return pMu(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Bm(){var J=this.player.getVideoData(),m=J.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return J.y8||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.X("web_fix_annotations")?iHZ(this)?m?.isWatermarkEnforced===!0?!0:m?.isAnnotationsEnabled??!1:!1:iHZ(this)}W(){if(this.K){var J=this.player.nz().getVideoContentRect(!0);g.HB(this.K.element,J.width,J.height);g.dd(this.K.element,J.left,J.top)}if(this.J){var m=this.player.vL();J=this.J;m=m.width;g.Zh(J.D,"iv-drawer-small",m<=426);g.Zh(J.D,"iv-drawer-big",m>=1280)}}GT(J){lBe(this,J.state);J.state.J(2)&&(this.DQ()&&this.y3()&&this.player.getPresentingPlayerType()!==
2&&this.Ph(!1),this.Rd(!1))}load(){super.load();lBe(this,this.player.getPlayerStateObject());this.loadNumber++;var J=this.player.getVideoData();aB1(this,J);g.H9(this.player,this.K.element,4);this.W();var m=g.yG(J),S=J.rw();if(this.player.X("web_fix_annotations")){if(m&&(m.featuredChannel&&m6R(this,m.featuredChannel,m.annotationId||"branding",J.videoId||null,J.eventId||null),m=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,m?.isWatermarkEnforced&&!m?.isAnnotationsEnabled))return;
S&&yW(this,S)}else S&&yW(this,S),m&&m.featuredChannel&&m6R(this,m.featuredChannel,m.annotationId||"branding",J.videoId||null,J.eventId||null);this.T8=g.fV("ytp-cards-button",this.player.getRootNode());J.Ed()&&HHu(this,J)}onVideoDataChange(){}unload(){this.player.h8("annotations_module");for(let J of Object.keys(this.L))this.L[J].destroy();this.B=null;this.J&&(this.J.destroy(),this.J=null,Fz(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.eN=!1;this.L={};this.G.hide();super.unload();
this.K.detach();Ggs(this)}TT(J){J===this.player.getVideoData().videoId&&(this.loaded?Mgs(this):this.load())}DQ(){return this.J?.isAvailable()||this.eN}y3(){return!!this.J&&this.J.K}Ph(J,m=!1,S){this.DQ();this.J&&(J?S?SD(this.J,S,m):SD(this.J,"YOUTUBE_DRAWER_AUTO_OPEN",m):Ys(this.J))}Rd(J,m){this.player.publish(J?"cardsteasershow":"cardsteaserhide",m)}fz(){this.player.U().MB.unsubscribe("vast_info_card_add",this.TT,this);g.bw(this.player.getRootNode(),g.NE.IV_DRAWER_OPEN);var J=this.mQ,m=g.kd;for(let S=
0,Y=J.length;S<Y;S++)m.gi(J[S]);this.mQ.length=0;super.fz()}createElement(J){J=new g.C(J);g.O(this,J);return J.element}});g.gs("creatorendscreen",V5k);})(_yt_player);
