(function(g){var window=this;'use strict';var D6u=async function(J,m,S){J.G=g.Wo(m,S)},DI=function(J){J.isActive()||J.start()},Rhs=function(J,m){var S=new g.HH;
S.languageCode=J.languageCode;S.languageName=J.languageName;S.name=J.name;S.displayName=J.displayName;S.kind=J.kind;S.isDefault=!1;S.J=J.J;S.isTranslateable=J.isTranslateable;S.vssId=J.vssId;S.url=J.url;S.translationLanguage=m;J.xtags&&(S.xtags=J.xtags);J.captionId&&(S.captionId=J.captionId);return S},RK=function(J,m){return m?J.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},rNu=function(J){return g.PH(J)||J.X("web_enable_caption_language_preference_stickiness")},NXk=async function(J,m){J=
J+"|"+m;
m=await g.p5();if(!m)throw g.Ec("gct");return(await g.Ni(m)).get("captions",J)},BXt=function(J,m,S){NXk(J,m).then(Y=>{Y&&S(Y.trackData,new g.HH(Y.metadata))})},rJ=function(J){if(!Qau.test(J))throw Error("'"+J+"' is not a valid hex color");
J.length==4&&(J=J.replace(PYX,"#$1$1$2$2$3$3"));J=J.toLowerCase();J=parseInt(J.slice(1),16);return[J>>16,J>>8&255,J&255]},o5R=function(){var J={},m="suggest_correction"in g.cN?g.cN.suggest_correction:"Edit caption";
m=m||"";for(let S in J){let Y=()=>String(J[S]);
m=m.replace(new RegExp("\\$\\{"+S+"\\}","gi"),Y);m=m.replace(new RegExp("\\$"+S,"gi"),Y)}return m},NB=function(){return g.OC("yt-player-caption-display-settings")},W8e=function(J,m){var S=g.Qg(J.segments,m);
S>=0||S<0&&(-S-1)%2===1||(S=-S-1,S>0&&m-J.segments[S-1]===1&&S<J.segments.length&&J.segments[S]-m===1?(g.SX(J.segments,S),g.SX(J.segments,S-1)):S>0&&m-J.segments[S-1]===1?J.segments[S-1]=m:S<J.segments.length&&J.segments[S]-m===1?J.segments[S]=m:(g.RI(J.segments,S,0,m),g.RI(J.segments,S+1,0,m)))},F8X=function(J){return J.J&&J.J.A?J.J.A+J.player.tp()<J.player.getCurrentTime():!1},ehv=function(J,m){if(J.policy.E3&&J.player.Gt()){var S=g.la(m,J.policy,{});
S.set("pot",J.player.Gt());S=S.H3()}else S=g.la(m,J.policy,{}).H3();var Y={format:"RAW",withCredentials:!0};if(J.policy.u5){Y.method="POST";let K=m.D;K&&Object.keys(K).length>0?Y.postBody=g.Wr(K,g.q4):Y.postBody=(0,g.wP)([120,0])}J.A&&(Y.responseType="arraybuffer");var h=++J.mQ,V=(0,g.l)();J.G=g.si(S,Y,3,100,-1,K=>{K.errorCode==="net.timeout"&&J.player.yE("capnt",{rn:h++})}).then(K=>{if(J.policy.Ug&&h%100===1){var E=(0,g.l)();
J.player.yE("caprsp",{rn:h,ms:E-V,kb:(K.xhr.responseText.length/1024).toFixed()})}a:{K=K.xhr;J.EE();if(J.K){var T=!(J.A?K.response:K.responseText)||K.status>=400;if(E=g.kzn(K)){K=g.la(J.K,J.policy,{});J.K.A_(K,E);ehv(J,J.K);break a}T?J.player.yE("capfail",{status:K.status}):(g.qn("fcb_r",(0,g.l)(),J.player.getVideoData()?.W||""),E=J.K.WB[0],T=E.Cz,J.B!=null&&J.L!==T&&(J.A?J.B(K.response,(E.segmentStartTime+J.player.tp())*1E3):J.B(K.responseText,(E.segmentStartTime+J.player.tp())*1E3),J.L=T))}J.K=
null;J.G=null}}).yb(K=>{J.K=null;
J.G=null;J.player.yE("capfail",{rn:h,status:K.xhr?.status})});
J.K=m;W8e(J.D,J.K.WB[0].Cz)},n5g=function(J,m){return m!=null&&m in J.G.J?J.G.J[m]:null},saZ=function(J,m,S){var Y=[];
for(let h in J.G.J){if(!J.G.J.hasOwnProperty(h))continue;let V=J.G.J[h];if(g.DC(V,S||null)){let K=V.info.captionTrack;K&&K.languageCode===m&&Y.push(V)}}return Y.length?Y[0]:null},x6R=function(J,m){var S=[];
for(let h in J.G.J){if(!J.G.J.hasOwnProperty(h))continue;var Y=J.G.J[h];if(g.DC(Y,m||null)){let V=Y.info.id,K=V,E=`.${V}`,T="",k="";if(Y=Y.info.captionTrack)V=Y.languageCode,K=Y.displayName,E=Y.vssId,T=Y.kind,k=Y.id;S.push(new g.HH({id:h,languageCode:V,languageName:K,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:T,captionId:k}))}}return S},cNu=function(J,m,S,Y){var h=m/360*16;
m>=J&&(J=640,Y>S*1.3&&(J=480),h=S/J*16);return h},bee=function(J){var m=1+.25*(J.fontSizeIncrement||0);
if(J.offset===0||J.offset===2)m*=.8;return m},Oev=function(J,m){var S="vertical-rl";
J.J.Va===1&&(S="vertical-lr");g.A1&&(S=S==="vertical-lr"?"tb-lr":"tb-rl");g.pZ(m,"-o-writing-mode",S);g.pZ(m,"-webkit-writing-mode",S);g.pZ(m,"writing-mode",S);g.pZ(m,"text-orientation","upright");g.xd(m,"ytp-vertical-caption");J.G.params.Q4===3&&(g.pZ(m,"text-orientation",""),g.pZ(m,"transform","rotate(180deg)"))},ZeR=function(J,m){var S={},Y=m.background?m.background:J.J.Y7.background;
if(m.backgroundOpacity!=null||m.background){var h=m.backgroundOpacity!=null?m.backgroundOpacity:J.J.Y7.backgroundOpacity;Y=rJ(Y);S.background="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+h+")";J.qB&&(S["box-decoration-break"]="clone",S["border-radius"]=`${J.oM*.375}px`)}if(m.fontSizeIncrement!=null||m.offset!=null)S["font-size"]=`${J.t0*bee(m)}px`;Y=1;h=m.color||J.J.Y7.color;if(m.color||m.textOpacity!=null)h=rJ(h),Y=m.textOpacity==null?J.J.Y7.textOpacity:m.textOpacity,h="rgba("+h[0]+","+h[1]+","+h[2]+","+Y+
")",S.color=h,S.fill=h;var V=m.charEdgeStyle;V===0&&(V=void 0);if(V){h=`rgba(34, 34, 34, ${Y})`;let T=`rgba(204, 204, 204, ${Y})`;m.Dw&&(T=h=m.Dw);let k=J.t0/16/2,y=Math.max(k,1);var K=Math.max(2*k,1),E=Math.max(3*k,1);let D=Math.max(5*k,1);Y=[];switch(V){case 4:for(;E<=D;E+=k)Y.push(`${K}px ${K}px ${E}px ${h}`);break;case 1:K=window.devicePixelRatio>=2?.5:1;for(V=y;V<=E;V+=K)Y.push(`${V}px ${V}px ${h}`);break;case 2:Y.push(`${y}px ${y}px ${T}`);Y.push(`-${y}px -${y}px ${h}`);break;case 3:for(E=0;E<
5;E++)Y.push(`0 0 ${K}px ${h}`)}S["text-shadow"]=Y.join(", ")}h="";switch(m.fontFamily){case 1:h='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:h='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:h='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:h='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:h='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:h=g.fd()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:h='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}h&&(S["font-family"]=h);h=m.offset;h==null&&(h=J.J.Y7.offset);switch(h){case 0:S["vertical-align"]="sub";break;case 2:S["vertical-align"]="super"}m.fontFamily===7&&(S["font-variant"]="small-caps");m.bold&&(S["font-weight"]="bold");m.italic&&(S["font-style"]="italic");m.underline&&
(S["text-decoration"]="underline");m.sL&&(S.visibility="hidden");m.HD===1&&J.D&&(S["text-combine-upright"]="all",S["text-orientation"]="mixed",h=g.sU||g.V1,J.G.params.Q4===3?S.transform=h?"rotate(90deg)":"rotate(180deg)":h&&(S.transform="rotate(-90deg)"));if(m.textEmphasis===1||m.textEmphasis===2||m.textEmphasis===3||m.textEmphasis===4||m.textEmphasis===5)if(g.sU)S["font-weight"]="bold";else switch(S["text-emphasis-style"]="filled circle",S["text-emphasis-color"]="currentcolor",S["webkit-text-emphasis"]=
"filled circle",m.textEmphasis){case 4:case 3:S["text-emphasis-position"]="under left";S["webkit-text-emphasis-position"]="under left";break;case 5:case 2:S["text-emphasis-position"]="over right",S["webkit-text-emphasis-position"]="over right"}return S},Imv=function(J,m){if(J.FG&&m.length===0)return 0;
J=1;for(let S=0;S<m.length;S++){let Y=m[S];typeof Y.text==="string"&&(J+=Y.text.split("\n").length-1,Y.append||S===0||J++)}return J},B6=function(J){J=J.split("px");
return J.length>0?(J=Number(J[0]))?J:0:0},ANI=function(J,m,S){J.A0=J.A0||!!S;
var Y={};Object.assign(Y,J.J.Y7);Object.assign(Y,S||m.J);Object.assign(Y,J.ur.Y7);(S=!J.A)&&pKe(J);var h=J.aM&&J.MB&&g.lu(Y,J.MB)?J.aM:GBu(J,Y),V=typeof m.text==="string",K=V?m.text.split("\n"):[m.text];for(let T=0;T<K.length;T++){var E=T>0||!m.append;let k=K[T];E&&!S?(pKe(J),h=GBu(J,Y)):E&&S&&(S=!1);k&&(h.appendChild(V?g.h2(k):k),V||k.tagName!=="RUBY"||k.childElementCount!==4||g.sU||!g.ug(k.children[2],"text-emphasis")||(E=J.D?"padding-right":"padding-top",g.ug(k.children[2],"text-emphasis-position")&&
(E=J.D?"padding-left":"padding-bottom"),g.MX?g.pZ(h,E,"1em"):g.pZ(h,E,"0.5em")))}J.MB=Y;J.aM=h;J.C.push(m)},pKe=function(J){if(J.A){var m=J.A;
if(J.qB){var S=J.J.textAlign;S===0?(m=m.firstElementChild)&&g.pZ(m,{"border-bottom-left-radius":"0"}):S===1&&(m=m.lastElementChild)&&g.pZ(m,{"border-bottom-right-radius":"0"})}}J.A=g.Yc("SPAN");g.pZ(J.A,{display:"block"});g.xd(J.A,"caption-visual-line");J.K.appendChild(J.A)},GBu=function(J,m){var S=g.Yc("SPAN");
g.pZ(S,{display:"inline-block","white-space":"pre-wrap"});g.pZ(S,ZeR(J,m));S.classList.add("ytp-caption-segment");J.A.appendChild(S);J.qB&&J.K.children.length>1&&(J=J.J.textAlign,J===0?S.previousElementSibling||g.pZ(S,{"border-top-left-radius":"0"}):J===1&&g.pZ(S,{"border-top-right-radius":"0"}));S.previousElementSibling&&(g.pZ(S.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.pZ(S,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return S},
uKZ=function(J,m,S){if(J===255&&m===255||!J&&!m)return{s4:J,
Li:m,result:0};J=v5v[J];m=v5v[m];if(J&128){var Y;if(Y=!(m&128))Y=m,Y=S.df()&&S.Li===Y;if(Y)return{s4:J,Li:m,result:1}}else if(m&128&&1<=J&&J<=31)return{s4:J,Li:m,result:2};return{s4:J,Li:m,result:3}},qpI=function(J,m,S,Y){m===255&&S===255||!m&&!S?(++J.K===45&&J.reset(),J.D.G.clear(),J.A.G.clear()):(J.K=0,L8R(J.D,m,S,Y))},zhZ=function(J,m){J.J.sort((S,Y)=>{var h=S.time-Y.time;
return h===0?S.order-Y.order:h});
for(let S of J.J)J.time=S.time,S.type===0?qpI(J,S.GB,S.cO,m):S.type===1&&J.G&496&&L8R(J.A,S.GB,S.cO,m);J.J.length=0},lmX=function(J,m){switch(J){case 0:return d6e[(m&127)-32];
case 1:return wKg[m&15];case 2:return U6I[m&31];case 3:return iev[m&31]}return 0},QW=function(J,m){if(J.style.type===3){var S=0,Y=0,h=J.A.time+0,V="",K="",E=h;
for(var T=1;T<=15;++T){var k=!1;for(var y=Y?Y:1;y<=32;++y){var D=J.K[T][y];if(D.J!==0){S===0&&(S=T,Y=y);k=String.fromCharCode(D.J);var R=D.timestamp;R<h&&(h=R);D.timestamp=E;K&&(V+=K,K="");V+=k;k=!0}if((D.J===0||y===32)&&k){K="\n";break}else if(Y&&!k)break}if(S&&!k)break}V&&m.D(S,Y,h,E,V)}else for(Y=S=0,V=h=J.A.time+0,K=1;K<=15;++K)for(E="",T=1;T<=32;++T)if(y=J.K[K][T],D=y.J,D!==0&&(S===0&&(S=K,Y=T),k=String.fromCharCode(D),R=y.timestamp,R<=h&&(h=R),E+=k,y.reset()),T===32||D===0)E&&m.D(S,Y,h,V,E),
h=V,E="",Y=S=0},P6=function(J){return J.K[J.row][J.G]},oK=function(J,m,S){m>=2&&J.G>1&&(--J.G,P6(J).J=0);
var Y=P6(J);Y.timestamp=J.A.time+0;Y.J=lmX(m,S);J.G<32&&J.G++},fmu=function(J,m,S,Y){for(let K=0;K<Y;K++)for(let E=0;E<=32;E++){var h=J.K[m+K][E],V=J.K[S+K][E];
h.J=V.J;h.timestamp=V.timestamp}},W6=function(J,m,S){for(let Y=0;Y<S;Y++)for(let h=0;h<=32;h++)J.K[m+Y][h].reset()},FA=function(J){J.row=J.J>0?J.J:1;
J.G=1;W6(J,0,15)},t5v=function(J){J.style.set(1);
J.J=J.D;J.J.J=0;J.J.style=J.style;J.K.mode=1<<J.J.D},eD=function(J,m,S){var Y=J.G,h=!1;
switch(J.style.get()){case 4:case 1:case 2:J.style.get()===4&&Y.J>0||(QW(Y,S),FA(J.G),FA(J.D),Y.row=15,Y.J=m,h=!0)}J.style.set(3);J.J=Y;J.J.style=J.style;J.K.mode=1<<Y.D;h?Y.G=1:Y.J!==m&&(Y.J>m?(QW(Y,S),W6(Y,Y.row-Y.J,m)):Y.row<m&&(m=Y.J),Y.J=m)},HeX=function(J){J.style.set(4);
J.J=J.text;J.J.style=J.style;J.K.mode=1<<J.J.D},L8R=function(J,m,S,Y){J.G.update();
m=uKZ(m,S,J.G);switch(m.result){case 0:return;case 1:case 2:return}var h=m.s4;m=m.Li;if(32<=h||!h)J.J.mode&J.J.G&&(S=h,S&128&&(S=127),m&128&&(m=127),J=J.D.J,S&96&&oK(J,0,S),m&96&&oK(J,0,m),S!==0&&m!==0&&J.style.type===3&&QW(J,Y));else if(h&16)a:if(!J.G.matches(h,m)&&(S=J.G,S.s4=h,S.Li=m,S.state=2,S=h&8?J.L:J.K,J.D=S,J.J.mode=1<<(J.A<<2)+(S.A<<1)+(S.style.type===4?1:0),(J.J.mode|1<<(J.A<<2)+(S.A<<1)+(S.style.type!==4?1:0))&J.J.G))if(m&64){Y=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(h&7)<<1|m>>5&1];
J=m&16?((m&14)>>1)*4:0;m=S.J;switch(S.style.get()){case 4:Y=m.row;break;case 3:if(Y!==m.row){if(Y<m.J&&(Y=m.J,Y===m.row))break;var V=1+m.row-m.J;let K=1+Y-m.J;fmu(m,K,V,m.J);S=V;h=m.J;K<V?(V=K+h-V,V>0&&(S+=V,h-=V)):(V=V+h-K,V>0&&(h-=V));W6(m,S,h)}}m.row=Y;m.G=J+1}else switch(h&7){case 1:switch(m&112){case 32:oK(S.J,0,32);break a;case 48:m===57?(Y=S.J,P6(Y).J=0,Y.G<32&&Y.G++):oK(S.J,1,m&15)}break;case 2:m&32&&oK(S.J,2,m&31);break;case 3:m&32&&oK(S.J,3,m&31);break;case 4:case 5:if(32<=m&&m<=47)switch(m){case 32:t5v(S);
break;case 33:Y=S.J;Y.G>1&&(--Y.G,P6(Y).J=0);break;case 36:Y=S.J;J=P6(Y);for(m=0;m<=15;m++)for(S=0;S<=32;S++)if(Y.K[m][S]===J){for(;S<=32;S++)Y.K[m][S].reset();break}break;case 37:eD(S,2,Y);break;case 38:eD(S,3,Y);break;case 39:eD(S,4,Y);break;case 40:oK(S.J,0,32);break;case 41:Y=S;Y.style.set(2);Y.J=Y.G;Y.J.J=0;Y.J.style=Y.style;Y.K.mode=1<<Y.J.D;break;case 42:Y=S;J=Y.text;J.J=15;J.style.set(4);FA(J);HeX(Y);break;case 43:HeX(S);break;case 44:J=S;m=J.G;switch(J.style.get()){case 1:case 2:case 3:QW(m,
Y)}W6(m,0,15);break;case 45:b:{m=S;J=m.J;switch(m.style.get()){default:case 2:case 1:break b;case 4:if(J.row<15){++J.row;J.G=1;break b}break;case 3:}J.J<2&&(J.J=2,J.row<J.J&&(J.row=J.J));m=J.row-J.J+1;QW(J,Y);fmu(J,m,m+1,J.J-1);W6(J,J.row,1)}break;case 46:W6(S.D,0,15);break;case 47:J=S,QW(J.G,Y),J.D.updateTime(J.K.time+0),Y=J.D,J.D=J.G,J.G=Y,t5v(J)}break;case 7:switch(m){case 33:case 34:case 35:Y=S.J,(Y.G+=m&3)>32&&(Y.G=32)}}},XKR=function(J,m,S,Y,h,V,K){var E=V[0],T=K[E.getAttribute("p")];
if(T.ef===1){var k=V[1],y=V[2];V=V[3];E.getAttribute("t");k.getAttribute("t");y.getAttribute("t");V.getAttribute("t");E.getAttribute("p");k.getAttribute("p");V.getAttribute("p");K=K[y.getAttribute("p")];E=ame(E.textContent,k.textContent,y.textContent,V.textContent,K);return new n9(J,m,h,S,E,Y,T)}switch(T.ef){case 9:case 10:T.textEmphasis=1;break;case 11:T.textEmphasis=2;break;case 12:T.textEmphasis=3;break;case 13:T.textEmphasis=4;break;case 14:T.textEmphasis=5}return new n9(J,m,h,S,E.textContent||
"",Y,T)},ame=function(J,m,S,Y,h){var V=g.fd(),K=V?g.Yc("DIV"):g.Yc("RUBY"),E=g.Yc("SPAN");
E.textContent=J;K.appendChild(E);J=V?g.Yc("DIV"):g.Yc("RP");J.textContent=m;K.appendChild(J);m=V?g.Yc("DIV"):g.Yc("RT");m.textContent=S;K.appendChild(m);S=h.ef;if(S===10||S===11||S===12||S===13||S===14)if(g.pZ(m,"text-emphasis-style","filled circle"),g.pZ(m,"text-emphasis-color","currentcolor"),g.pZ(m,"webkit-text-emphasis","filled circle"),h.ef===11||h.ef===13)g.pZ(m,"webkit-text-emphasis-position","under left"),g.pZ(m,"text-emphasis-position","under left");S=!0;if(h.ef===4||h.ef===7||h.ef===12||
h.ef===14)g.pZ(K,"ruby-position","over"),g.pZ(K,"-webkit-ruby-position","before");else if(h.ef===5||h.ef===6||h.ef===11||h.ef===13)g.pZ(K,"ruby-position","under"),g.pZ(K,"-webkit-ruby-position","after"),S=!1;h=V?g.Yc("DIV"):g.Yc("RP");h.textContent=Y;K.appendChild(h);V&&(Y=S,g.pZ(K,{display:"inline-block",position:"relative"}),V=K.firstElementChild.nextElementSibling,g.pZ(V,"display","none"),V=V.nextElementSibling,g.pZ(V,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.pZ(K.lastElementChild,"display","none"),Y?(g.pZ(K,"padding-top","0.6em"),g.pZ(V,"top","0")):(g.pZ(K,"padding-bottom","0.6em"),g.pZ(V,"bottom","0")));return K},CYZ=function(J){var m="_"+s$++;
return new xs(0,0x8000000000000,0,m,J)},c6=function(J,m){J=J.getAttribute(m);
if(J!=null)return Number(J)},bz=function(J,m){J=J.getAttribute(m);
if(J!=null)return J==="1"},O$=function(J,m){J=c6(J,m);
return J!==void 0?J:null},IK=function(J,m){J=J.getAttribute(m);
if(J!=null)return ZI.test(J),J},M5v=function(J,m){var S={},Y=m.getAttribute("ws");
Object.assign(S,Y?J.W[Y]:J.D);J=O$(m,"mh");J!=null&&(S.nM=J);J=O$(m,"ju");J!=null&&(S.textAlign=J);J=O$(m,"pd");J!=null&&(S.Q4=J);J=O$(m,"sd");J!=null&&(S.Va=J);J=IK(m,"wfc");J!=null&&(S.windowColor=J);m=c6(m,"wfo");m!==void 0&&(S.windowOpacity=m/255);return S},JGu=function(J,m){var S={},Y=m.getAttribute("wp");
Y&&Object.assign(S,J.B[Y]);J=O$(m,"ap");J!=null&&(S.yg=J);J=c6(m,"cc");J!=null&&(S.lJ=J);J=c6(m,"ah");J!=null&&(S.iV=J);J=c6(m,"rc");J!=null&&(S.Bs=J);m=c6(m,"av");m!=null&&(S.US=m);return S},mFe=function(J,m,S,Y){var h={};
Object.assign(h,JGu(J,m));Object.assign(h,M5v(J,m));Y?g.lu(h,J.D)?(Y=J.A,h=J.D):Y="_"+s$++:Y=m.getAttribute("id")||"_"+s$++;J=c6(m,"t")+S;m=c6(m,"d")||0x8000000000000;if(h.Q4===2||h.Q4===3)S=h.Bs,h.Bs=h.lJ,h.lJ=S;return new xs(J,m,0,Y,h)},p9=function(J){J=g.sh(Math.round(J),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-J.length)+J},SPs=function(J,m,S,Y,h){Y===0&&(Y=0x8000000000000);
var V={};m.wpWinPosId&&Object.assign(V,J.D.get(m.wpWinPosId));m.wsWinStyleId&&Object.assign(V,J.A.get(m.wsWinStyleId));J=m.rcRowCount;J!==void 0&&(V.Bs=J);m=m.ccColCount;m!==void 0&&(V.lJ=m);if(V.Q4===2||V.Q4===3)m=V.Bs,V.Bs=V.lJ,V.lJ=m;return new xs(S,Y,0,h,V)},Gl=function(J){var m=J.byteOffset;
J.byteOffset+=1;return J.J.getUint8(m)},A7=function(J){var m=J.byteOffset;
J.byteOffset+=4;return J.J.getUint32(m)},haR=function(J){if(typeof J==="string")return!1;
J=new jeu(J,0);return YPs(J)},YPs=function(J){if(!(J.byteOffset<J.J.byteLength)||A7(J)!==1380139777)return!1;
J.version=Gl(J);if(J.version>1)return!1;Gl(J);Gl(J);Gl(J);return!0},VlX=function(J,m){if(!m)return"";
J.D&&J.G.params.Va!==1&&(m*=-1);return`translate${J.D?"X":"Y"}(${m}px)`},$FR=function(J){J.GT=Array.from(J.element.getElementsByClassName("caption-visual-line"));
for(var m=J.G.params.Bs,S=0,Y=0,h=J.GT.length-1;S<m&&h>-1;){var V=J.GT[h];Y+=J.D?V.offsetWidth:V.offsetHeight;S++;h--}J.N=Y;m=Math;S=m.max;isNaN(J.u5)&&((Y=J.J.lJ)?(h=g.Yc("SPAN"),g.gd(h,"\u2013".repeat(Y)),g.pZ(h,ZeR(J,J.J.Y7)),J.K.appendChild(h),J.u5=h.offsetWidth,J.K.removeChild(h)):J.u5=0);Y=J.K;J.mQ=S.call(m,J.u5,J.s9,(J.D?Y.offsetHeight:Y.offsetWidth)+1)},KbR=function(J,m){$FR(J);
var S=J.GT.reduce((Y,h)=>(J.D?h.offsetWidth:h.offsetHeight)+Y,0);
S=J.N-S;if(S!==J.h0){let Y=S>0&&J.h0===0,h=S<J.h0;m||isNaN(S)||Y||!h||(g.xd(J.element,"ytp-rollup-mode"),J.j(J.element,"transitionend",J.QE));g.pZ(J.K,"transform",VlX(J,S));J.h0=S}$FR(J)},TlZ=function(J,m,S,Y){var {formatId:h,
Cz:V,startTimeMs:K,durationMs:E}=J.aF(m),T={formatId:h,startTimeMs:K,durationMs:E,aY:V,Iy:V},k=EzZ(J.pg,T.startTimeMs),y=k>=0?J.pg[k]:null,D=y?y.startTimeMs+y.durationMs:0,R=T.startTimeMs+T.durationMs;!y||T.startTimeMs-D>J.D?J.pg.splice(k+1,0,T):(y.durationMs=Math.max(D,R)-y.startTimeMs,y.Iy=Math.max(y.Iy,T.Iy));Y(J.pg);Y=g.Ms(m);J=J.A;Y=Y.buffer.slice(Y.byteOffset,Y.byteLength+Y.byteOffset);m=m.info.D;J.mQ?J.B==null?g.f$(J.logger,350058965,"Null loaded track meta data at captions data received"):
S.tZ(Y,J.B,m*1E3):g.f$(J.logger,350058965,"Null Representation at captions data received")},yGI=function(J,m){J.G=(S,Y)=>{if(J.V.U().experiments.RM("html5_sabr_live_support_subfragmented_captions"))(J.J?J.J=J.J.A(S):(J.J=S,gzs(J.J)),J.J)?S.info.A8&&(kmg(J.J),TlZ(J,J.J,m,Y),J.J=null):g.f$(J.logger,350058965,"Empty slice");
else if(S.info.A8){var h=S;if(J.lx.length>0){for(h=J.lx.shift();J.lx.length>0;)h=h?.A(J.lx.shift());h=h?.A(S)}h?(gzs(h),kmg(h),TlZ(J,h,m,Y)):g.f$(J.logger,350058965,"Empty slice")}else J.lx.push(S)};
J.V.addEventListener("sabrCaptionsDataLoaded",J.G)},EzZ=function(J,m){J=g.Qg(J,{startTimeMs:m},(S,Y)=>S.startTimeMs-Y.startTimeMs);
return J>=0?J:-J-2},gzs=function(J){try{var m=g.Sj(J)*1E3}catch(S){m=J.info.segmentStartTime*1E3}m<0&&(m=J.info.segmentStartTime*1E3);
J.info.segmentStartTime=m/1E3;J.info.D=m/1E3},kmg=function(J){try{var m=g.YAP(J)*1E3}catch(S){m=J.info.K*1E3}m<0&&(m=J.info.K*1E3);
J.info.K=m/1E3;J.info.L=m/1E3},DFu=function(J,m){if(!g.rbS(J)||J.J!=null&&g.y9(m,J.J)&&J.J.J.rawcc!=null)return!1;
m=!!J.J&&J.J.isManifestless&&Object.values(J.J.J).some(S=>g.DC(S,"386"));
J=!!J.J&&!J.J.isManifestless&&g.Icn(J.J);return m||J},Ra1=function(J,m,S){var Y=[];
for(let h in J.G.J){if(!J.G.J.hasOwnProperty(h))continue;let V=J.G.J[h];if(g.DC(V,S||null)){let K=V.info.captionTrack;K&&K.languageCode===m&&Y.push(V)}}return Y.length?Y[0]:null},rGR=function(J,m){var S=[];
for(let h in J.G.J){if(!J.G.J.hasOwnProperty(h))continue;var Y=J.G.J[h];if(g.DC(Y,m||null)){let V=Y.info.id,K=V,E=`.${V}`,T="",k="";if(Y=Y.info.captionTrack)V=Y.languageCode,K=Y.displayName,E=Y.vssId,T=Y.kind,k=Y.id;S.push(new g.HH({id:h,languageCode:V,languageName:K,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:T,captionId:k}))}}return S},BlZ=function(J){var m=Nlk.length;
if(J.byteLength<m)return!1;J=new Uint8Array(J,0,m);for(let S=0;S<m;S++)if(Nlk[S]!==J[S])return!1;return!0},v6=function(J){J=J.split(":");
var m=0;for(let S of J)m=m*60+Number(S);return m*1E3},Qev=function(J,m,S,Y){Y=Object.assign({nM:0},Y);
return new xs(J,m,S,"_"+s$++,Y)},PCR=function(J,m,S,Y,h,V,K,E,T){switch(K.tagName){case "b":E.bold=!0;
break;case "i":E.italic=!0;break;case "u":E.underline=!0}for(let y=0;y<K.childNodes.length;y++){var k=K.childNodes[y];if(k.nodeType===3)k=new n9(m,S,Y,h.id,k.nodeValue,V||y>0,g.de(E)?void 0:E),T.push(k),h.J.push(k);else{let D={};Object.assign(D,E);PCR(J,m,S,Y,h,!0,k,D,T)}}},Wbs=function(J,m,S){if(typeof m==="string"||haR(m))return[{trackData:m,
w6:S}];if(typeof m==="string"&&m.substring(0,6)==="WEBVTT"||typeof m!=="string"&&BlZ(m))return[{trackData:m,w6:S}];var Y=new DataView(m);if(Y.byteLength<=8||Y.getUint32(4)!==1718909296)return[];var h=g.Dbu(Y);if(J.Iq&&h){var V=g.hln(h),K=g.VWV(h);h=h.segmentNumber;V&&h&&J.Iq.Wx(h,V,K)}J=g.jI(Y,1835295092);if(!J||!J.length||!J[0].size)return[];V=[];for(K=0;K<J.length;K++)h=J[K],h=new Uint8Array(m,h.dataOffset,h.size-(h.dataOffset-h.offset)),h=g.hh(h),V.push({trackData:h,w6:S+K*1E3});ozs(Y,V,S);return V=
V.filter(E=>!!E.trackData)},eaX=function(J,m,S){J.J||(J.J=new Fbu);
J=J.J.K(m,S);Math.random()<.01&&g.CR(Error("Deprecated subtitles format in web player: WebVTT"));return J},ozs=function(J,m,S){var Y=g.CC(J,0,1836476516),h=9E4;
Y&&(h=g.ME(Y)||9E4);Y=0;var V=g.jI(J,1836019558);for(let E=0;E<V.length;E++){var K=V[E];E<m.length&&(K=g.CC(J,K.dataOffset,1953653094))&&(K=g.CC(J,K.dataOffset,1952867444))&&(K=g.SI(K)/h*1E3,E===0&&(Y=K),m[E].w6=K-Y+S||S*E*1E3)}},nzu=function(J){var m={};
if(J=g.Wi(J))m.lang=J,g.mDQ.test(J)&&(m.Q4=1);return m},uz=function(J){return J.K==="HLS"&&J.yI?!0:J.aM&&J.yI&&J.K!=="LIVE"&&J.K!=="SABR_LIVE"},seZ=function(J){return!J.D&&J.aM&&J.FG&&(J.K==="LIVE"||J.K==="SABR_LIVE")},L9=function(J,m,S=!1){var Y=J.b5.X("enable_player_captions_new_style_defaults")?xFu:cGs,h=Y.Y7;
J.A={};Object.assign(J.A,Y);J.A.Y7={};Object.assign(J.A.Y7,h);J.L={Y7:{}};var V=m.backgroundOverride?J.L:J.A,K=m.background||h.background;ZI.test(K);V.Y7.background=K;V=m.colorOverride?J.L:J.A;K=m.color||h.color;ZI.test(K);V.Y7.color=K;V=m.windowColorOverride?J.L:J.A;K=m.windowColor||Y.windowColor;ZI.test(K);V.windowColor=K;V=m.backgroundOpacityOverride?J.L:J.A;K=m.backgroundOpacity;K==null&&(K=h.backgroundOpacity);V.Y7.backgroundOpacity=K;V=m.fontSizeIncrementOverride?J.L:J.A;K=m.fontSizeIncrement;
K==null&&(K=h.fontSizeIncrement);V.Y7.fontSizeIncrement=K;K=m.fontStyleOverride?J.L:J.A;V=m.fontStyle;V==null&&(V=h.bold&&h.italic?3:h.bold?1:h.italic?2:0);K=K.Y7;switch(V){case 1:K.bold=!0;delete K.italic;break;case 2:delete K.bold;K.italic=!0;break;case 3:K.bold=!0;K.italic=!0;break;default:delete K.bold,delete K.italic}V=m.textOpacityOverride?J.L:J.A;K=m.textOpacity;K==null&&(K=h.textOpacity);V.Y7.textOpacity=K;V=m.windowOpacityOverride?J.L:J.A;K=m.windowOpacity;K==null&&(K=Y.windowOpacity);V.windowOpacity=
K;Y=m.charEdgeStyleOverride?J.L:J.A;V=m.charEdgeStyle;V==null&&(V=h.charEdgeStyle);Y.Y7.charEdgeStyle=V;Y=m.fontFamilyOverride?J.L:J.A;V=m.fontFamily;V==null&&(V=h.fontFamily);Y.Y7.fontFamily=V;J.loaded&&J.Yk();S&&g.bD("yt-player-caption-display-settings",m,2592E3)},qB=function(J,m,S){m&&!J.eN?(m=CYZ({Q4:0,
lang:"en-GB"}),J.eN=[m,new n9(m.start,m.end-m.start,0,m.id,S??"Captions look like this")],J.player.zc(J.eN)):!m&&J.eN&&(bwI(J,J.eN),J.eN=null)},Zwu=function(J){if(J.b5.X("enable_player_captions_persistence_state_machine")){var m=g.OC("yt-player-caption-persistence");
if(m==null){let S=g.vt().sE(65);if(S===!0)m=!1;else{let Y=g.PH(J.b5)?zl(J):Owe(J);Y!=null?m=!!Y:S===!1&&(m=!0)}m!==void 0&&dJ(J,m)}return m}},zl=function(J){if(!J.V.isInline())return g.OC("yt-player-sticky-caption")},Owe=function(J){if(!J.storage)return null;
try{var m=J.storage.get("module-enabled")}catch(S){J.storage.remove("module-enabled")}return m},wJ=function(J){if(J.b5.X("enable_player_captions_persistence_state_machine"))return Zwu(J);
var m=void 0,S=g.vt().sE(65);if(g.PH(J.b5)&&S!=null){if(zl(J)!=null)return!1;m=!S}return m},IxR=function(J){if(J.b5.qo===1||J.videoData.w1===1||g.$X(J.videoData,"yt:cc")==="alwayson")return!0;
if(J.videoData.captionTracks.length)var m=J.getAudioTrack().G;if(J.b5.X("enable_player_captions_persistence_state_machine")){var S=Zwu(J);if(S!==void 0)return!!S}else if(J.b5.qo===2&&(g.PH(J.b5)?S=zl(J):S=Owe(J),S!=null))return!!S;S=RK(J.player.getAudioTrack(),g.PH(J.b5));var Y=g.$X(J.videoData,"yt:cc");if(wJ(J)===void 0){if(S==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return Y?Y==="on":!0;if(S==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return Y==="on"}else return Y==="on";return m==="ON"||g.$X(J.videoData,
"yt:cc")==="on"},U$=function(J,m=!1){if(J.G&&!m||!J.videoData.captionTracks.length)return!1;
J=J.getAudioTrack();return!!J.J||J.G==="FORCED_ON"},plv=function(J,m){if(J.G){var S=J.V.B9().cS().textTracks,Y=null;
J.K==="HLS"?Y=J.G.getId():Y=J.G.toString();for(let V=0;V<S.length;V++){var h=S[V];h.id===Y&&(m?h.mode!=="showing"&&(h.mode="showing",h=J.G,J.ER(h,!!h,iz(J)?"g":J.C?"m":"s")):h.mode==="showing"&&(h.mode="disabled"))}}},iz=function(J){var m=lz(J);
return!!m&&J.G===m},Gmg=function(J,m){if(J.K==="HLS")return!1;
g.Rg(J.videoData)&&(m=!0);m||(m=J.K==="TTS"?!1:J.K==="INNERTUBE"?!1:!0);return m||J.b5.X("web_watch_disable_account_level_captions_settings")&&g.PH(J.b5)?!0:!!g.vt().sE(66)},lz=function(J){return J.W&&J.W.J},f9=function(J,m){if(!J.J)return null;
if(J.W&&J.W.D)return J.W.D;m=Gmg(J,m);m=g.iK(J.J.J,m);var S=null;if(rNu(J.b5)){var Y=J.V.isInline()?void 0:g.OC("yt-player-caption-sticky-language");var h=[Y,J.videoData.captionsLanguagePreference,J.b5.captionsLanguagePreference,g.$X(J.videoData,"yt:cc_default_lang")];let E=!1;for(let T=0;T<h.length;T++){let k=h[T];if(k){E=!0;for(var V=0;V<m.length;V++)if(g.Wi(m[V])===k)return m[V];for(V=0;V<m.length;V++)if(g.Wi(m[V]).split("-")[0]===k.split("-")[0])return m[V]}}if(E&&J.J&&(h=J.J.W,h.length))for(var K of h)if(K.languageCode===
Y){S=K;break}}else for(K=[J.videoData.captionsLanguagePreference,J.b5.captionsLanguagePreference,g.$X(J.videoData,"yt:cc_default_lang")],Y=0;Y<K.length;Y++)for(h=0;h<m.length;h++)if(g.Wi(m[h])===K[Y])return m[h];K=null;J.W&&J.W.K&&(K=J.W.K);K||(K=m.find(E=>E.isDefault)||null);
K||(K=m[0]||lz(J));K&&S&&g.Wi(K).split("-")[0]!==S.languageCode.split("-")[0]&&(K=Rhs(K,S));return K},XA=function(J,m,S){J.loaded&&J.unload();
S!=null&&(J.C=S,J.C&&(J.b5.X("enable_player_captions_persistence_state_machine")?dJ(J,!!m):g.PH(J.b5)?t7(J,!!m):H6(J,!!m)));m!==null||U$(J,!0)||J.ER(m,!!m,J.C?"m":"s");J.G=m;U$(J)&&(J.G=lz(J));aK(J,J.G??void 0);J.load()},dJ=function(J,m){J.b5.X("enable_player_captions_persistence_state_machine")&&g.bD("yt-player-caption-persistence",m,3122064E3)},t7=function(J,m){J.V.isInline()||g.bD("yt-player-sticky-caption",m,2592E3)},H6=function(J,m){if(J.storage)try{J.storage.set("module-enabled",m)}catch(S){}},
aK=function(J,m){J.b5.X("html5_modify_caption_vss_logging")&&(J.videoData.pu=m)},vzu=function(J,m){var S=J.TT[m.id];
S&&S.G!==m&&(S.dispose(),delete J.TT[m.id],S=null);S||(S=AGk(J,m))&&(J.TT[m.id]=S)},u61=function(J,m){var S=m.windowId;
J.qB[S]||(J.qB[S]=[]);J.qB[S].push(m)},AGk=function(J,m){var S=LbR(J);
if(!S)return null;var Y=J.G?g.Wi(J.G):null;Y&&g.mDQ.test(Y)&&(m.params.Q4=1);var h=J.QE.getPlayerSize();Y=h.height*J.mQ.height;h=h.width*J.mQ.width;J.b5.playerStyle!=="google-live"||J.A.isDefault||Object.assign(m.params,J.A);switch(m.params.nM!=null?m.params.nM:m.J.length>1?1:0){case 1:return new qPv(m,J.A,J.L,S.width,S.height,h,Y,J.b5.experiments,J.oM.bind(J),J.V);case 2:return new zaZ(m,J.A,J.L,S.width,S.height,h,Y,J.b5.experiments,J.oM.bind(J),J.V);default:return new C9(m,J.A,J.L,S.width,S.height,
h,Y,J.b5.experiments,J.oM.bind(J),J.V)}},LbR=function(J){var m=J.QE.getVideoContentRect(!0).height,S=J.QE.getVideoContentRect(!0).width;
if(!m||!S)return null;m*=J.mQ.height;S*=J.mQ.width;return{width:S,height:m}},bwI=function(J,m){J.player.Ja(m);
for(let S of m)g.jX(J.u5,S);DI(J.A0)},dFg=function(J,m){if(!J.J)return{};
if(m){g.de(m)||J.OR(m.vss_id,"m");if(J.D&&J.K!=="HLS"||!g.FQ(m))return;if(g.de(m)){XA(J,null,!0);return}let Y;var S=g.iK(J.J.J,!0);for(let h=0;h<S.length;h++){let V=S[h];V.languageCode!==m.languageCode||Y&&(V.languageName!==m.languageName||(V.captionId||"")!==(m.captionId||"")||g.Pi(V)!==m.displayName)||(Y=m.translationLanguage?Rhs(V,m.translationLanguage):V)}J.nH(m.position);!Y||Y===J.G&&J.loaded||(m=g.RY(),S=g.Wi(Y),m.length&&S===m[m.length-1]||(m.push(S),g.bD("yt-player-caption-language-preferences",
m)),rNu(J.b5)&&!J.V.isInline()&&g.bD("yt-player-caption-sticky-language",S,2592E3),XA(J,Y,!0))}else return J.loaded&&J.G&&!iz(J)?g.oY(J.G):{};return""};
g.mQ.prototype.Wx=g.hn(68,function(J,m,S){this.G.set(J,{xo:m,To:S})});
g.S4.prototype.Wx=g.hn(67,function(J,m,S){this.mQ.Wx(J,m,S)});
g.zT.prototype.N=g.hn(66,function(){return!1});
g.zT.prototype.D=g.hn(65,function(){});
g.dV.prototype.D=g.hn(64,function(J,m,S){this.EE();m=this.L(J,m);var Y=this.ZY.U().X("html5_report_captions_ctmp_qoe"),h=(0,g.l)();this.K();D6u(this,m,{format:"RAW",onSuccess:V=>{this.G=null;if(Y){var K=(V.responseText.length/1024).toFixed();let E=(0,g.l)();this.videoData.yE("capresp",{ms:E-h,kb:K})}K=V.getResponseHeader&&V.getResponseHeader("Content-Length")?Number(V.getResponseHeader("Content-Length")):0;S.tZ(V.responseText,J,void 0,void 0,K)},
onError:Y?V=>{this.videoData.yE("capfail",{status:V?.status??0})}:void 0,
withCredentials:!0})});
g.wV.prototype.D=g.hn(63,function(J,m,S){this.EE();m=this.L(J,m);this.K();this.G=g.Wo(m,{format:"RAW",onSuccess:Y=>{this.G=null;var h=Y.getResponseHeader&&Y.getResponseHeader("Content-Length")?Number(Y.getResponseHeader("Content-Length")):0;S.tZ(Y.responseText,J,void 0,void 0,h)},
withCredentials:!0})});
g.nW.prototype.C=g.hn(62,function(){this.mediaElement.C()});
g.on.prototype.C=g.hn(61,function(){var J=g.lj(document,"track",void 0,this.J);for(let m=0;m<J.length;m++)g.EE(J[m])});
g.nW.prototype.A0=g.hn(60,function(){return this.mediaElement.A0()});
g.on.prototype.A0=g.hn(59,function(){return!(!this.J.textTracks||!this.J.textTracks.addEventListener)});
g.nW.prototype.u5=g.hn(58,function(){return this.mediaElement.u5()});
g.on.prototype.u5=g.hn(57,function(){return!!this.J.textTracks});
g.nW.prototype.eN=g.hn(56,function(J){this.mediaElement.eN(J)});
g.on.prototype.eN=g.hn(55,function(J){for(let m=0;m<J.length;m++)this.J.appendChild(J[m])});
g.rV.prototype.OR=g.hn(42,function(J,m){this.app.PB().OR(J,m)});
g.wW.prototype.OR=g.hn(41,function(J,m){this.J0.OR(J,m)});
g.Iy.prototype.OR=g.hn(40,function(J,m){J=[J,m];g.B7(this,g.o5(this.provider),"cfi",J)});
g.GT.prototype.OR=g.hn(39,function(J,m){this.qoe&&this.qoe.OR(J,m)});
g.aD.prototype.OR=g.hn(38,function(J,m){this.FR.OR(J,m)});
g.Xc.prototype.OR=g.hn(37,function(){});
g.rV.prototype.ER=g.hn(36,function(J,m,S){this.app.PB().ER(J,m,S)});
g.wW.prototype.ER=g.hn(35,function(J,m,S){this.J0.ER(J,m,S)});
g.Iy.prototype.ER=g.hn(34,function(J,m,S){if(this.aM!==J||this.eX!==m)m=m==="rawcc"?"":m,S=[J,m,this.aM,S],g.B7(this,g.o5(this.provider),"cfs",S),this.aM=J,this.eX=m});
g.GT.prototype.ER=g.hn(33,function(J,m,S){this.qoe&&this.qoe.ER(J,m,S)});
g.aD.prototype.ER=g.hn(32,function(J,m,S){this.FR.ER(J,m,S)});
g.Xc.prototype.ER=g.hn(31,function(){});
g.hj.prototype.L8=g.hn(10,function(J){return(J=this.K(J))?J.J:0});
g.$K.prototype.L8=g.hn(9,function(){return 0});
g.HH.prototype.G=g.hn(8,function(){return this.vssId});
var PYX=/#(.)(.)(.)/,Qau=/^#(?:[0-9a-f]{3}){1,2}$/i,wls={en:"English"},UFk=class extends g.zT{constructor(J){super(J);this.G=new Set}A(J){var m=this.ZY.B9();if(m&&m.cS()){m=m.cS().textTracks;for(let S of m)S.kind==="subtitles"&&!this.G.has(S.language)&&S.language&&(g.kT(this.J,new g.HH({languageCode:S.language,languageName:S.language,kind:S.kind,id:S.id,displayName:wls[S.label]||S.label,vss_id:`.${S.language}`})),this.G.add(S.language))}g.iK(this.J).length>0&&J.Qw()}},iw1=class{constructor(){this.segments=
[]}contains(J){J=g.Qg(this.segments,J);return J>=0||J<0&&(-J-1)%2===1}length(){return this.segments.length/2}},lxg=class extends g.rX{constructor(J,m,S,Y,h,V){super();this.policy=J;this.player=m;this.DY=S;this.B=Y;this.A=h;this.N=V;this.D=new iw1;this.L=-1;this.G=this.K=this.J=null;this.mQ=0;this.C=new g.P$(this.eN,1E3,this);this.events=new g.PW(this);g.O(this,this.C);g.O(this,this.events);this.events.j(m,"SEEK_COMPLETE",this.W);this.W();this.eN()}fz(){super.fz();this.G&&this.G.cancel()}W(){this.seekTo(this.player.getCurrentTime())}seekTo(J){J-=
this.player.tp();var m=this.J;this.J=g.z2(this.DY.L(J).WB);m!==this.J&&this.N&&this.N()}reset(){this.D=new iw1;this.L=-1;this.G&&(this.G.cancel(),this.G=null)}eN(){this.EE();var J;if(J=this.J!=null)J=this.J,J=J.DY.D(J);if(J&&!this.G&&!(this.J&&this.J.segmentStartTime-this.player.getCurrentTime()>30)){J=this.J;J=J.DY.A0(J);let h=J.WB[0];if(this.player.getVideoData()?.enableServerStitchedDai){var m=this.player.yG();if(m){var S=h.DY.info.id;let V=h.Cz;var Y=J.WB[0].D;if(this.policy.u5){if(m=g.wHi(m,
Y,V,S,3))J.D=m}else if(S=m.gP(Y,V,S,3))if(Y=2,m.Yb.has(V)?Y=0:g.tT(m,V)&&(Y=1),m=Y,m===0)S&&(J.J=new g.AM(S));else if(m===2){this.C.start();F8X(this)&&this.seekTo(this.player.getCurrentTime());return}}}h.DY.index.Aw(h.Cz)?(this.D.contains(J.WB[0].Cz)||ehv(this,J),this.J=g.z2(J.WB)):F8X(this)&&this.seekTo(this.player.getCurrentTime())}this.C.start()}},fxk=class extends g.zT{constructor(J,m){super(m);this.G=J;this.V=m;this.B=null;this.eN=!1;this.logger=new g.ld("caps");this.mQ=g.y9(this.V,this.G)}D(J,
m,S){this.K();m=n5g(this,J.getId());m||(m=J.languageCode,m=this.G.isManifestless?saZ(this,m,"386"):saZ(this,m));if(m){var Y=(m.index.L8(m.index.Tt())-m.index.getStartTime(m.index.Tt()))*1E3,h=new g.hyn(this.V.U());this.B=new lxg(h,this.V,m,(V,K)=>{S.tZ(V,J,K,Y)},this.mQ||g.Yk(m.info),()=>{this.B&&this.B.reset();
this.eN=!0})}}N(){var J=this.eN;
this.eN=!1;return J}A(J){var m=this.V.U().X("html5_fallback_if_rawcc_missing");var S=this.G.J.rawcc!=null;if(!this.mQ||!S&&m)m=this.G.isManifestless?x6R(this,"386"):x6R(this);else{if(!S){g.f$(this.logger,386248249,"rawcc used but unavailable");return}m=[new g.HH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.HH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let Y of m)g.kT(this.J,
Y);J.Qw()}K(){this.B&&(this.B.dispose(),this.B=null)}L(){return""}},ZI=/^#(?:[0-9a-f]{3}){1,2}$/i;var tlZ=["left","right","center","justify"];var n9=class extends g.hq{constructor(J,m,S,Y,h,V=!1,K=null){super(J,J+m,{priority:S,namespace:"captions"});this.windowId=Y;this.text=h;this.append=V;this.J=K}toString(){return super.toString()}};var C9=class extends g.C{constructor(J,m,S,Y,h,V,K,E,T,k){var y=k.isInline()&&!0,D={};Object.assign(D,m);Object.assign(D,J.params);Object.assign(D,S);var R={};Object.assign(R,m.Y7);J.params.Y7&&Object.assign(R,J.params.Y7);Object.assign(R,S.Y7);y&&(D.windowOpacity=.6,R.backgroundOpacity=0);D.Y7=R;var r=D.Q4===1,W=[{S:"span",Z:"captions-text",O:{style:"word-wrap: normal; display: block;"}}],b=E.RM("caption_edit_on_hover")&&k.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
b&&W.unshift({S:"button",Z:"caption-edit",O:{tabindex:"0","aria-label":o5R()},Y:[{S:"svg",O:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Y:[{S:"path",O:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({S:"div",Z:"caption-window",O:{id:`caption-window-${J.id}`,dir:r?"rtl":"ltr",tabindex:"0",lang:D.lang},Y:W});this.experiments=
E;this.C=[];this.A0=!1;this.G=J;this.MB=this.aM=null;this.f_=V;this.W9=K;this.A=null;this.maxWidth=V*.96;this.maxHeight=K*.96;this.J=D;this.ur=S;this.TT=m;this.K=this.vB("captions-text");J=this.K.style;this.qB=E.RM("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in J||"WebkitBoxDecorationBreak"in J);this.t0=cNu(Y,h,V,K);this.v9=T;b&&(this.L=this.vB("caption-edit"),this.j(this.L,"click",()=>{this.v9()}));
this.type=0;this.oM=this.t0*bee(R);this.vS=y;this.FG=E.RM("enable_centered_caption_for_tvfilm_video")&&k.getVideoData().isTvfilmVideo;this.W=k.U().jN().J.sE(g.LzS);Y=new g.fJ(this.element,!0);g.O(this,Y);Y.subscribe("dragstart",this.n1,this);Y.subscribe("dragmove",this.S7,this);Y.subscribe("dragend",this.Mu,this);this.Yk=this.kk=this.yI=this.eX=0;Y="";this.J.windowOpacity&&(Y=rJ(this.J.windowColor),Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+this.J.windowOpacity+")");h={"background-color":Y,display:this.J.isVisible===
!1?"none":"","text-align":tlZ[this.J.textAlign]};this.qB&&(h["border-radius"]=Y?`${this.oM*.375}px`:"");(this.D=this.G.params.Q4===2||this.G.params.Q4===3)&&Oev(this,this.element);g.pZ(this.element,h);y&&this.element.parentElement?.style.setProperty("--caption-window-color",Y);switch(this.J.yg){case 0:case 1:case 2:g.xd(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.xd(this.element,"ytp-caption-window-bottom")}}n1(J,m){this.kk=J;this.Yk=m;var S=g.t2(this.element,this.element.parentElement);
this.eX=J-S.x;this.yI=m-S.y}S7(J,m){if(J!==this.kk||m!==this.Yk){g.sH(this.element,"ytp-dragging")||g.xd(this.element,"ytp-dragging");var S=g.Xo(this.element);J=J-this.eX-.02*this.f_;var Y=m-this.yI-.02*this.W9,h=(J+S.width/2)/this.maxWidth*3;h=Math.floor(g.sh(h,0,2));var V=(Y+S.height/2)/this.maxHeight*3;V=Math.floor(g.sh(V,0,2));m=h+V*3;J=(J+h/2*S.width)/this.maxWidth;J=g.sh(J,0,1)*100;S=(Y+V/2*S.height)/this.maxHeight;S=g.sh(S,0,1)*100;this.G.params.yg=m;this.G.params.US=S;this.G.params.iV=J;this.G.params.isDefault=
!1;this.J.yg=m;this.J.US=S;this.J.iV=J;this.J.isDefault=!1;this.TT.yg=m;this.TT.US=S;this.TT.iV=J;this.TT.isDefault=!1;this.lS()}}Mu(){g.bw(this.element,"ytp-dragging")}lS(){this.B(this.C)}B(J){var m=this.vS?0:Math.min(this.wX(),this.maxWidth),S=this.jX(),Y=this.vS;if(Y){var h=getComputedStyle(this.K.parentNode);h=B6(h.borderLeftWidth)+B6(h.borderRightWidth)+B6(h.paddingLeft)+B6(h.paddingRight)}else h=0;var V=h;h="";this.G.params.Q4===3&&(h="rotate(180deg)");var K=Y?`calc(96% - ${V}px)`:"96%";g.pZ(this.element,
{top:0,left:0,right:"",bottom:"",width:m?`${m}px`:"",height:S?`${S}px`:"","max-width":K,"max-height":K,margin:"",transform:""});this.d2(J);h={transform:h,top:"",left:"",width:m?`${m}px`:"",height:S?`${S}px`:"","max-width":"","max-height":""};K=this.J.yg;var E=this.J.iV,T=this.J.US;this.FG&&K!=null&&(E=50,K=Math.floor(K/3)*3+1);E=E*.96+2;switch(K){case 0:case 3:case 6:(Y=this.J.Y7.fontSizeIncrement)&&Y>0&&this.J.Q4!==2&&this.J.Q4!==3&&(E=Math.max(E/(1+Y*2),2));h.left=`${E}%`;break;case 1:case 4:case 7:h.left=
`${E}%`;E=0;this.W||(E=this.K.offsetWidth);m||E?(m=m||E+1,h.width=`${m}px`,h["margin-left"]=Y?`${m/-2-V/2}px`:`${m/-2}px`):(this.W&&(h.width="max-content"),h.transform+=" translateX(-50%)");break;case 2:case 5:case 8:h.right=`${100-E}%`}Y=T*.96+2;switch(K){case 0:case 1:case 2:h.top=`${Y}%`;break;case 3:case 4:case 5:h.top=`${Y}%`;Y=0;this.W||(Y=this.element.clientHeight);(S=S||Y)?(h.height=`${S}px`,h["margin-top"]=`${S/-2}px`):h.transform+=" translateY(-50%)";break;case 6:case 7:case 8:h.bottom=
`${100-Y}%`}g.pZ(this.element,h);this.L&&(this.W?S=this.oM:(J=Imv(this,J),S=this.FG?J>0?this.K.offsetHeight/J:0:this.K.offsetHeight/J),this.L.style.height=`${S}px`,this.L.style.width=`${S}px`,this.element.style.paddingLeft=`${S+5}px`,this.element.style.paddingRight=`${S+5}px`,this.W||(J=Number(this.element.style.marginLeft.replace("px",""))-S-5,S=Number(this.element.style.marginRight.replace("px",""))-S-5,this.element.style.marginLeft=`${J}px`,this.element.style.marginRight=`${S}px`))}d2(J){if(this.type===
0&&this.G.params.Bs!==void 0&&this.experiments.RM("web_enable_popon_asr_captions")){var m=J,S=this.G.params.Bs;if(m.length===0||S<=0)J=[];else{J=[];for(let h=m.length-1;h>=0;h--){var Y=m[h];J.unshift(Y);let V=Imv(this,J);if(V>S){J.shift();typeof Y.text==="string"&&(m=Y.text.split("\n"),S=V-S,m.length-S>0&&(S=m.slice(S),Y=new n9(Y.start,Y.end-Y.start,Y.priority||0,Y.windowId,S.join("\n"),Y.append,Y.J),J.unshift(Y)));break}}}}for(Y=0;Y<J.length&&J[Y]===this.C[Y];Y++);if(this.A0||this.C.length>Y)Y=0,
this.A0=!1,this.C=[],this.A=this.MB=this.aM=null,g.$c(this.K);for(;Y<J.length;Y++)ANI(this,J[Y])}wX(){return 0}jX(){return 0}toString(){return super.toString()}};var axg=class{constructor(){this.K=this.time=this.mode=this.G=0;this.D=new Hwu(this);this.A=new Hwu(this);this.J=[];this.clear()}clear(){this.K=this.time=this.mode=0;this.J=[];this.reset()}reset(){this.mode=0;this.D.reset(0);this.A.reset(1)}},v5v=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],XlR=class{constructor(){this.type=0}set(J){this.type=J}get(){return this.type}},CCs=class{constructor(){this.state=this.Li=this.s4=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}df(){return this.state!==0}matches(J,m){return this.df()&&J===this.s4&&m===this.Li}},Mlk=class{constructor(){this.timestamp=this.J=0}reset(){this.timestamp=
this.J=0}},MB=class{constructor(J){this.A=J;this.K=[];this.J=this.G=this.row=0;this.style=new XlR;this.D=0;for(J=0;J<=15;J++){this.K[J]=[];for(let m=0;m<=32;m++)this.K[J][m]=new Mlk}}updateTime(J){for(let m=1;m<=15;++m)for(let S=1;S<=32;++S)this.K[m][S].timestamp=J}debugString(){var J="\n";for(let m=1;m<=15;++m){for(let S=1;S<=32;++S){let Y=this.K[m][S];J=Y.J===0?J+"_":J+String.fromCharCode(Y.J)}J+="\n"}return J}reset(J){for(let m=0;m<=15;m++)for(let S=0;S<=32;S++)this.K[m][S].reset();this.D=J;this.J=
0;this.G=this.row=1}},d6e=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],wKg=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],U6I=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],iev=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],JrR=class{constructor(J){this.K=J;this.A=0;this.style=new XlR;this.L=new MB(this.K);this.C=new MB(this.K);this.text=new MB(this.K);this.G=this.L;this.D=this.C;this.J=this.G}reset(J,m){this.A=m;this.style.set(2);this.G=this.L;this.D=this.C;this.J=this.G;var S=(J<<2)+(m<<1);this.L.reset(S);this.C.reset(S);this.text.reset((J<<
2)+(m<<1)+1)}},Hwu=class{constructor(J){this.J=J;this.A=0;this.K=new JrR(this.J);this.L=new JrR(this.J);this.G=new CCs;this.D=this.K}reset(J){this.A=J;this.G.clear();this.D=this.K;this.K.reset(J,0);this.L.reset(J,1)}};var mmX=class{D(){}};var JH=class extends g.rX{reset(){}};var xs=class extends g.hq{constructor(J,m,S,Y,h){super(J,J+m,{priority:S,namespace:"captions"});this.id=Y;this.params=h;this.J=[]}toString(){return super.toString()}},s$=0;var Sr1=class extends JH{constructor(J){super();this.D=J;this.pens={};this.B={};this.W={};this.A="_"+s$++;this.C={};this.G=this.J=null;this.L=!0}reset(){this.C={};this.G=this.J=null;this.L=!0}K(J,m){J=J.firstChild;J.getAttribute("format");m=m||0;Number.isFinite(m);J=Array.from(J.childNodes);for(var S of J)if(S.nodeType===1)switch(S.tagName){case "head":var Y=S;break;case "body":var h=S}if(Y){Y=Array.from(Y.childNodes);for(var V of Y)if(V.nodeType===1)switch(V.tagName){case "pen":S=V.getAttribute("id");
Y=this.pens;J={};var K=V.getAttribute("p");K&&Object.assign(J,this.pens[K]);K=bz(V,"b");K!=null&&(J.bold=K);K=bz(V,"i");K!=null&&(J.italic=K);K=bz(V,"u");K!=null&&(J.underline=K);K=O$(V,"et");K!=null&&(J.charEdgeStyle=K);K=O$(V,"of");K!=null&&(J.offset=K);K=IK(V,"bc");K!=null&&(J.background=K);K=IK(V,"ec");K!=null&&(J.Dw=K);K=IK(V,"fc");K!=null&&(J.color=K);K=O$(V,"fs");K!=null&&K!==0&&(J.fontFamily=K);K=c6(V,"sz");K!==void 0&&(J.fontSizeIncrement=K/100-1);K=c6(V,"bo");K!==void 0&&(J.backgroundOpacity=
K/255);K=c6(V,"fo");K!==void 0&&(J.textOpacity=K/255);K=O$(V,"rb");K!=null&&K!==10&&K!==0&&(J.ef=K>10?K-1:K);K=O$(V,"hg");K!=null&&(J.HD=K);Y[S]=J;break;case "ws":Y=V.getAttribute("id");this.W[Y]=M5v(this,V);break;case "wp":Y=V.getAttribute("id"),this.B[Y]=JGu(this,V)}}if(h){V=[];h=Array.from(h.childNodes);for(b of h)if(b.nodeType===1)switch(b.tagName){case "w":this.J=mFe(this,b,m,!1);(h=this.C[this.J.id])&&h.end>this.J.start&&(h.end=this.J.start);this.C[this.J.id]=this.J;V.push(this.J);break;case "p":var E=
b;J=m;h=[];Y=E.getAttribute("w")||this.A;S=!!bz(E,"a");J=(c6(E,"t")||0)+J;K=c6(E,"d")||5E3;S||(!this.L&&this.G&&this.G.windowId===Y&&this.G.end>J&&(this.G.end=J),this.G&&this.G.text==="\n"&&(this.G.text=""));let v=S?6:5;var T=E.getAttribute("p");T=T?this.pens[T]:null;let q=Array.from(E.childNodes);q.length&&(this.L=E.getAttribute("d")!=null);for(E=0;E<q.length;E++){var k=q[E],y=void 0;E>0&&(S=!0);let d;k.nodeType===1&&(d=k);if(d&&d.tagName==="s"){if((k=(k=d.getAttribute("p"))?this.pens[k]:null)&&
k.ef&&(k.ef===1?(k=q.slice(E,E+4),k.length===4&&(y=XKR(J,K,Y,S,v,k,this.pens),E+=3)):y=XKR(J,K,Y,S,v,[d],this.pens)),!y){var D=d;y=J;k=K;var R=Y,r=S;let w=D.textContent?D.textContent:"";var W=D.getAttribute("p");W=W?this.pens[W]:null;D=c6(D,"t")||0;y=new n9(y+D,k-D,v,R,w,r,W)}}else y=new n9(J,K,v,Y,k.textContent||"",S,T);h.push(y);this.G=y}if(h.length>0){h[0].windowId===this.A&&(this.J=mFe(this,b,m,!0),V.push(this.J));for(let d of h)d.windowId=this.J.id,this.J.J.push(d),V.push(d)}}var b=V}else b=
[];return b}};var jGb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Yre=class extends JH{constructor(J){super();this.L=J;this.J=new Map;this.D=new Map;this.A=new Map;this.G=new Map}reset(){this.G.clear()}K(J,m){J=JSON.parse(J);if(!J)return[];if(J.pens){var S=J.pens,Y=0;for(var h of S){S={};var V=h.pParentId;V&&Object.assign(S,this.J.get(V));h.bAttr&&(S.bold=!0);h.iAttr&&(S.italic=!0);h.uAttr&&(S.underline=!0);V=h.ofOffset;V!=null&&(S.offset=V);h.szPenSize!==void 0&&(S.fontSizeIncrement=h.szPenSize/100-1);
V=h.etEdgeType;V!=null&&(S.charEdgeStyle=V);h.ecEdgeColor!==void 0&&(S.Dw=p9(h.ecEdgeColor));V=h.fsFontStyle;V!=null&&V!==0&&(S.fontFamily=V);h.fcForeColor!==void 0&&(S.color=p9(h.fcForeColor));h.foForeAlpha!==void 0&&(S.textOpacity=h.foForeAlpha/255);h.bcBackColor!==void 0&&(S.background=p9(h.bcBackColor));h.boBackAlpha!==void 0&&(S.backgroundOpacity=h.boBackAlpha/255);(V=h.rbRuby)&&V!==10&&(S.ef=V>10?V-1:V,S.textEmphasis=jGb.get(S.ef));h.hgHorizGroup&&(S.HD=h.hgHorizGroup);this.J.set(Y++,S)}}if(J.wsWinStyles){Y=
J.wsWinStyles;h=0;for(var K of Y)Y={},(S=K.wsParentId)?Object.assign(Y,this.A.get(S)):Object.assign(Y,this.L),K.mhModeHint!==void 0&&(Y.nM=K.mhModeHint),K.juJustifCode!==void 0&&(Y.textAlign=K.juJustifCode),K.pdPrintDir!==void 0&&(Y.Q4=K.pdPrintDir),K.sdScrollDir!==void 0&&(Y.Va=K.sdScrollDir),K.wfcWinFillColor!==void 0&&(Y.windowColor=p9(K.wfcWinFillColor)),K.wfoWinFillAlpha!==void 0&&(Y.windowOpacity=K.wfoWinFillAlpha/255),this.A.set(h++,Y)}if(J.wpWinPositions){h=J.wpWinPositions;K=0;for(var E of h)h=
{},(Y=E.wpParentId)&&Object.assign(h,this.D.get(Y)),E.ahHorPos!==void 0&&(h.iV=E.ahHorPos),E.apPoint!==void 0&&(h.yg=E.apPoint),E.avVerPos!==void 0&&(h.US=E.avVerPos),E.ccCols!==void 0&&(h.lJ=E.ccCols),E.rcRows!==void 0&&(h.Bs=E.rcRows),this.D.set(K++,h)}if(J.events){J=J.events;E=[];for(let f of J)if(K=(f.tStartMs||0)+m,h=f.dDurationMs||0,f.id)Y=String(f.id),J=SPs(this,f,K,h,Y),E.push(J),this.G.set(Y,J);else{f.wWinId?Y=f.wWinId.toString():(Y="_"+s$++,J=SPs(this,f,K,h,Y),E.push(J),this.G.set(Y,J));
J=E;var T=f;h===0&&(h=5E3);S=this.G.get(Y);let mt=(V=!!T.aAppend)?6:5,rF=T.segs,xf=null;T.pPenId&&(xf=this.J.get(T.pPenId));for(T=0;T<rF.length;T++){var k=rF[T],y=k.utf8;if(y){var D=k.tOffsetMs||0;let An=null;k.pPenId&&(An=this.J.get(k.pPenId));if((S.params.nM!=null?S.params.nM:S.J.length>1?1:0)===2&&V&&y==="\n")continue;k=null;var R=[],r;if(r=An&&An.ef===1)a:{r=rF;var W=T;if(W+3>=r.length||!r[W+1].pPenId||!r[W+2].pPenId||!r[W+3].pPenId){r=!1;break a}var b=r[W+1].pPenId;(b=this.J.get(b))&&b.ef&&b.ef===
2?(b=r[W+2].pPenId,b=this.J.get(b),!b||!b.ef||b.ef<3?r=!1:(b=r[W+3].pPenId,r=(b=this.J.get(b))&&b.ef&&b.ef===2?!0:!1)):r=!1}if(r)D=rF[T+1].utf8,k=rF[T+3].utf8,r=rF[T+2].utf8,W=this.J.get(rF[T+2].pPenId),y=ame(y,D,r,k,W),k=new n9(K,h,mt,Y,y,V,An),T+=3;else{if(y.indexOf("<")>-1){R=An;r=xf;W=K;b=h;var v=D,q=mt,d=V;let iV=[];var w=g.XN(`<html>${y}</html>`);if(!w.getElementsByTagName("parsererror").length&&w.firstChild?.childNodes.length)for(let CD of w.firstChild.childNodes){w=CD.textContent?.replace(/\n/g,
"")??"";if(CD.nodeType===3&&(!w||w.match(/^ *$/)!=null))continue;let Zz={};Object.assign(Zz,R||r);switch(CD?.tagName){case "b":Zz.bold=!0;break;case "i":Zz.italic=!0;break;case "u":Zz.underline=!0}iV.push(new n9(W+v,b-v,q,S.id,w,d,Zz))}R=iV}R.length||(R=[new n9(K+D,h-D,mt,S.id,y,V,An||xf)])}if(R.length)for(let iV of R)J.push(iV),S.J.push(iV);else k&&(J.push(k),S.J.push(k))}V=!0}}m=E}else m=[];return m}};var hB1=class extends g.zT{constructor(J,m,S){super(J);this.videoData=m;this.audioTrack=S;this.W=m.D_}D(J,m,S){BXt(this.videoData.videoId,J.vssId,S.tZ)}A(J){if(this.audioTrack)for(let m of this.audioTrack.captionTracks)g.kT(this.J,m);J.Qw()}};var qPv=class extends C9{constructor(J,m,S,Y,h,V,K,E,T,k){super(J,m,S,Y,h,V,K,E,T,k);this.type=1}d2(J){var m=this.G.J;super.d2(J);for(J=J.length;J<m.length;J++){let h=m[J],V;if(Y&&h.J===S)V=Y;else{V={};Object.assign(V,h.J);Object.assign(V,Vo1);var S=h.J;var Y=V}ANI(this,h,V)}}},Vo1={sL:!0};var jeu=class extends mmX{constructor(J,m){super();this.trackData=J;this.L=m;this.version=this.A=this.K=this.byteOffset=0;this.G=[];this.J=new DataView(this.trackData)}D(J,m,S,Y,h){if(S<Y){let V="_"+s$++;S=S/1E3-this.L;Y=Y/1E3-this.L;J=new xs(S,Y-S,5,V,{textAlign:0,yg:0,iV:m*2.5,US:J*5.33});h=new n9(S,Y-S,5,V,h);this.G.push(J);this.G.push(h)}}},$mZ=class extends JH{constructor(J,m){super();this.G=J;this.D=m;this.track=this.D.languageName==="CC3"?4:0;this.J=new axg;this.J.G=1<<this.track}K(J){J=new jeu(J,
this.G);if(YPs(J)){for(;J.byteOffset<J.J.byteLength;)for(J.version===0?J.K=A7(J)*(1E3/45):J.version===1&&(J.K=A7(J)*4294967296+A7(J)),J.A=Gl(J);J.A>0;J.A--){var m=Gl(J);let S=Gl(J),Y=Gl(J);m&4&&(m&3)===this.track&&(this.track===0||this.track===1)&&(m=this.J,m.J.push({time:J.K,type:this.track,GB:S,cO:Y,order:m.J.length}))}zhZ(this.J,J);return J.G}return[]}reset(){this.J.clear()}};var zaZ=class extends C9{constructor(J,m,S,Y,h,V,K,E,T,k){super(J,m,S,Y,h,V,K,E,T,k);this.type=2;this.GT=[];this.mQ=this.N=this.h0=0;this.u5=NaN;this.s9=0;this.YI=null;this.HS=new g.P$(this.QE,433,this);this.L&&(k.createClientVe(this.L,this,167342),this.j(this.L,"click",()=>{k.logClick(this.L)}),J=new g.fJ(this.element,!0),g.O(this,J),J.subscribe("hoverstart",()=>{k.logVisibility(this.L,!0)},this));
g.xd(this.element,"ytp-caption-window-rollup");g.O(this,this.HS);g.pZ(this.element,"overflow","hidden")}lS(){g.W$(this.HS)}QE(){this.element.removeEventListener("transitionend",this.QE,!1);g.bw(this.element,"ytp-rollup-mode");this.B(this.YI,!0)}jX(){return this.D?this.mQ:this.N}wX(){return this.D?this.N:this.mQ}B(J,m){this.YI=J;if(this.G.params.Bs){var S=0;for(let Y=0;Y<this.C.length&&S<J.length;Y++)this.C[Y]===J[S]&&S++;S>0&&S<J.length&&(J=this.C.concat(J.slice(S)));this.s9=this.mQ;this.N=this.mQ=
0;super.B(J);KbR(this,m)}super.B(J)}};var KOb=class{constructor(J,m,S,Y){this.V=J;this.A=m;this.logger=S;this.Kg=Y;this.pg=[];this.J=null;this.K=[];this.lx=[];this.G=null;this.xI={bXz:()=>this.G,
G8:()=>this.pg,
c2N:h=>{this.K=h},
JyB:()=>this.K};
J=g.EI(this.V.U().experiments,"html5_override_micro_discontinuities_threshold_ms");this.D=J>0?J:10}unload(){this.G!=null&&(this.V.removeEventListener("sabrCaptionsDataLoaded",this.G),this.G=null);this.pg=[];this.J=null;this.K=[];this.V.publish("sabrCaptionsBufferedRangesUpdated",this.pg)}aF(J){return{formatId:g.V2(J.info.DY.info,this.Kg),Cz:J.info.Cz+(this.Kg?0:1),startTimeMs:J.info.D*1E3,durationMs:J.info.L*1E3}}};var EbR=class extends g.zT{constructor(J,m){super(m);this.G=J;this.V=m;this.logger=new g.ld("caps");this.B=this.mQ=null;this.eN=new KOb(this.V,this,this.logger,this.G.Kg)}D(J,m,S){this.K();m=J.getId();m=m!=null&&m in this.G.J?this.G.J[m]:null;m||(m=J.languageCode,m=this.G.isManifestless?Ra1(this,m,"386"):Ra1(this,m));m&&(this.B=J,this.mQ=m,yGI(this.eN,S),this.V.publish("sabrCaptionsTrackChanged",g.V2(m.info,this.G.Kg)))}A(J){var m=this.G.isManifestless?rGR(this,"386"):rGR(this);for(let S of m)g.kT(this.J,
S);J.Qw()}K(){this.B&&(this.B=this.mQ=null,this.eN.unload(),this.V.publish("sabrCaptionsTrackChanged",null))}L(){return""}};var Nlk="WEBVTT".split("").map(J=>J.charCodeAt(0)),Fbu=class extends JH{constructor(){super()}K(J,m){J instanceof ArrayBuffer&&(J=g.hh(new Uint8Array(J)));
var S=[];J=J.split(TiR);for(let W=1;W<J.length;W++){var Y=J[W],h=m;if(Y!==""&&!gbX.test(Y)){var V=m4.exec(Y);if(V&&V.length>=4){var K=v6(V[1]),E=v6(V[2])-K;K+=h;var T=(V=V[3])?V.split(" "):[];V={};var k=null;var y="";var D=null,R="";for(let b of T){T=b.split(":");if(T.length!==2)continue;var r=T[1];switch(T[0]){case "line":T=r.split(",");T[0].endsWith("%")&&(k=T[0],V.US=Number.parseInt(k,10),T.length===2&&(y=T[1].trim()));break;case "position":T=r.split(",");D=T[0];V.iV=Number.parseInt(D,10);T.length===
2&&(R=T[1].trim());break;case "align":switch(r){case "start":V.textAlign=0;break;case "middle":V.textAlign=2;break;case "end":V.textAlign=1}}}k||y||(y="end");if(!D)switch(V.textAlign){case 0:V.iV=0;break;case 1:V.iV=100;break;case 2:V.iV=50}if(V.textAlign!=null){k=0;switch(y){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(R){case "line-left":k+=0;break;case "center":k+=1;break;case "line-right":k+=2;break;default:switch(V.textAlign){case 0:k+=0;break;case 2:k+=1;break;case 1:k+=
2}}y=k<0||k>8?7:k;V.yg=y}Y=Y.substring(m4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");R=V;V={};if(Y.indexOf("<")<0&&Y.indexOf("&")<0)h=Qev(K,E,5,R),K=new n9(K,E,5,h.id,Y,!1,g.de(V)?void 0:V),S.push(h),S.push(K),h.J.push(K);else for(y=Y.split(kvs),y.length===1?(Y=5,R=Qev(K,E,Y,R)):(k=Y=6,R=Object.assign({lJ:32},R),R=new xs(K,E,k,"_"+s$++,R)),S.push(R),k=K,D=0;D<y.length;D++)if(T=y[D],D%2===0){r=g.XN(`<html>${T}</html>`);let b;r.getElementsByTagName("parsererror").length?(b=r.createElement("span"),
b.appendChild(r.createTextNode(T))):b=r.firstChild;PCR(this,k,E-(k-K),Y,R,D>0,b,V,S)}else k=v6(T)+h}m4.lastIndex=0}}return S}},gbX=/^NOTE/,TiR=/(?:\r\n|\r|\n){2,}/,m4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),kvs=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var yrk=class extends g.rX{constructor(J,m){super();this.V=J;this.b5=m;this.J=null;this.Iq=this.V.yG();this.logger=new g.ld("caps")}clear(){this.J&&this.J.dispose();this.J=null}reset(){this.J&&this.J.reset()}fz(){super.fz();this.clear()}};var cGs={windowColor:"#080808",windowOpacity:0,textAlign:2,yg:7,iV:50,US:100,isDefault:!0,Y7:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},xFu={windowColor:"#080808",windowOpacity:0,textAlign:0,yg:7,iV:50,US:100,isDefault:!0,Y7:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.gs("captions",class extends g.qa{constructor(J){super(J);this.V=J;this.u5=[];this.TT={};this.qB={};this.C=!1;this.K="NONE";this.J=this.W=this.eN=this.h0=this.t0=null;this.kk={Qw:()=>{this.Qw()},
tZ:(Y,h,V,K,E=0)=>{var T=Number(this.videoData.U().jN().J.sE(g.XsS)??0);E>0&&T>0&&this.videoData.lengthSeconds>0&&E/this.videoData.lengthSeconds>T?this.V.yE("tts",{dropcap:E}):this.tZ(Y,h,V,K)}};
this.G=null;this.eX="";this.b5=this.V.U();this.videoData=this.V.getVideoData();this.QE=this.V.nz();this.A={Y7:{}};this.L={Y7:{}};this.videoData.Cg()?this.K="OFFLINE":g.ZnS(this.videoData,this.V)?this.K="HLS":DFu(this.videoData,this.V)?this.K="SABR_LIVE":g.ICQ(this.videoData,this.V)?this.K="LIVE":this.videoData.captionTracks.length?this.K="INNERTUBE":this.videoData.yI&&(this.K="TTS");this.aM=this.b5.controlsType==="3";this.d2=new yrk(this.V,this.b5);this.GT=new g.PW(this);this.B=new g.C({S:"div",Z:"ytp-caption-window-container",
O:{id:"ytp-caption-window-container"}});this.mQ={top:0,right:0,bottom:0,left:0,width:1,height:1};var m=null,S=g.j7("yt-html5-player-modules::subtitlesModuleData");S&&(m=new g.t1(S));this.storage=m;m=J.B9();this.yI=!!m?.u5();this.FG=!!m?.A0();this.D=uz(this);this.N=seZ(this);g.O(this,this.d2);this.D?this.MB=this.A0=null:(this.A0=new g.QU(this.vS,void 0,this),g.O(this,this.A0),this.MB=new g.P$(this.HS,2E3,this),g.O(this,this.MB));g.O(this,this.GT);g.H9(this.player,this.B.element,4);g.O(this,this.B);
this.D||this.GT.j(J,"resize",this.Yk);m=g.Vs(this.b5)&&!g.Bt()&&!this.V.isFullscreen();S=this.b5.jN().J.sE(g.rOQ)&&g.aT(this.b5)&&g.c3;(this.Cg=(m||S)&&!this.D&&!this.N)&&this.GT.j(J,m?"resize":"fullscreentoggled",this.wX);this.GT.j(J,"onPlaybackAudioChange",this.jX);this.GT.j(J,g.zz("captions"),Y=>{this.onCueRangeEnter(Y)});
this.GT.j(J,g.da("captions"),Y=>{this.onCueRangeExit(Y)});
L9(this,NB()||{});g.Ig(this.player,"onCaptionsModuleAvailable");this.K==="HLS"&&this.D&&(J=this.V.B9().cS(),this.FG&&this.GT.j(J.textTracks,"addtrack",this.s9))}fz(){if(this.D||this.N){let J=this.V.B9();J&&!J.EE()&&J.C()}else qB(this,!1);super.fz()}Nh(){return this.b5.X("html5_honor_caption_availabilities_in_audio_track")&&this.K!=="LIVE"&&this.K!=="SABR_LIVE"}Bm(){if(this.aM)return this.D||this.N;if(this.K==="HLS")return this.D;var J=this.getAudioTrack();if(this.Nh()){if(!J.captionTracks.length)return!1;
if(!this.J)return!0}J=RK(J,g.PH(this.b5));return J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?U$(this):wJ(this)||U$(this)?!0:IxR(this)}load(){super.load();this.W=this.getAudioTrack();if(this.J)this.G&&(this.d2.clear(),this.D?plv(this,!0):this.player.getPresentingPlayerType()!==3&&this.J.D(this.G,"json3",this.kk),this.K!=="HLS"&&this.D||this.N||iz(this)||g.Ig(this.player,"captionschanged",g.oY(this.G)));else{let J;this.K==="OFFLINE"?J=new hB1(this.player,this.videoData,
this.getAudioTrack()):this.K==="SABR_LIVE"?J=new EbR(this.videoData.J,this.player):this.K==="HLS"?J=new UFk(this.player):this.K==="LIVE"?J=new fxk(this.videoData.J,this.player):this.K==="INNERTUBE"?J=new g.dV(this.player,this.videoData,this.getAudioTrack()):J=new g.wV(this.player,this.videoData.yI,this.videoData.videoId,g.QLn(this.videoData),this.videoData.Od,this.videoData.eventId);this.J=J;g.O(this,this.J);this.J.A(this.kk)}}unload(){this.D&&this.G?plv(this,!1):(this.MB&&this.MB.m6(),this.player.h8("captions"),
this.u5=[],this.J&&this.J.K(),this.d2.clear(),this.eN&&this.player.zc(this.eN),this.Yk());super.unload();this.player.QW();g.Ig(this.player,"captionschanged",{})}create(){this.Bm()&&this.load();var J;a:{if(this.b5.X("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let m of J)if(m.kind==="asr"&&m.languageCode===
"en"){J=!0;break a}J=!1}J&&this.V.publish("showpromotooltip",this.B.element)}Qw(){var J=RK(this.player.getAudioTrack(),g.PH(this.b5));var m=J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?f9(this,this.C):J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&U$(this)?lz(this):wJ(this)||this.C||IxR(this)?f9(this,this.C):U$(this)?lz(this):null;if(this.K!=="HLS"&&this.D||this.N){let S=g.iK(this.J.J,!0);J=[];for(let Y=0;Y<S.length;Y++){let h=S[Y],V=g.Yc("TRACK");V.setAttribute("kind","subtitles");V.setAttribute("label",
g.Pi(h));V.setAttribute("srclang",g.Wi(h));V.setAttribute("id",h.toString());this.N||V.setAttribute("src",this.J.L(h,"vtt"));h===m&&V.setAttribute("default","1");J.push(V)}m=this.V.B9();m.eN(J);J=m.cS();this.FG&&this.GT.j(J.textTracks,"change",this.lS)}else!this.G&&m&&XA(this,m),g.Ig(this.player,"onCaptionsTrackListChanged"),g.p_(this.player,"onApiChange")}getTrackById(J){var m=g.iK(this.J.J,!0);for(let S=0;S<m.length;S++)if(m[S].toString()===J)return m[S];return null}lS(){var J=this.V.B9().cS().textTracks,
m=null;for(let S=0;S<J.length;S++)J[S].mode==="showing"&&(m=this.getTrackById(J[S].id));(this.loaded?this.G:null)!==m&&XA(this,m,!0)}s9(){this.J?.A(this.kk)}gY(){!this.G&&this.D||this.unload()}tZ(J,m,S,Y){if(J){aK(this,this.G??void 0);this.J.N()&&(this.u5=[],this.V.h8("captions"),DI(this.A0),this.d2.reset());a:{var h=this.d2;Y=Y||0;S=Wbs(h,J,S||0);J=[];try{for(let q of S){let d=q.trackData,w=q.w6,f=h.b5.X("safari_live_drm_captions_fix");if(typeof d!=="string"){S=J;var V=S.concat;if(f&&BlZ(d))var K=
eaX(h,d,w);else{var E=h,T=m,k=d,y=w,D=Y;if(!haR(k))throw Error("Invalid binary caption track data");E.J||(E.J=new $mZ(D,T));K=E.J.K(k,y)}var R=V.call(S,K)}else{if(d.substring(0,6)==="WEBVTT")var r=J.concat(eaX(h,d,w));else{S=J;var W=S.concat;b:{T=h;E=m;if(d[0]==="{")try{T.J||(T.J=new Yre(nzu(E)));var b=T.J.K(d,w);break b}catch(xf){g.af(xf);b=[];break b}let mt=g.XN(d);if(!mt||!mt.firstChild){let xf=Error("Invalid caption track data");xf.params=d;throw xf;}if(mt.firstChild.tagName==="timedtext"){if(Number(mt.firstChild.getAttribute("format"))===
3){k=mt;T.J||(T.J=new Sr1(nzu(E)));b=T.J.K(k,w);break b}let xf=Error("Unsupported subtitles format in web player (Format2)");xf.params=d;throw xf;}if(mt.firstChild.tagName==="transcript"){let xf=Error("Unsupported subtitles format in web player (Format1)");xf.params=d;throw xf;}let rF=Error("Invalid caption track data");rF.params=d;throw rF;}r=W.call(S,b)}R=r}J=R}var v=J;break a}catch(q){g.f$(h.logger,187101178,`Captions parsing failed: ${q.message}. `);h.clear();v=[];break a}v=void 0}this.b5.X("html5_sabr_live_support_subfragmented_captions")&&
this.J instanceof EbR&&(m=this.J.eN,h=[],v.length>0&&(h=v.slice(m.K.length)),m.K=!m.J||m.J.info.A8?[]:v,v=h);m=this.b5.jN().J.sE(g.hOD);v.length>0&&(!m||this.eX!==this.G?.G())&&(h=this.G,this.ER(h,!!h,iz(this)?"g":this.C?"m":"s"),m&&(this.eX=this.G?.G()||""));this.player.zc(v,void 0,this.K==="LIVE"||this.K==="SABR_LIVE");!this.C||this.N||iz(this)||g.xO(this.b5)||g.hU(this.b5)||g.Nk(this.b5)||this.b5.GT==="shortspage"||this.player.isInline()||(this.MB.m6(),v=CYZ({yg:0,iV:5,US:5,Bs:2,textAlign:0,Q4:0,
lang:"en-GB"}),this.h0=[v],m=["Click "," for settings"],this.t0||(h=new g.vN(g.tt()),g.O(this,h),this.t0=h.element),h=v.end-v.start,(R=g.Pi(this.G))&&this.h0.push(new n9(v.start,h,0,v.id,R)),this.h0.push(new n9(v.start,h,0,v.id,m[0]),new n9(v.start,h,0,v.id,this.t0,!0),new n9(v.start,h,0,v.id,m[1],!0)),this.player.zc(this.h0),g.o8(this.MB));!this.C||this.N||iz(this)||(this.b5.X("enable_player_captions_persistence_state_machine")?dJ(this,!0):g.PH(this.b5)?t7(this,!0):H6(this,!0),this.W&&(this.W.D=
this.G),this.player.QW());this.C=!1}}onCueRangeEnter(J){this.u5.push(J);DI(this.A0)}onCueRangeExit(J){g.jX(this.u5,J);this.J instanceof fxk&&this.J.mQ&&this.player.Ja([J]);DI(this.A0)}getCaptionWindowContainerId(){return this.B.element.id}HS(){bwI(this,this.h0);this.h0=null}vS(){if(!this.Cg||!this.D){this.A0.stop();g.we(this.qB);this.u5.sort(g.qu);var J=this.u5;if(this.eN){let m=g.wF(J,function(S){return this.eN.indexOf(S)===-1},this);
m.length&&(J=m)}for(let m of J)m instanceof xs?vzu(this,m):u61(this,m);for(let [m,S]of Object.entries(this.TT)){let Y=m,h=S;this.qB[Y]?(h.element.parentNode||(h instanceof zaZ||h instanceof qPv||g.ZZ(this.TT,(V,K)=>{K!==Y&&V.G.params.yg===h.G.params.yg&&V.G.params.iV===h.G.params.iV&&V.G.params.US===h.G.params.US&&(V.dispose(),delete this.TT[K]);return K===Y},this),this.B.element.appendChild(h.element)),h.B(this.qB[Y])):(h.dispose(),delete this.TT[Y])}}}TM(){L9(this,{},!0);
g.Ig(this.player,"captionssettingschanged")}v6(){var J=this.b5.X("enable_player_captions_new_style_defaults")?xFu:cGs,m=J.Y7;J={background:m.background,backgroundOpacity:m.backgroundOpacity,charEdgeStyle:m.charEdgeStyle,color:m.color,fontFamily:m.fontFamily,fontSizeIncrement:m.fontSizeIncrement,fontStyle:m.bold&&m.italic?3:m.bold?1:m.italic?2:0,textOpacity:m.textOpacity,windowColor:J.windowColor,windowOpacity:J.windowOpacity};m=NB()||{};m.background!=null&&(J.background=m.background);m.backgroundOverride!=
null&&(J.backgroundOverride=m.backgroundOverride);m.backgroundOpacity!=null&&(J.backgroundOpacity=m.backgroundOpacity);m.backgroundOpacityOverride!=null&&(J.backgroundOpacityOverride=m.backgroundOpacityOverride);m.charEdgeStyle!=null&&(J.charEdgeStyle=m.charEdgeStyle);m.charEdgeStyleOverride!=null&&(J.charEdgeStyleOverride=m.charEdgeStyleOverride);m.color!=null&&(J.color=m.color);m.colorOverride!=null&&(J.colorOverride=m.colorOverride);m.fontFamily!=null&&(J.fontFamily=m.fontFamily);m.fontFamilyOverride!=
null&&(J.fontFamilyOverride=m.fontFamilyOverride);m.fontSizeIncrement!=null&&(J.fontSizeIncrement=m.fontSizeIncrement);m.fontSizeIncrementOverride!=null&&(J.fontSizeIncrementOverride=m.fontSizeIncrementOverride);m.fontStyle!=null&&(J.fontStyle=m.fontStyle);m.fontStyleOverride!=null&&(J.fontStyleOverride=m.fontStyleOverride);m.textOpacity!=null&&(J.textOpacity=m.textOpacity);m.textOpacityOverride!=null&&(J.textOpacityOverride=m.textOpacityOverride);m.windowColor!=null&&(J.windowColor=m.windowColor);
m.windowColorOverride!=null&&(J.windowColorOverride=m.windowColorOverride);m.windowOpacity!=null&&(J.windowOpacity=m.windowOpacity);m.windowOpacityOverride!=null&&(J.windowOpacityOverride=m.windowOpacityOverride);return J}L3(J,m){var S={};Object.assign(S,NB());Object.assign(S,J);L9(this,S,m);g.Ig(this.player,"captionssettingschanged")}Yk(){!this.D&&this.loaded&&(g.xR(this.TT,function(J,m){J.dispose();delete this.TT[m]},this),this.vS())}f4(J,m){switch(J){case "fontSize":if(isNaN(m))break;
J=g.sh(m,-2,4);this.L3({fontSizeIncrement:J});return J;case "reload":m&&!this.D&&XA(this,this.G,!0);break;case "stickyLoading":m!==void 0&&this.b5.eN&&(this.b5.X("enable_player_captions_persistence_state_machine")?dJ(this,!(!m||!m.userInitiated)):g.PH(this.b5)?t7(this,!!m):H6(this,!!m));break;case "track":return dFg(this,m);case "tracklist":return this.J?g.lV(g.iK(this.J.J,!(!m||!m.includeAsr)),S=>g.oY(S)):[];
case "translationLanguages":return this.J?this.J.W.map(S=>Object.assign({},S)):[];
case "sampleSubtitles":this.D||m===void 0||qB(this,!!m);break;case "sampleSubtitlesCustomized":this.D||qB(this,!!m,m);break;case "recommendedTranslationLanguages":return g.RY();case "defaultTranslationSourceTrackIndices":return this.J?this.J.TT:[]}}getOptions(){var J="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.b5.eN&&J.push("stickyLoading");return J}JN(){var J=this.G;if(this.V.yB("captions")){if(this.b5.X("html5_modify_caption_vss_logging"))return(J=this.videoData.pu??
null)?{cc:g.ZjQ(J)}:{};if(J){let m=J.vssId;J.translationLanguage&&m&&(m=`t${m}.${g.Wi(J)}`);return{cc:m}}}return{}}OF(J){this.isSubtitlesOn()?(this.b5.X("enable_player_captions_persistence_state_machine")&&J?dJ(this,!1):g.PH(this.b5)?t7(this,!1):H6(this,!1),aK(this),XA(this,null,!0)):this.Nm(J)}Nm(J){var m=iz(this)||!this.G?f9(this,!0):this.G;m&&this.OR(m.vssId,"m");this.isSubtitlesOn()||XA(this,m,this.b5.X("enable_player_captions_persistence_state_machine")?J:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.G&&!iz(this)}jX(){var J=iz(this);U$(this,J)?XA(this,this.getAudioTrack().J,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Nh()&&(this.C=!1,this.G=null,this.J&&(this.J.dispose(),this.J=null)),this.Bm()&&(J?XA(this,f9(this,!1),!1):this.load()))}nH(J){J&&(this.mQ={top:J.top,right:J.right,bottom:J.bottom,left:J.left,width:1-J.left-J.right,height:1-J.top-J.bottom},this.B.element.style.top=`${this.mQ.top*100}%`,this.B.element.style.left=`${this.mQ.left*100}%`,this.B.element.style.width=
`${this.mQ.width*100}%`,this.B.element.style.height=`${this.mQ.height*100}%`,this.B.element.style.position="absolute",J=LbR(this))&&(this.B.element.style.width=`${J.width}px`,this.B.element.style.height=`${J.height}px`)}onVideoDataChange(J,m){J==="newdata"&&(this.videoData=m,this.loaded&&this.unload(),this.C=!1,this.G=null,this.J&&(this.J.dispose(),this.J=null,g.Ig(this.player,"captionschanged",{})),this.Bm()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}wX(){if(this.b5.jN().J.sE(g.rOQ)){if(this.loaded&&
this.unload(),this.aM=this.V.isFullscreen()||this.b5.controlsType==="3",this.D=uz(this),this.N=seZ(this),this.D||this.N){var J=this.V.B9();J&&!J.EE()&&J.C();this.Qw()}}else(J=this.V.B9())&&!J.EE()&&J.C(),this.V.isFullscreen()?(this.D=this.aM=!0,this.loaded&&this.Qw()):(this.aM=this.b5.controlsType==="3",this.D=uz(this));XA(this,this.G)}oM(){var J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;J&&g.c9(this.player,"innertubeCommand",J)}ER(J,m,S){var Y=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,h="";J&&(h=J.vssId,h=h.replace(Y,""));var V="";if(J&&J.getId()&&this.b5.jN().J.sE(g.hOD))if(V=J.getId()||"",V.includes(";"))V=V.split(";").map(E=>E.replace(Y,"")).join(";");
else{V=V.replace(Y,"");var K="";J.getXtags()&&(K=J.getXtags(),K=K.replace(Y,""),V=V.concat(`;${K}`))}else J&&J.getId()&&(V=J.getId()||""),K="",J&&J.getXtags()&&(K=J.getXtags(),K=K.replace(Y,""),V=V.concat(`;${K}`));this.K==="HLS"&&(V="");this.V.ER(m?h:"",m?V:"",S)}OR(J,m){J=(J||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");J.length>0&&this.V.OR(J,m)}});})(_yt_player);
