(function(g){var window=this;'use strict';var vbZ=function(J,m){g.c9(J,"onAutonavCoundownStarted",m)},uhk=function(J){return J.isBackground()&&J.Ik()},LOX=function(J,m){m=m.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
J.N=m?.navigationEndpoint;m=m?.trackingParams;J.playButton&&m&&J.V.setTrackingParams(J.playButton.element,m)},kC=function(J){var m=TH(J),S=Math,Y=S.min;
var h=J.C?Date.now()-J.C:0;S=Y.call(S,h,m);gx(J,Math.ceil((m-S)/1E3));m-S<=500&&J.J()?J.select(!0):J.J()&&J.B.start()},ye=function(J){var m=J.V.vL(!0,J.V.isFullscreen());
g.Zh(J.container.element,"ytp-autonav-endscreen-small-mode",J.tk(m));g.Zh(J.container.element,"ytp-autonav-endscreen-is-premium",!!J.suggestion&&!!J.suggestion.Lq);g.Zh(J.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!J.V.rp());g.Zh(J.V.getRootNode(),"countdown-running",J.J());g.Zh(J.container.element,"ytp-player-content",J.V.rp());J.V.X("web_post_play_autonav_embiggening")||g.pZ(J.overlay.element,{width:`${m.width}px`});if(J.V.X("web_post_play_autonav_embiggening")){var S=J.V.getRootNode().getBoundingClientRect();
m=Math.min(720,S.width*.5);var Y=m*.5625;S=S.height-36-60;Y>S&&(Y=S,m=16/9*Y);g.pZ(J.G.vB("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${Y}px`,width:`${m}px`});g.pZ(J.container.element,{width:`${m}px`})}J.J()||(J.V.rp()?gx(J,Math.round(TH(J)/1E3)):gx(J),m=!!J.suggestion&&!!J.suggestion.Hg,Y=J.V.getVideoData(),Y=Y?.autonavState===1&&Y?.Mu&&J.V.rp()?!1:J.V.rp()||!(J.suggestion&&J.suggestion.Hg),g.Zh(J.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!Y&&m),g.Zh(J.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",Y&&!m),J.L.Rq(J.V.rp()))},gx=function(J,m=-1){J=J.G.vB("ytp-autonav-endscreen-upnext-header");
g.$c(J);if(m>=0){m=String(m);let Y="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],h="Up next in $SECONDS".indexOf(Y);if(h>=0){var S=g.h2("Up next in $SECONDS".slice(0,h));J.appendChild(S);S=g.Yc("span");g.nc(S,"ytp-autonav-endscreen-upnext-header-countdown-number");g.gd(S,m);J.appendChild(S);m=g.h2("Up next in $SECONDS".slice(h+Y.length));J.appendChild(m);return}}g.gd(J,"Up next")},TH=function(J){return J.V.isFullscreen()?(J=J.V.getVideoData()?.oz,J===-1||J===void 0?8E3:J):J.V.FA()>=0?
J.V.FA():g.EI(J.V.U().experiments,"autoplay_time")||1E4},Di=function(J,m){m=qrR(J,m);
var S=Math,Y=S.min;var h=(0,g.l)()-J.C;S=Y.call(S,h,m);m=m===0?1:Math.min(S/m,1);J.u5.setAttribute("stroke-dashoffset",`${-211*(m+1)}`);m>=1&&J.J()&&!J.isCasting()?J.select(!0):J.J()&&J.G.start()},qrR=function(J,m){return m?m:J.api.isFullscreen()?(J=J.api.getVideoData()?.oz,J===-1||J===void 0?8E3:J):J.api.FA()>=0?J.api.FA():g.EI(J.api.U().experiments,"autoplay_time")||1E4},RV=function(J){return g.ag(J.player)&&J.B()&&!J.D},rx=function(J){var m=J.rp();
m!==J.W&&(J.W=m,J.player.publish("autonavvisibility"))},NL=function(J){return g.ag(J.player)&&J.B()&&!J.A},BS=function(J){var m=J.rp();
m!==J.mQ&&(J.mQ=m,J.player.publish("autonavvisibility"))},zBt=function(J){J=J.U();
return J.Mu&&!J.disableOrganicUi},dmk=function(J){var m=J.player.getVideoData();
if(!m||J.J===m.vS)return!1;J.J=m.vS;return!0},w0u=function(J){J.player.h8("endscreen");
var m=J.player.getVideoData();m=new g.hq(Math.max((m.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var S=new g.hq(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});J.player.zc([m,S])};
g.rV.prototype.FA=g.hn(16,function(){return this.app.FA()});
g.YD.prototype.FA=g.hn(15,function(){return this.getVideoData().xZ});
g.Ry.prototype.F3=g.hn(14,function(J){this.IB().F3(J)});
g.S3.prototype.F3=g.hn(13,function(J){this.PP!==J&&(this.PP=J,this.u3())});
var Qe=class extends g.C{constructor(J){super({S:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.N=void 0;this.C=0;J.X("web_post_play_autonav_embiggening")&&g.xd(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.C({S:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.O(this,this.container);this.container.VE(this.element);var m=J.U(),S=m.D;this.V=J;this.suggestion=null;this.onVideoDataChange("newdata",this.V.getVideoData());this.j(J,"videodatachange",
this.onVideoDataChange);this.G=new g.C({S:"div",Z:"ytp-autonav-endscreen-upnext-container",O:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{S:"div",Z:"ytp-autonav-endscreen-topbar-container",Y:[{S:"div",Z:"ytp-autonav-endscreen-upnext-header"},{S:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",g2:"{{autoplayAlternativeHeader}}"}]},{S:"a",Z:"ytp-autonav-endscreen-link-container",
O:{href:"{{url}}",target:S?m.N:""},Y:[{S:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",O:{style:"{{background}}"},Y:[{S:"div",O:{"aria-label":"{{timestamp}}"},w2:["ytp-autonav-timestamp"],g2:"{{duration}}"},{S:"div",w2:["ytp-autonav-live-stamp"],g2:"Live"},{S:"div",w2:["ytp-autonav-upcoming-stamp"],g2:"Upcoming"}]},{S:"div",Z:"ytp-autonav-endscreen-video-info",Y:[{S:"div",Z:"ytp-autonav-endscreen-premium-badge"},{S:"div",Z:"ytp-autonav-endscreen-upnext-title",g2:"{{title}}"},{S:"div",Z:"ytp-autonav-endscreen-upnext-author",
g2:"{{author}}"},{S:"div",Z:"ytp-autonav-view-and-date",g2:"{{views_and_publish_time}}"},{S:"div",Z:"ytp-autonav-author-and-view",g2:"{{author_and_views}}"}]}]}]});g.O(this,this.G);this.G.VE(this.container.element);S||this.j(this.G.vB("ytp-autonav-endscreen-link-container"),"click",this.GT);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.G.vB("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.C({S:"button",Z:"ytp-autonav-endscreen-upnext-header-close-button",
O:{"aria-label":"Cancel auto-play"}});g.O(this,this.closeButton);J.X("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.TT,this),this.V.createClientVe(this.closeButton.element,this,115129),this.G.vB("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.C({S:"div",Z:"ytp-autonav-overlay"});g.O(this,this.overlay);this.overlay.VE(this.container.element);this.L=new g.C({S:"div",Z:"ytp-autonav-endscreen-button-container"});g.O(this,
this.L);this.L.VE(this.container.element);this.cancelButton=new g.C({S:"button",w2:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],O:{"aria-label":"Cancel auto-play"},g2:"Cancel"});g.O(this,this.cancelButton);this.cancelButton.VE(this.L.element);this.cancelButton.listen("click",this.TT,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.C({S:"a",w2:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],O:{href:"{{url}}",role:"button","aria-label":"Play next video"},g2:"Play now"});g.O(this,this.playButton);this.playButton.VE(this.L.element);this.playButton.listen("click",this.GT,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(m=this.V.getVideoData())&&LOX(this,m);this.B=new g.P$(()=>{kC(this)},500);
g.O(this,this.B);this.mQ();this.j(J,"autonavvisibility",this.mQ)}W(J){this.suggestion!==J&&(this.suggestion=J,g.Xf(this.G,J),this.playButton.updateValue("url",this.suggestion.Pt()),ye(this))}J(){return this.C>0}A(){this.J()||(this.C=Date.now(),kC(this),vbZ(this.V,TH(this)),g.Zh(this.V.getRootNode(),"countdown-running",this.J()))}D(){this.K();kC(this);var J=this.G.vB("ytp-autonav-endscreen-upnext-header");J&&g.gd(J,"Up next")}K(){this.J()&&(this.B.stop(),this.C=0)}select(J=!1){this.V.nextVideo(!1,
J);this.K()}GT(J){g.EG(J,this.V)&&(J.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):J.currentTarget===this.G.vB("ytp-autonav-endscreen-link-container")&&(J=this.G.vB("ytp-autonav-endscreen-link-container"),this.V.logVisibility(J,!0),this.V.logClick(J)),this.N?(g.c9(this.V,"innertubeCommand",this.N),this.K()):this.select())}TT(){this.V.logClick(this.cancelButton.element);g.wQ(this.V,!0);this.cancelCommand&&g.c9(this.V,"innertubeCommand",this.cancelCommand)}onVideoDataChange(J,
m){LOX(this,m);this.cancelCommand=m.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}mQ(){var J=this.V.rp();this.gX!==J&&this.Rq(J);ye(this);this.V.logVisibility(this.container.element,J);this.V.logVisibility(this.cancelButton.element,J);this.V.logVisibility(this.G.vB("ytp-autonav-endscreen-link-container"),J);this.V.logVisibility(this.playButton.element,J)}tk(J){return J.width<400||J.height<459}};var PS=class extends g.C{constructor(J,m){super({S:"div",w2:["html5-endscreen","ytp-player-content",m||"base-endscreen"]});this.created=!1;this.player=J}create(){this.created=!0}destroy(){this.created=!1}B(){return!1}rp(){return!1}N(){return!1}};var Umu=class extends g.C{constructor(J){super({S:"div",w2:["ytp-upnext","ytp-player-content"],O:{"aria-label":"{{aria_label}}"},Y:[{S:"div",Z:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{S:"span",Z:"ytp-upnext-top",Y:[{S:"span",Z:"ytp-upnext-header",g2:"Up Next"},{S:"span",Z:"ytp-upnext-title",g2:"{{title}}"},{S:"span",Z:"ytp-upnext-author",g2:"{{author}}"}]},{S:"a",Z:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"Play next video"},Y:[{S:"svg",O:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},Y:[{S:"circle",Z:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{S:"circle",Z:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{S:"path",Z:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{S:"span",Z:"ytp-upnext-bottom",Y:[{S:"span",Z:"ytp-upnext-cancel"},
{S:"span",Z:"ytp-upnext-paused",g2:"Auto-play is paused"}]}]});this.api=J;this.cancelButton=null;this.u5=this.vB("ytp-svg-autoplay-ring");this.B=this.notification=this.G=this.suggestion=null;this.N=new g.P$(this.L,5E3,this);this.C=0;var m=this.vB("ytp-upnext-cancel");this.cancelButton=new g.C({S:"button",w2:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Cancel auto-play"},g2:"Cancel"});g.O(this,this.cancelButton);this.cancelButton.listen("click",this.TT,this);this.cancelButton.VE(m);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.O(this,this.N);this.api.createClientVe(this.element,this,18788);m=this.vB("ytp-upnext-autoplay-icon");this.j(m,"click",this.GT);this.api.createClientVe(m,this,115130);this.mQ();this.j(J,"autonavvisibility",this.mQ);this.j(J,"mdxnowautoplaying",this.A0);this.j(J,"mdxautoplaycanceled",this.aM);g.Zh(this.element,"ytp-upnext-mobile",this.api.U().K)}L(){this.notification&&(this.N.stop(),this.rg(this.B),this.B=null,this.notification.close(),
this.notification=null)}W(J){this.suggestion=J;g.Xf(this,J,"hqdefault.jpg")}mQ(){this.Rq(this.api.rp());this.api.logVisibility(this.element,this.api.rp());this.api.logVisibility(this.vB("ytp-upnext-autoplay-icon"),this.api.rp());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.rp())}MB(){window.focus();this.L()}A(J){this.J()||(g.nP("a11y-announce",`Up Next ${this.suggestion.title}`),this.C=(0,g.l)(),this.G=new g.P$(()=>{Di(this,J)},25),Di(this,J),vbZ(this.api,qrR(this,
J)));
g.bw(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}J(){return!!this.G}isCasting(){return this.api.getPresentingPlayerType()===3}D(){this.K();this.C=(0,g.l)();Di(this);g.xd(this.element,"ytp-upnext-autoplay-paused")}K(){this.J()&&(this.G.dispose(),this.G=null)}select(J=!1){if(this.api.U().X("autonav_notifications")&&J&&window.Notification&&typeof document.hasFocus==="function"){let m=Notification.permission;m==="default"?Notification.requestPermission():m!=="granted"||document.hasFocus()||
(this.L(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Cx()}),this.B=this.j(this.notification,"click",this.MB),this.N.start())}this.K();this.api.nextVideo(!1,J)}GT(J){!g.T3(this.cancelButton.element,J.target)&&g.EG(J,this.api)&&(this.api.rp()&&this.api.logClick(this.vB("ytp-upnext-autoplay-icon")),this.select())}TT(){this.api.rp()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.wQ(this.api,!0)}A0(J){this.isCasting();this.show();this.A(J)}aM(){this.isCasting();
this.K();this.hide()}fz(){this.K();this.L();super.fz()}};var ifI=class extends PS{constructor(J){super(J,"videowall-endscreen");this.V=J;this.stills=[];this.D=this.videoData=null;this.A=this.W=!1;this.mQ=null;g.xd(this.element,"modern-videowall-endscreen");this.G=new g.PW(this);g.O(this,this.G);this.L=new g.P$(()=>{g.xd(this.element,"ytp-show-tiles")},0);
g.O(this,this.L);this.table=new g.vN({S:"div",Z:"ytp-modern-endscreen-content"});g.O(this,this.table);this.table.VE(this.element);J.getVideoData().vS?this.J=new Qe(J):this.J=new Umu(J);g.O(this,this.J);g.H9(this.player,this.J.element,4);J.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var J=this.player.getVideoData();J&&(this.videoData=J);this.K();this.G.j(this.player,"appresize",this.K);this.G.j(this.player,"onVideoAreaChange",this.K);this.G.j(this.player,"videodatachange",
this.onVideoDataChange);this.G.j(this.player,"autonavchange",this.C);this.G.j(this.player,"onAutonavCancelled",this.TT);J=this.videoData.autonavState;J!==this.mQ&&this.C(J,!1);this.G.j(this.element,"transitionend",this.GT)}destroy(){this.G.G();g.Ra(this.stills);this.stills=[];super.destroy();g.bw(this.element,"ytp-show-tiles");this.L.stop();this.mQ=this.videoData.autonavState}B(){return this.videoData?.Mu||this.videoData.autonavState!==1}show(){var J=this.gX;super.show();g.bw(this.element,"ytp-show-tiles");
this.player.U().K?g.W$(this.L):this.L.start();(this.A||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.wQ(this.player,!1);RV(this)?(rx(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||uhk(this.player.al())&&this.player.X("web_player_pip_logging_fix")?this.J.select(!0):this.J.A():this.videoData.autonavState===3&&this.J.D()):(g.wQ(this.player,!0),rx(this));J!==this.gX&&this.player.logVisibility(this.element,!0)}hide(){var J=this.gX;super.hide();this.J.D();rx(this);
J!==this.gX&&this.player.logVisibility(this.element,!1)}GT(J){J.target===this.element&&this.K()}K(){var J=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.eN()];if(J.length){var m=this.V.vL(!0,this.V.isFullscreen()),S=Math.floor((m.width-64+16)/(g.sh(m.width*.27,250,450)+16));m=Math.min(3,Math.floor((m.height-64)/((m.width-64-(S-1)*16)/S*.5625+70)));g.OH(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.xd(this.element,`ytp-modern-endscreen-limit-rows-${m}`);g.Zh(this.element,"ytp-modern-endscreen-single-item",S===1);g.Zh(this.element,"ytp-modern-endscreen-row-0",m===0);S=this.table.element;S.ariaLive="polite";this.J.W(this.videoData.eN());this.J instanceof Qe&&ye(this.J);g.Zh(this.element,"ytp-endscreen-takeover",RV(this));rx(this);m=0;S.ariaBusy="true";var Y=J.length;for(let h=0;h<Y;h++){let V=h%Y,K=this.stills[h];K||(K=new g.Yzv(this.player),this.stills[h]=K,S.appendChild(K.element));g.gTi(K,
J[V]);m++}this.stills.length=m}}onVideoDataChange(){var J=this.player.getVideoData({playerType:1});this.videoData!==J&&(J?.eN()?(this.videoData=J,this.K()):this.player.yE("missg",{vid:J?.videoId||"",cpn:J?.clientPlaybackNonce||""}))}N(){return this.J.J()}C(J,m=!1){var S=this.videoData?.Mu;if(J===1){if(!S||m)this.A=!1,this.D=this.videoData.clientPlaybackNonce;this.J.K();this.gX&&this.K()}else this.A=!0,this.gX&&RV(this)&&(J===2?this.J.A():J===3&&this.J.D())}TT(J){if(J){for(J=0;J<this.stills.length;J++)this.V.logVisibility(this.stills[J].element,
!0);this.C(1,!0)}else this.D=null,this.A=!1;this.K()}rp(){return this.gX&&RV(this)}};var lUe=class extends g.C{constructor(J){var m=J.U(),S=g.xo||g.ng?{style:"will-change: opacity"}:void 0,Y=m.D,h=["ytp-videowall-still"];m.K&&h.push("ytp-videowall-show-text");super({S:"a",w2:h,O:{href:"{{url}}",target:Y?m.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Y:[{S:"div",Z:"ytp-videowall-still-image",O:{style:"{{background}}"}},{S:"span",Z:"ytp-videowall-still-info",O:{"aria-hidden":"true"},Y:[{S:"span",Z:"ytp-videowall-still-info-bg",
Y:[{S:"span",Z:"ytp-videowall-still-info-content",O:S,Y:[{S:"span",Z:"ytp-videowall-still-info-title",g2:"{{title}}"},{S:"span",Z:"ytp-videowall-still-info-author",g2:"{{author_and_views}}"},{S:"span",Z:"ytp-videowall-still-info-live",g2:"Live"},{S:"span",Z:"ytp-videowall-still-info-duration",g2:"{{duration}}"}]}]}]},{S:"span",w2:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],O:{"aria-hidden":"true"},Y:[{S:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{S:"span",
Z:"ytp-videowall-still-listlabel-length",Y:[" (",{S:"span",g2:"{{playlist_length}}"},")"]}]},{S:"span",w2:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],O:{"aria-hidden":"true"},Y:[{S:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{S:"span",Z:"ytp-videowall-still-listlabel-length",g2:" (50+)"}]}]});this.suggestion=null;this.G=Y;this.api=J;this.J=new g.PW(this);g.O(this,this.J);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.J.j(J,"videodatachange",
this.onVideoDataChange);J.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.YA(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.i$||void 0)&&this.api.logClick(this.element)}onClick(J){if(g.yK(this.api.U())&&this.api.X("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let m=this.suggestion.Pt(),S={};g.f_(this.api,S);m=g.ZB(m,S);g.Tk(m,this.api,J)}else g.EG(J,this.api,
this.G,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(J){switch(J.keyCode){case 13:case 32:J.defaultPrevented||(this.select(),J.preventDefault())}}onVideoDataChange(){var J=this.api.getVideoData(),m=this.api.U();this.G=J.y8?!1:m.D}};var fUu=class extends PS{constructor(J){super(J,"videowall-endscreen");this.V=J;this.D=0;this.stills=[];this.A=this.videoData=null;this.L=this.mQ=!1;this.TT=null;this.K=new g.PW(this);g.O(this,this.K);this.C=new g.P$(()=>{g.xd(this.element,"ytp-show-tiles")},0);
g.O(this,this.C);var m=new g.C({S:"button",w2:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Previous"},Y:[g.At()]});g.O(this,m);m.VE(this.element);m.listen("click",this.A0,this);this.table=new g.vN({S:"div",Z:"ytp-endscreen-content"});g.O(this,this.table);this.table.VE(this.element);m=new g.C({S:"button",w2:["ytp-button","ytp-endscreen-next"],O:{"aria-label":"Next"},Y:[g.vy()]});g.O(this,m);m.VE(this.element);m.listen("click",this.u5,this);J.getVideoData().vS?this.J=new Qe(J):this.J=new Umu(J);
g.O(this,this.J);g.H9(this.player,this.J.element,4);J.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var J=this.player.getVideoData();J&&(this.videoData=J);this.G();this.K.j(this.player,"appresize",this.G);this.K.j(this.player,"onVideoAreaChange",this.G);this.K.j(this.player,"videodatachange",this.onVideoDataChange);this.K.j(this.player,"autonavchange",this.W);this.K.j(this.player,"onAutonavCancelled",this.GT);J=this.videoData.autonavState;J!==this.TT&&this.W(J,!1);this.K.j(this.element,
"transitionend",this.aM)}destroy(){this.K.G();g.Ra(this.stills);this.stills=[];super.destroy();g.bw(this.element,"ytp-show-tiles");this.C.stop();this.TT=this.videoData.autonavState}B(){return this.videoData?.Mu||this.videoData?.autonavState!==1}show(){var J=this.gX;super.show();g.bw(this.element,"ytp-show-tiles");this.player.U().K?g.W$(this.C):this.C.start();(this.L||this.A&&this.A!==this.videoData.clientPlaybackNonce)&&g.wQ(this.player,!1);NL(this)?(BS(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||uhk(this.player.al())&&this.player.X("web_player_pip_logging_fix")?this.J.select(!0):this.J.A():this.videoData.autonavState===3&&this.J.D()):(g.wQ(this.player,!0),BS(this));J!==this.gX&&this.player.logVisibility(this.element,!0)}hide(){var J=this.gX;super.hide();this.J.D();BS(this);J!==this.gX&&this.player.logVisibility(this.element,!1)}aM(J){J.target===this.element&&this.G()}G(){var J=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.eN()];if(J.length){g.xd(this.element,
"ytp-endscreen-paginate");var m=this.V.vL(!0,this.V.isFullscreen()),S=g.Ao(this.V);S&&(S=S.MQ()?48:32,m.width-=S*2);var Y=m.width/m.height,h=96/54,V=S=2,K=Math.max(m.width/96,2),E=Math.max(m.height/54,2),T=J.length;var k=T*4;for(k-=4;k>0&&(S<K||V<E);){var y=S/2,D=V/2,R=S<=K-2&&k>=D*4,r=V<=E-2&&k>=y*4;if((y+1)/D*h/Y>Y/(y/(D+1)*h)&&r)k-=y*4,V+=2;else if(R)k-=D*4,S+=2;else if(r)k-=y*4,V+=2;else break}h=!1;k>=12&&T*4-k<=6&&(V>=4||S>=4)&&(h=!0);k=S*96;K=V*54;Y=k/K<Y?m.height/K:m.width/k;Y=Math.min(Y,2);
k=Math.floor(Math.min(m.width,k*Y));K=Math.floor(Math.min(m.height,K*Y));m=this.table.element;m.ariaLive="polite";g.HB(m,k,K);g.pZ(m,{marginLeft:`${k/-2}px`,marginTop:`${K/-2}px`});this.J.W(this.videoData.eN());this.J instanceof Qe&&ye(this.J);g.Zh(this.element,"ytp-endscreen-takeover",NL(this));BS(this);k+=4;K+=4;Y=0;m.ariaBusy="true";for(E=0;E<S;E++)for(y=0;y<V;y++)if(R=Y,r=0,h&&E>=S-2&&y>=V-2?r=1:y%2===0&&E%2===0&&(y<2&&E<2?y===0&&E===0&&(r=2):r=2),R=g.xQ(R+this.D,T),r!==0){D=this.stills[Y];D||
(D=new lUe(this.player),this.stills[Y]=D,m.appendChild(D.element));var W=Math.floor(K*y/V);let b=Math.floor(k*E/S),v=Math.floor(K*(y+r)/V)-W-4,q=Math.floor(k*(E+r)/S)-b-4;g.dd(D.element,b,W);g.HB(D.element,q,v);g.pZ(D.element,"transitionDelay",(y+E)/20+"s");g.Zh(D.element,"ytp-videowall-still-mini",r===1);g.Zh(D.element,"ytp-videowall-still-large",r>2);r=Math.max(q,v);g.Zh(D.element,"ytp-videowall-still-round-large",r>=256);g.Zh(D.element,"ytp-videowall-still-round-medium",r>96&&r<256);g.Zh(D.element,
"ytp-videowall-still-round-small",r<=96);R=J[R];D.suggestion!==R&&(D.suggestion=R,r=D.api.U(),W=g.sH(D.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Xf(D,R,W),g.yK(r)&&!D.api.X("web_player_log_click_before_generating_ve_conversion_params")&&(r=R.Pt(),W={},g.ZY(D.api,"addEmbedsConversionTrackingParams",[W]),r=g.ZB(r,W),D.updateValue("url",r)),(R=(R=R.sessionData)&&R.itct)&&D.api.setTrackingParams(D.element,R));Y++}m.ariaBusy="false";g.Zh(this.element,"ytp-endscreen-paginate",
Y<T);for(J=this.stills.length-1;J>=Y;J--)S=this.stills[J],g.EE(S.element),g.Dm(S);this.stills.length=Y}}onVideoDataChange(){var J=this.player.getVideoData({playerType:1});this.videoData!==J&&(J?.eN()?(this.D=0,this.videoData=J,this.G()):this.player.yE("missg",{vid:J?.videoId||"",cpn:J?.clientPlaybackNonce||""}))}u5(){this.D+=this.stills.length;this.G()}A0(){this.D-=this.stills.length;this.G()}N(){return this.J.J()}W(J,m=!1){var S=this.videoData?.Mu;if(J===1){if(!S||m)this.L=!1,this.A=this.videoData.clientPlaybackNonce;
this.J.K();this.gX&&this.G()}else this.L=!0,this.gX&&NL(this)&&(J===2?this.J.A():J===3&&this.J.D())}GT(J){if(J){for(J=0;J<this.stills.length;J++)this.V.logVisibility(this.stills[J].element,!0);this.W(1,!0)}else this.A=null,this.L=!1;this.G()}rp(){return this.gX&&NL(this)}};var tob=class extends g.C{constructor(J){super({S:"button",w2:["ytp-watch-on-youtube-button","ytp-button"],g2:"{{content}}"});this.V=J;this.buttonType=this.buttonType=1;this.J();this.buttonType===2&&g.xd(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.J);this.Rq(!0)}J(){switch(this.buttonType){case 1:var J="Watch again on YouTube";var m=156915;break;case 2:J="Continue watching on YouTube";m=156942;break;default:J="Continue watching on YouTube",
m=156942}this.update({content:J});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,m)}onClick(J){this.V.X("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.Tk(this.getVideoUrl(),this.V,J);this.V.X("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)}getVideoUrl(){var J=!0;switch(this.buttonType){case 1:J=!0;break;case 2:J=!1}J=this.V.getVideoUrl(J,!1,!1,!0);var m=
this.V.U();if(g.yK(m)){let S={};g.yK(m)&&g.ZY(this.V,"addEmbedsConversionTrackingParams",[S]);J=g.ZB(J,S)}return J}logVisibility(){this.V.logVisibility(this.element,this.gX&&this.eN)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}K1(J){super.K1(J);this.logVisibility()}};var Hfu=class extends PS{constructor(J){super(J,"watch-again-on-youtube-endscreen");this.watchButton=new tob(J);g.O(this,this.watchButton);this.watchButton.VE(this.element);g.xlH(J)&&(this.J=new g.u8u(J),g.O(this,this.J),this.G=new g.C({S:"div",w2:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],O:{tabIndex:"-1"},Y:[this.J]}),g.O(this,this.G),this.J.VE(this.G.element),this.G.VE(this.element));J.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.J?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let m=this.G;if(m){var J=this.J.hasSuggestions();g.Zh(this.element,"ytp-shorts-branded-ui",J);J?m.show():m.hide()}g.Ao(this.player)?.F3(!0);this.player.logVisibility(this.element,!0);this.watchButton.K1(!0)}}hide(){super.hide();g.Ao(this.player)?.F3(!1);this.player.logVisibility(this.element,!1);this.watchButton.K1(!1)}};g.gs("endscreen",class extends g.qa{constructor(J){super(J);this.endScreen=null;this.J=this.G=!1;this.listeners=new g.PW(this);g.O(this,this.listeners);var m=J.U();J.isEmbedsShortsMode()?this.endScreen=new Hfu(J):zBt(J)?(this.G=!0,dmk(this),m.X("delhi_modern_endscreen")?this.endScreen=new ifI(J):this.endScreen=new fUu(J)):this.endScreen=new PS(J);g.O(this,this.endScreen);g.H9(J,this.endScreen.element,4);w0u(this);this.listeners.j(J,"videodatachange",this.onVideoDataChange,this);this.listeners.j(J,
g.zz("endscreen"),S=>{this.onCueRangeEnter(S)});
this.listeners.j(J,g.da("endscreen"),S=>{this.onCueRangeExit(S)})}Bm(){var J=this.player.getVideoData(),m=J.mutedAutoplay&&(J.limitedPlaybackDurationInSeconds>0||J.endSeconds>0||J.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!m)return!0;var S=!(!J?.eN()&&!J?.suggestions?.length);S=!zBt(this.player)||S;var Y=J.OZ,h=this.player.mf();return(S||!!J?.Mu)&&!Y&&!h&&!m}rp(){return this.endScreen.rp()}Fa(){return this.rp()?this.endScreen.N():!1}fz(){this.player.h8("endscreen");super.fz()}load(){{let S=this.player.getVideoData(),Y=S.transitionEndpointAtEndOfStream;if(Y&&Y.videoId){var J=this.player.aq().KX.get("heartbeat");var m=S.eN();!m||Y.videoId!==m.videoId||S.vR?(this.player.YA(Y.videoId,
void 0,void 0,!0,!0,Y),J&&J.T2("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),J=!0):J=!1}else J=!1}J||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(J){this.Bm()&&(this.endScreen.created||this.endScreen.create(),J.getId()==="load"&&this.load())}onCueRangeExit(J){J.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){w0u(this);this.G&&dmk(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new fUu(this.player),g.O(this,this.endScreen),g.H9(this.player,this.endScreen.element,4))}});})(_yt_player);
